import type { IpcApi } from '@/shared/types/ipc';
import type { DashboardFilters } from '@/shared/types/dashboard';

function getApi(): IpcApi {
  if (typeof window === 'undefined' || !window.electronAPI) {
    throw new Error(
      "API Electron indisponible. Lancez l'application via dev.bat ou npm run dev.",
    );
  }
  return window.electronAPI;
}

const api = () => getApi();

export const ipcClient: IpcApi = {
  app: {
    getVersion: () => api().app.getVersion(),
    ping: () => api().app.ping(),
  },
  auth: {
    login: (payload) => api().auth.login(payload),
    logout: (sessionToken) => api().auth.logout(sessionToken),
    restore: (sessionToken) => api().auth.restore(sessionToken),
    getCurrentUser: () => api().auth.getCurrentUser(),
    getProfile: () => api().auth.getProfile(),
    changePassword: (payload) => api().auth.changePassword(payload),
    listDemoAccounts: () => api().auth.listDemoAccounts(),
  },
  users: {
    list: (search) => api().users.list(search),
    get: (id) => api().users.get(id),
    create: (input) => api().users.create(input),
    update: (id, input) => api().users.update(id, input),
    deactivate: (id, reason) =>
      api().users.deactivate(id, reason),
    pendingCount: () => api().users.pendingCount(),
    activatePending: (id) => api().users.activatePending(id),
  },
  hotels: {
    list: () => api().hotels.list(),
    get: (id) => api().hotels.get(id),
    create: (input) => api().hotels.create(input),
    update: (id, input) => api().hotels.update(id, input),
    pickLogo: (hotelId) => api().hotels.pickLogo(hotelId),
    removeLogo: (hotelId) => api().hotels.removeLogo(hotelId),
    deactivate: (id, reason) =>
      api().hotels.deactivate(id, reason),
  },
  roles: {
    list: () => api().roles.list(),
    listForSelect: () => api().roles.listForSelect(),
    listPermissions: () => api().roles.listPermissions(),
    updatePermissions: (roleId, permissionCodes) =>
      api().roles.updatePermissions(roleId, permissionCodes),
  },
  rubriques: {
    list: () => api().rubriques.list(),
    create: (input) => api().rubriques.create(input),
    update: (id, input) => api().rubriques.update(id, input),
    delete: (id) => api().rubriques.delete(id),
    reorder: (items) => api().rubriques.reorder(items),
  },
  audit: {
    list: (filters) => api().audit.list(filters),
  },
  recettes: {
    rubriques: () => api().recettes.rubriques(),
    getSaisie: (hotelId, dateJournal) =>
      api().recettes.getSaisie(hotelId, dateJournal),
    saveSaisie: (input) => api().recettes.saveSaisie(input),
    historique: (filters) => api().recettes.historique(filters),
    historiqueGrouped: (filters) => api().recettes.historiqueGrouped(filters),
    updateLigne: (id, montant, observation, motif) =>
      api().recettes.updateLigne(id, montant, observation, motif),
    deleteLigne: (id, motif) =>
      api().recettes.deleteLigne(id, motif),
    deleteJournee: (hotelId, dateJournal, motif) =>
      api().recettes.deleteJournee(hotelId, dateJournal, motif),
    listAValider: (hotelId) => api().recettes.listAValider(hotelId),
    validerJour: (hotelId, dateJournal, motif) =>
      api().recettes.validerJour(hotelId, dateJournal, motif),
    refuserJour: (hotelId, dateJournal, motif) =>
      api().recettes.refuserJour(hotelId, dateJournal, motif),
    getMensuelle: (hotelId, annee, mois) =>
      api().recettes.getMensuelle(hotelId, annee, mois),
    saveMensuelle: (hotelId, annee, mois, payload) =>
      api().recettes.saveMensuelle(hotelId, annee, mois, payload),
  },
  objectifs: {
    list: (filters) => api().objectifs.list(filters),
    get: (hotelId, annee, mois) =>
      api().objectifs.get(hotelId, annee, mois),
    save: (input) => api().objectifs.save(input),
  },
  dashboard: {
    get: (filters) => api().dashboard.get(filters),
  },
  portmaster: {
    dashboard: (filters?: DashboardFilters) => api().portmaster.dashboard(filters),
    listBateaux: (search) => api().portmaster.listBateaux(search),
    getBateau: (id) => api().portmaster.getBateau(id),
    createBateau: (input) => api().portmaster.createBateau(input),
    updateBateau: (id, input) =>
      api().portmaster.updateBateau(id, input),
    deactivateBateau: (id) => api().portmaster.deactivateBateau(id),
    listEmplacements: () => api().portmaster.listEmplacements(),
    listEmplacementsLibres: () =>
      api().portmaster.listEmplacementsLibres(),
    listContrats: (statut) => api().portmaster.listContrats(statut),
    getContrat: (id) => api().portmaster.getContrat(id),
    saveContrat: (input, id) =>
      api().portmaster.saveContrat(input, id),
    submitContrat: (id) => api().portmaster.submitContrat(id),
    addEncaissement: (input) =>
      api().portmaster.addEncaissement(input),
    bateauxOptions: () => api().portmaster.bateauxOptions(),
    listClients: (search) => api().portmaster.listClients(search),
    getClient: (id) => api().portmaster.getClient(id),
    saveClient: (input, id) =>
      api().portmaster.saveClient(input, id),
    clientsOptions: () => api().portmaster.clientsOptions(),
    listBassins: () => api().portmaster.listBassins(),
    listQuais: (bassinId) => api().portmaster.listQuais(bassinId),
    listEmplacementsDetail: (filters) =>
      api().portmaster.listEmplacementsDetail(filters),
    searchReferentiel: (query) =>
      api().portmaster.searchReferentiel(query),
    listAlertes: () => api().portmaster.listAlertes(),
    listTarifs: () => api().portmaster.listTarifs(),
    getTarif: (id) => api().portmaster.getTarif(id),
    saveTarif: (input, id) => api().portmaster.saveTarif(input, id),
    simulerTarif: (tarifId, longueurM) =>
      api().portmaster.simulerTarif(tarifId, longueurM),
    listFactures: (statut) => api().portmaster.listFactures(statut),
    getFacture: (id) => api().portmaster.getFacture(id),
    createFacture: (input) => api().portmaster.createFacture(input),
    createFactureFromContrat: (contratId, tarifId) =>
      api().portmaster.createFactureFromContrat(contratId, tarifId),
    submitFacture: (id) => api().portmaster.submitFacture(id),
    addPaiementFacture: (input) =>
      api().portmaster.addPaiementFacture(input),
    listValidations: () => api().portmaster.listValidations(),
    validerEntite: (entityType, entityId, motif) =>
      api().portmaster.validerEntite(entityType, entityId, motif),
    rejeterEntite: (entityType, entityId, motif) =>
      api().portmaster.rejeterEntite(entityType, entityId, motif),
    listMouvements: () => api().portmaster.listMouvements(),
    createMouvement: (input) =>
      api().portmaster.createMouvement(input),
    recouvrementSummary: () =>
      api().portmaster.recouvrementSummary(),
    listCreances: () => api().portmaster.listCreances(),
    listRelances: () => api().portmaster.listRelances(),
    createRelance: (input) =>
      api().portmaster.createRelance(input),
    marquerRelanceEnvoyee: (id) =>
      api().portmaster.marquerRelanceEnvoyee(id),
  },
  settings: {
    getBranding: () => api().settings.getBranding(),
    getBusinessSector: () => api().settings.getBusinessSector(),
    getAppInfo: () => api().settings.getAppInfo(),
    update: (input) => api().settings.update(input),
    pickBrandAsset: (asset) => api().settings.pickBrandAsset(asset),
    removeBrandAsset: (asset) => api().settings.removeBrandAsset(asset),
    getUiPreferences: () => api().settings.getUiPreferences(),
    saveUiPreferences: (prefs) => api().settings.saveUiPreferences(prefs),
  },
  database: {
    getInfo: () => api().database.getInfo(),
    integrityCheck: () => api().database.integrityCheck(),
    vacuum: () => api().database.vacuum(),
    pickImportFile: () => api().database.pickImportFile(),
    importLegacy: (filePath) =>
      api().database.importLegacy(filePath),
  },
  backup: {
    list: () => api().backup.list(),
    create: () => api().backup.create(),
    restore: (filename) => api().backup.restore(filename),
    delete: (filename) => api().backup.delete(filename),
  },
  sync: {
    getConfig: () => api().sync.getConfig(),
    updateConfig: (input) => api().sync.updateConfig(input),
    getStatus: () => api().sync.getStatus(),
    listQueue: () => api().sync.listQueue(),
    retryFailed: () => api().sync.retryFailed(),
    listConflicts: () => api().sync.listConflicts(),
    resolveConflict: (conflictId, decision, note) => api().sync.resolveConflict(conflictId, decision, note),
    run: () => api().sync.run(),
  },
  export: {
    excel: (kind) => api().export.excel(kind),
    facturePdf: (factureId) => api().export.facturePdf(factureId),
    dashboardExcel: (filters) =>
      api().export.dashboardExcel(filters),
    dashboardPdf: (filters) => api().export.dashboardPdf(filters),
  },
  clients: {
    getDashboard: () => api().clients.getDashboard(),
    list: (filters) => api().clients.list(filters),
    get: (id) => api().clients.get(id),
    create: (input) => api().clients.create(input),
    update: (id, input) => api().clients.update(id, input),
    toggleActif: (id) => api().clients.toggleActif(id),
    delete: (id) => api().clients.delete(id),
    listContacts: (clientId) => api().clients.listContacts(clientId),
    createContact: (clientId, input) => api().clients.createContact(clientId, input),
    updateContact: (contactId, input) => api().clients.updateContact(contactId, input),
    deleteContact: (contactId) => api().clients.deleteContact(contactId),
    crmDashboard: (hotelId) => api().clients.crmDashboard(hotelId),
    crmClient360: (clientId) => api().clients.crmClient360(clientId),
    listCrmConsents: (clientId) => api().clients.listCrmConsents(clientId),
    recordCrmConsent: (input) => api().clients.recordCrmConsent(input),
    listCrmSegments: () => api().clients.listCrmSegments(),
    createCrmSegment: (input) => api().clients.createCrmSegment(input),
    recomputeCrmSegment: (id) => api().clients.recomputeCrmSegment(id),
    enrollLoyalty: (clientId) => api().clients.enrollLoyalty(clientId),
    moveLoyaltyPoints: (input) => api().clients.moveLoyaltyPoints(input),
    createCrmCampaign: (input) => api().clients.createCrmCampaign(input),
    prepareCrmCampaign: (id) => api().clients.prepareCrmCampaign(id),
    queueCrmMessage: (input) => api().clients.queueCrmMessage(input),
    nextCrmMessages: (limit) => api().clients.nextCrmMessages(limit),
    completeCrmMessage: (input) => api().clients.completeCrmMessage(input),
    createCrmSurvey: (input) => api().clients.createCrmSurvey(input),
    inviteCrmSurvey: (input) => api().clients.inviteCrmSurvey(input),
    submitCrmSurvey: (input) => api().clients.submitCrmSurvey(input),
    crmNpsDashboard: (hotelId) => api().clients.crmNpsDashboard(hotelId),
    ingestCrmReview: (input) => api().clients.ingestCrmReview(input),
    listCrmReviews: (hotelId) => api().clients.listCrmReviews(hotelId),
    respondCrmReview: (id, response) => api().clients.respondCrmReview(id, response),
    inviteCrmPortal: (clientId, email) => api().clients.inviteCrmPortal(clientId, email),
    activateCrmPortal: (input) => api().clients.activateCrmPortal(input),
    crmPortalOverview: (input) => api().clients.crmPortalOverview(input),
    invitePrecheckin: (reservationId) => api().clients.invitePrecheckin(reservationId),
    submitPrecheckin: (input) => api().clients.submitPrecheckin(input),
    validatePrecheckin: (id, approved) => api().clients.validatePrecheckin(id, approved),
  },
  tresorerie: {
    getDashboard: (hotelId) => api().tresorerie.getDashboard(hotelId),
    listEncaissements: (filters) => api().tresorerie.listEncaissements(filters),
    createEncaissement: (input) => api().tresorerie.createEncaissement(input),
    updateEncaissement: (id, input) => api().tresorerie.updateEncaissement(id, input),
    confirmerEncaissement: (id) => api().tresorerie.confirmerEncaissement(id),
    rejeterEncaissement: (id, motif) => api().tresorerie.rejeterEncaissement(id, motif),
    deleteEncaissement: (id) => api().tresorerie.deleteEncaissement(id),
    listComptes: (hotelId) => api().tresorerie.listComptes(hotelId),
    createCompte: (input) => api().tresorerie.createCompte(input),
    updateCompte: (id, input) => api().tresorerie.updateCompte(id, input),
    deleteCompte: (id) => api().tresorerie.deleteCompte(id),
    getJournalCaisse: (hotelId, dateDebut, dateFin) => api().tresorerie.getJournalCaisse(hotelId, dateDebut, dateFin),
    addOperationCaisse: (input) => api().tresorerie.addOperationCaisse(input),
    deleteOperationCaisse: (id) => api().tresorerie.deleteOperationCaisse(id),
    listPaymentOrders: (hotelId) => api().tresorerie.listPaymentOrders(hotelId),
    createPaymentOrder: (input) => api().tresorerie.createPaymentOrder(input),
    decidePaymentOrder: (id,approved) => api().tresorerie.decidePaymentOrder(id,approved),
    executePaymentOrder: (id) => api().tresorerie.executePaymentOrder(id),
    listForecast: (hotelId,from,to) => api().tresorerie.listForecast(hotelId,from,to),
    createForecast: (input) => api().tresorerie.createForecast(input),
    importBankStatement: (input) => api().tresorerie.importBankStatement(input),
    listBankLines: (accountId) => api().tresorerie.listBankLines(accountId),
    suggestReconciliation: (lineId) => api().tresorerie.suggestReconciliation(lineId),
    confirmReconciliation: (input) => api().tresorerie.confirmReconciliation(input),
    listCostCenters: (hotelId) => api().tresorerie.listCostCenters(hotelId),
    createCostCenter: (input) => api().tresorerie.createCostCenter(input),
    allocateCost: (input) => api().tresorerie.allocateCost(input),
    analyticalReport: (hotelId,from,to) => api().tresorerie.analyticalReport(hotelId,from,to),
  },
  facturation: {
    getDashboard: (hotelId) => api().facturation.getDashboard(hotelId),
    listFactures: (filters) => api().facturation.listFactures(filters),
    getFacture: (id) => api().facturation.getFacture(id),
    createFacture: (input) => api().facturation.createFacture(input),
    updateFacture: (id, input) => api().facturation.updateFacture(id, input),
    soumettre: (id) => api().facturation.soumettre(id),
    valider: (id) => api().facturation.valider(id),
    annuler: (id) => api().facturation.annuler(id),
    deleteFacture: (id) => api().facturation.deleteFacture(id),
    addPaiement: (input) => api().facturation.addPaiement(input),
    deletePaiement: (id) => api().facturation.deletePaiement(id),
    listClients: (search) => api().facturation.listClients(search),
    createClient: (input) => api().facturation.createClient(input),
    updateClient: (id, input) => api().facturation.updateClient(id, input),
    deleteClient: (id) => api().facturation.deleteClient(id),
    exportPdf: (factureId) => api().facturation.exportPdf(factureId),
    createAvoir: (input) => api().facturation.createAvoir(input),
    listRegistre: (filters) => api().facturation.listRegistre(filters),
    exportRegistreCsv: (filters) => api().facturation.exportRegistreCsv(filters),
  },
  comptabilite: {
    listComptes: (classe) => api().comptabilite.listComptes(classe),
    listJournaux: () => api().comptabilite.listJournaux(),
    listExercices: () => api().comptabilite.listExercices(),
    createExercice: (input) => api().comptabilite.createExercice(input),
    cloturerExercice: (exerciceId) => api().comptabilite.cloturerExercice(exerciceId),
    listEcritures: (filters) => api().comptabilite.listEcritures(filters),
    getEcriture: (id) => api().comptabilite.getEcriture(id),
    createEcriture: (input) => api().comptabilite.createEcriture(input),
    validerEcriture: (id) => api().comptabilite.validerEcriture(id),
    getGrandLivre: (compteNumero, dateDebut, dateFin) =>
      api().comptabilite.getGrandLivre(compteNumero, dateDebut, dateFin),
    getBalance: (exerciceId, dateDebut, dateFin) =>
      api().comptabilite.getBalance(exerciceId, dateDebut, dateFin),
    listLignesLettrables: (compteNumero) => api().comptabilite.listLignesLettrables(compteNumero),
    listLettrages: () => api().comptabilite.listLettrages(),
    creerLettrage: (ligneIds) => api().comptabilite.creerLettrage(ligneIds),
    annulerLettrage: (id) => api().comptabilite.annulerLettrage(id),
  },
  fiscalite: {
    listRegistreTva: (periode) => api().fiscalite.listRegistreTva(periode),
    genererRegistreTva: (periode) => api().fiscalite.genererRegistreTva(periode),
    exportRegistreTvaCsv: (periode) => api().fiscalite.exportRegistreTvaCsv(periode),
    calculerDeclarationTva: (periode) => api().fiscalite.calculerDeclarationTva(periode),
    getDeclarationTva: (periode) => api().fiscalite.getDeclarationTva(periode),
    listDeclarationsTva: () => api().fiscalite.listDeclarationsTva(),
    createRetenue: (input) => api().fiscalite.createRetenue(input),
    listRetenues: () => api().fiscalite.listRetenues(),
    genererLiasse: (exercice) => api().fiscalite.genererLiasse(exercice),
    listLiasse: (exercice) => api().fiscalite.listLiasse(exercice),
    exportLiasseCsv: (exercice) => api().fiscalite.exportLiasseCsv(exercice),
    listAchats: (periode) => api().fiscalite.listAchats(periode),
    createAchat: (input) => api().fiscalite.createAchat(input),
    importAchatsFromBons: (periode) => api().fiscalite.importAchatsFromBons(periode),
    exportAchatsCsv: (periode) => api().fiscalite.exportAchatsCsv(periode),
    genererLiasseAvancee: (exercice) => api().fiscalite.genererLiasseAvancee(exercice),
    exportTeledeclTvaG50: (periode) => api().fiscalite.exportTeledeclTvaG50(periode),
    listTeledeclarations: (typeDecl) => api().fiscalite.listTeledeclarations(typeDecl),
    marquerTeledeclDeclaree: (id, referenceDgi) => api().fiscalite.marquerTeledeclDeclaree(id, referenceDgi),
  },
  sifec: {
    dashboard: () => api().sifec.dashboard(),
    getConfig: () => api().sifec.getConfig(),
    updateConfig: (input) => api().sifec.updateConfig(input),
    testConnection: () => api().sifec.testConnection(),
    listFactures: (statut) => api().sifec.listFactures(statut),
    prepareFacture: (factureId) => api().sifec.prepareFacture(factureId),
    submitFacture: (factureId) => api().sifec.submitFacture(factureId),
    submitBatch: (factureIds) => api().sifec.submitBatch(factureIds),
    listTransmissions: (limit) => api().sifec.listTransmissions(limit),
  },
  modulesLegaux: {
    dashboard: () => api().modulesLegaux.dashboard(),
    immo: {
      list: (actifOnly) => api().modulesLegaux.immo.list(actifOnly),
      upsert: (input, id) => api().modulesLegaux.immo.upsert(input, id),
      genererPlan: (immobilisationId) => api().modulesLegaux.immo.genererPlan(immobilisationId),
      listAmortissements: (immobilisationId, periode) => api().modulesLegaux.immo.listAmortissements(immobilisationId, periode),
      comptabiliserMensuel: (periode) => api().modulesLegaux.immo.comptabiliserMensuel(periode),
      exportCsv: () => api().modulesLegaux.immo.exportCsv(),
    },
    casnos: {
      listAffilies: (actifOnly) => api().modulesLegaux.casnos.listAffilies(actifOnly),
      upsertAffilie: (input, id) => api().modulesLegaux.casnos.upsertAffilie(input, id),
      listDeclarations: (periode) => api().modulesLegaux.casnos.listDeclarations(periode),
      calculerDeclaration: (affilieId, periode, revenu) => api().modulesLegaux.casnos.calculerDeclaration(affilieId, periode, revenu),
      calculerPeriode: (periode) => api().modulesLegaux.casnos.calculerPeriode(periode),
      marquerDeclaree: (id, referenceCasnos) => api().modulesLegaux.casnos.marquerDeclaree(id, referenceCasnos),
      exportCsv: (periode) => api().modulesLegaux.casnos.exportCsv(periode),
    },
    inventaire: {
      listSessions: (exercice) => api().modulesLegaux.inventaire.listSessions(exercice),
      createSession: (input) => api().modulesLegaux.inventaire.createSession(input),
      listLignes: (sessionId) => api().modulesLegaux.inventaire.listLignes(sessionId),
      updateLigne: (ligneId, quantitePhysique, motifEcart) => api().modulesLegaux.inventaire.updateLigne(ligneId, quantitePhysique, motifEcart),
      cloturerSession: (sessionId) => api().modulesLegaux.inventaire.cloturerSession(sessionId),
      exportCsv: (sessionId) => api().modulesLegaux.inventaire.exportCsv(sessionId),
    },
  },
  hebergement: {
    listTypesChambre: (hotelId?) => api().hebergement.listTypesChambre(hotelId),
    createTypeChambre: (input) => api().hebergement.createTypeChambre(input),
    deleteTypeChambre: (id) => api().hebergement.deleteTypeChambre(id),
    listChambres: (hotelId?, statut?) => api().hebergement.listChambres(hotelId, statut),
    createChambre: (input) => api().hebergement.createChambre(input),
    updateChambre: (id, input) => api().hebergement.updateChambre(id, input),
    updateStatutChambre: (id, statut) => api().hebergement.updateStatutChambre(id, statut),
    deleteChambre: (id) => api().hebergement.deleteChambre(id),
    listReservations: (hotelId?, dateDebut?, dateFin?, statut?) =>
      api().hebergement.listReservations(hotelId, dateDebut, dateFin, statut),
    getReservation: (id) => api().hebergement.getReservation(id),
    createReservation: (input) => api().hebergement.createReservation(input),
    updateReservationStatut: (id, statut) => api().hebergement.updateReservationStatut(id, statut),
    deleteReservation: (id) => api().hebergement.deleteReservation(id),
    estimatePrice: (input) => api().hebergement.estimatePrice(input),
    createFactureFromReservation: (reservationId) =>
      api().hebergement.createFactureFromReservation(reservationId),
    getOccupationKpis: (dateDebut, dateFin, hotelId?) =>
      api().hebergement.getOccupationKpis(dateDebut, dateFin, hotelId),
    getFolio: (reservationId) => api().hebergement.getFolio(reservationId),
    createFolio: (reservationId) => api().hebergement.createFolio(reservationId),
    addFolioLine: (folioId, input) => api().hebergement.addFolioLine(folioId, input),
    closeFolioToFacture: (reservationId) => api().hebergement.closeFolioToFacture(reservationId),
    listGroupes: (hotelId) => api().hebergement.listGroupes(hotelId),
    createGroupe: (input) => api().hebergement.createGroupe(input),
    addReservationToGroupe: (groupeId, reservationId) => api().hebergement.addReservationToGroupe(groupeId, reservationId),
    listDepots: (reservationId) => api().hebergement.listDepots(reservationId),
    createDepot: (input) => api().hebergement.createDepot(input),
    listChannelConnectors: () => api().hebergement.listChannelConnectors(),
    saveChannelConnector: (input) => api().hebergement.saveChannelConnector(input),
    importChannelReservation: (input) => api().hebergement.importChannelReservation(input),
    configureChannelConnector:(input)=>api().hebergement.configureChannelConnector(input),
    saveChannelMapping:(input)=>api().hebergement.saveChannelMapping(input),
    getDistributionAvailability:(hotelId,from,to)=>api().hebergement.getDistributionAvailability(hotelId,from,to),
    saveChannelRestriction:(input)=>api().hebergement.saveChannelRestriction(input),
    queueChannelSync:(connectorId,from,to)=>api().hebergement.queueChannelSync(connectorId,from,to),
    nextChannelSyncJobs:(limit)=>api().hebergement.nextChannelSyncJobs(limit),
    completeChannelSyncJob:(id,result)=>api().hebergement.completeChannelSyncJob(id,result),
    listChannelSyncLogs:(connectorId)=>api().hebergement.listChannelSyncLogs(connectorId),
    ingestChannelWebhook:(input)=>api().hebergement.ingestChannelWebhook(input),
    saveBookingEngineConfig:(input)=>api().hebergement.saveBookingEngineConfig(input),
    saveBookingPromo:(input)=>api().hebergement.saveBookingPromo(input),
    quoteDirectBooking:(input)=>api().hebergement.quoteDirectBooking(input),
    createDirectBooking:(input)=>api().hebergement.createDirectBooking(input),
    confirmDirectBookingPayment:(input)=>api().hebergement.confirmDirectBookingPayment(input),
    getDistributionDashboard:(hotelId)=>api().hebergement.getDistributionDashboard(hotelId),
    updateReservation: (reservationId, input) => api().hebergement.updateReservation(reservationId, input),
    moveReservationRoom: (reservationId, input) => api().hebergement.moveReservationRoom(reservationId, input),
    listRoomMoves: (reservationId) => api().hebergement.listRoomMoves(reservationId),
    listOccupants: (reservationId) => api().hebergement.listOccupants(reservationId),
    saveOccupant: (reservationId, input, occupantId) => api().hebergement.saveOccupant(reservationId, input, occupantId),
    deleteOccupant: (occupantId) => api().hebergement.deleteOccupant(occupantId),
    listWaitlist: (hotelId) => api().hebergement.listWaitlist(hotelId),
    createWaitlist: (input) => api().hebergement.createWaitlist(input),
    updateWaitlistStatus: (id, statut) => api().hebergement.updateWaitlistStatus(id, statut),
    promoteWaitlist: (id, input) => api().hebergement.promoteWaitlist(id, input),
    listCancellationPolicies: (hotelId) => api().hebergement.listCancellationPolicies(hotelId),
    createCancellationPolicy: (input) => api().hebergement.createCancellationPolicy(input),
    cancelReservation: (reservationId, input) => api().hebergement.cancelReservation(reservationId, input),
    markReservationNoShow: (reservationId, input) => api().hebergement.markReservationNoShow(reservationId, input),
    operateDeposit: (depotId, input) => api().hebergement.operateDeposit(depotId, input),
    transferFolioLines: (input) => api().hebergement.transferFolioLines(input),
    shareFolio: (input) => api().hebergement.shareFolio(input),
    getMiceDashboard: (hotelId) => api().hebergement.getMiceDashboard(hotelId),
    getMiceGroupDetail: (id) => api().hebergement.getMiceGroupDetail(id),
    saveMiceAllotment: (input) => api().hebergement.saveMiceAllotment(input),
    releaseMiceAllotments: (groupeId,date) => api().hebergement.releaseMiceAllotments(groupeId,date),
    importRoomingList: (groupeId,rows) => api().hebergement.importRoomingList(groupeId,rows),
    reserveRoomingLine: (id) => api().hebergement.reserveRoomingLine(id),
    listMiceSpaces: (hotelId) => api().hebergement.listMiceSpaces(hotelId),
    saveMiceSpace: (input) => api().hebergement.saveMiceSpace(input),
    listMiceEvents: (hotelId) => api().hebergement.listMiceEvents(hotelId),
    createMiceEvent: (input) => api().hebergement.createMiceEvent(input),
    bookMiceSpace: (input) => api().hebergement.bookMiceSpace(input),
    createMiceQuote: (input) => api().hebergement.createMiceQuote(input),
    addMiceQuoteLine: (input) => api().hebergement.addMiceQuoteLine(input),
    setMiceQuoteStatus: (id,status) => api().hebergement.setMiceQuoteStatus(id,status),
    listMiceDocuments: (eventId) => api().hebergement.listMiceDocuments(eventId),
    saveMiceBeo: (input) => api().hebergement.saveMiceBeo(input),
    addMiceCharge: (input) => api().hebergement.addMiceCharge(input),
    invoiceMiceEvent: (eventId) => api().hebergement.invoiceMiceEvent(eventId),
  },
  tarifs: {
    listComposants:   (hotelId?)             => api().tarifs.listComposants(hotelId),
    createComposant:  (input)                => api().tarifs.createComposant(input),
    deleteComposant:  (id)                   => api().tarifs.deleteComposant(id),
    listFormules:     (hotelId?)             => api().tarifs.listFormules(hotelId),
    createFormule:    (input)                => api().tarifs.createFormule(input),
    deleteFormule:    (id)                   => api().tarifs.deleteFormule(id),
    listPlans:        (hotelId?)             => api().tarifs.listPlans(hotelId),
    createPlan:       (input)                => api().tarifs.createPlan(input),
    deletePlan:       (id)                   => api().tarifs.deletePlan(id),
    getGrille:        (hotelId, planId, deb, fin, formuleId?) =>
                        api().tarifs.getGrille(hotelId, planId, deb, fin, formuleId),
    upsertTarif:      (input)                => api().tarifs.upsertTarif(input),
    upsertBulk:       (input)                => api().tarifs.upsertBulk(input),
    listPromotions:   (hotelId?)             => api().tarifs.listPromotions(hotelId),
    createPromotion:  (input)                => api().tarifs.createPromotion(input),
    togglePromotion:  (id, actif)            => api().tarifs.togglePromotion(id, actif),
    deletePromotion:  (id)                   => api().tarifs.deletePromotion(id),
    listConventions:  (hotelId?, clientId?)  => api().tarifs.listConventions(hotelId, clientId),
    createConvention: (input)                => api().tarifs.createConvention(input),
    toggleConvention: (id, actif)            => api().tarifs.toggleConvention(id, actif),
    deleteConvention: (id)                   => api().tarifs.deleteConvention(id),
    simuler:          (input)                => api().tarifs.simuler(input),
  },
  yield: {
    listRules:          (hotelId?)  => api().yield.listRules(hotelId),
    createRule:         (input)     => api().yield.createRule(input),
    updateRule:         (id, input) => api().yield.updateRule(id, input),
    toggleRule:         (id, actif) => api().yield.toggleRule(id, actif),
    deleteRule:         (id)        => api().yield.deleteRule(id),
    computeSuggestions: (input)     => api().yield.computeSuggestions(input),
    applySuggestions:   (input)     => api().yield.applySuggestions(input),
  },
  rh: {
    getDashboard: (dateDebut?, dateFin?, hotelId?) => api().rh.getDashboard(dateDebut, dateFin, hotelId),
    pendingAccountsCount: () => api().rh.pendingAccountsCount(),
    getMonEspace: () => api().rh.getMonEspace(),
    listDirections: () => api().rh.listDirections(),
    createDirection: (input) => api().rh.createDirection(input),
    updateDirection: (id, input) => api().rh.updateDirection(id, input),
    listDepartements: (directionId) => api().rh.listDepartements(directionId),
    createDepartement: (input) => api().rh.createDepartement(input),
    updateDepartement: (id, input) => api().rh.updateDepartement(id, input),
    listPostes: (departementId) => api().rh.listPostes(departementId),
    createPoste: (input) => api().rh.createPoste(input),
    updatePoste: (id, input) => api().rh.updatePoste(id, input),
    listEmployes: (search?) => api().rh.listEmployes(search),
    getEmploye: (id) => api().rh.getEmploye(id),
    createEmploye: (input) => api().rh.createEmploye(input),
    createEmployeWizard: (input) => api().rh.createEmployeWizard(input),
    updateEmploye: (id, input) => api().rh.updateEmploye(id, input),
    sortirEmploye: (id, input) => api().rh.sortirEmploye(id, input),
    listRecrutements: (statut?) => api().rh.listRecrutements(statut),
    createRecrutement: (input) => api().rh.createRecrutement(input),
    validerRecrutement: (id) => api().rh.validerRecrutement(id),
    refuserRecrutement: (id, motif?) => api().rh.refuserRecrutement(id, motif),
    listOffresEmploi: (statut?) => api().rh.listOffresEmploi(statut),
    createOffreEmploi: (input) => api().rh.createOffreEmploi(input),
    updateOffreEmploi: (id, input) => api().rh.updateOffreEmploi(id, input),
    getPipelineRecrutement: (offreId?) => api().rh.getPipelineRecrutement(offreId),
    createCandidature: (input) => api().rh.createCandidature(input),
    avancerCandidature: (input) => api().rh.avancerCandidature(input),
    listEntretiensRecrutement: (recrutementId) => api().rh.listEntretiensRecrutement(recrutementId),
    createEntretienRecrutement: (input) => api().rh.createEntretienRecrutement(input),
    updateEntretienRecrutement: (id, input) => api().rh.updateEntretienRecrutement(id, input),
    listHistoriqueCandidature: (recrutementId) => api().rh.listHistoriqueCandidature(recrutementId),
    runReconciliationTemps: (dateDebut, dateFin, hotelId) => api().rh.runReconciliationTemps(dateDebut, dateFin, hotelId),
    listReconciliationsTemps: (opts) => api().rh.listReconciliationsTemps(opts),
    listTempsAlertes: (statut) => api().rh.listTempsAlertes(statut),
    traiterTempsAlerte: (alerteId, action) => api().rh.traiterTempsAlerte(alerteId, action),
    getReconciliationPaie: (periode) => api().rh.getReconciliationPaie(periode),
    validerReconciliationPaie: (employeId, dateDebut, dateFin) => api().rh.validerReconciliationPaie(employeId, dateDebut, dateFin),
    exportReconciliationCsv: (dateDebut, dateFin) => api().rh.exportReconciliationCsv(dateDebut, dateFin),
    listEmployeCompetences: (employeId) => api().rh.listEmployeCompetences(employeId),
    setEmployeCompetence: (input) => api().rh.setEmployeCompetence(input),
    getMatriceGpec: (employeId) => api().rh.getMatriceGpec(employeId),
    listCampagnesEvaluation: () => api().rh.listCampagnesEvaluation(),
    createCampagneEvaluation: (input) => api().rh.createCampagneEvaluation(input),
    updateCampagneEvaluation: (id, input) => api().rh.updateCampagneEvaluation(id, input),
    lancerCampagneEvaluation: (campagneId) => api().rh.lancerCampagneEvaluation(campagneId),
    cloturerCampagneEvaluation: (campagneId) => api().rh.cloturerCampagneEvaluation(campagneId),
    getCampagneSynthese: (campagneId) => api().rh.getCampagneSynthese(campagneId),
    listCampagneEvaluations: (campagneId, employeId) => api().rh.listCampagneEvaluations(campagneId, employeId),
    soumettreEvaluationLigne: (ligneId, input) => api().rh.soumettreEvaluationLigne(ligneId, input),
    validerEvaluationLigne: (ligneId) => api().rh.validerEvaluationLigne(ligneId),
    listContrats: (employeId) => api().rh.listContrats(employeId),
    createContrat: (input) => api().rh.createContrat(input),
    listAllContrats: () => api().rh.listAllContrats(),
    listPointages: (dateDebut?, dateFin?, employeId?) =>
      api().rh.listPointages(dateDebut, dateFin, employeId),
    upsertPointage: (input) => api().rh.upsertPointage(input),
    soumettrePointage: (id) => api().rh.soumettrePointage(id),
    validerPointage: (id, approuve) => api().rh.validerPointage(id, approuve),
    listAbsences: (statut?, opts?) => api().rh.listAbsences(statut, opts),
    createAbsence: (input) => api().rh.createAbsence(input),
    deciderAbsence: (id, approuve) => api().rh.deciderAbsence(id, approuve),
    cancelAbsence: (id, motif) => api().rh.cancelAbsence(id, motif),
    listAffectations: (opts?) => api().rh.listAffectations(opts),
    createAffectation: (input) => api().rh.createAffectation(input),
    terminerAffectation: (id, dateFin?) => api().rh.terminerAffectation(id, dateFin),
    listOrganisation: (hotelId?) => api().rh.listOrganisation(hotelId),
    upsertOrganisation: (input) => api().rh.upsertOrganisation(input),
    deleteOrganisation: (id) => api().rh.deleteOrganisation(id),
    listSoldesConges: (opts?) => api().rh.listSoldesConges(opts),
    upsertSoldeConges: (input) => api().rh.upsertSoldeConges(input),
    listPlannings: (opts?) => api().rh.listPlannings(opts),
    createPlanning: (input) => api().rh.createPlanning(input),
    deletePlanning: (id) => api().rh.deletePlanning(id),
    getPlanningSynthese: (dateDebut, dateFin, hotelId?) =>
      api().rh.getPlanningSynthese(dateDebut, dateFin, hotelId),
    getSuggestionsRenfort: (seuil?) => api().rh.getSuggestionsRenfort(seuil),
    listEquipes: (chefEmployeId?) => api().rh.listEquipes(chefEmployeId),
    addEquipeMembre: (input) => api().rh.addEquipeMembre(input),
    removeEquipeMembre: (id) => api().rh.removeEquipeMembre(id),
    listBulletins: (periode?) => api().rh.listBulletins(periode),
    generatePrePaie: (periode) => api().rh.generatePrePaie(periode),
    validerBulletin: (id) => api().rh.validerBulletin(id),
    getPaieCloture: (periode) => api().rh.getPaieCloture(periode),
    listPaieClotures: () => api().rh.listPaieClotures(),
    validerPaieMensuelle: (periode) => api().rh.validerPaieMensuelle(periode),
    cloturerPaieMensuelle: (periode) => api().rh.cloturerPaieMensuelle(periode),
    getPaieParams: () => api().rh.getPaieParams(),
    comptabiliserBulletin: (id, hotelId, dateOperation) =>
      api().rh.comptabiliserBulletin(id, hotelId, dateOperation),
    listPrimes: (periode?, employeId?) => api().rh.listPrimes(periode, employeId),
    createPrime: (input) => api().rh.createPrime(input),
    deletePrime: (id) => api().rh.deletePrime(id),
    getDlgConfig: () => api().rh.getDlgConfig(),
    setDlgConfig: (input) => api().rh.setDlgConfig(input),
    pickDlgFolder: (kind) => api().rh.pickDlgFolder(kind),
    pickDlgImportFile: () => api().rh.pickDlgImportFile(),
    exportVersDlg: (periode) => api().rh.exportVersDlg(periode),
    importDepuisDlg: (periode, sourceFile) => api().rh.importDepuisDlg(periode, sourceFile),
    listDlgJournal: (limit?) => api().rh.listDlgJournal(limit),
    listFormationsCatalog: (actifOnly?) => api().rh.listFormationsCatalog(actifOnly),
    createFormationCatalog: (input) => api().rh.createFormationCatalog(input),
    updateFormationCatalog: (id, input) => api().rh.updateFormationCatalog(id, input),
    listEmployeFormations: (opts?) => api().rh.listEmployeFormations(opts),
    assignEmployeFormation: (input) => api().rh.assignEmployeFormation(input),
    updateEmployeFormation: (id, input) => api().rh.updateEmployeFormation(id, input),
    deleteEmployeFormation: (id) => api().rh.deleteEmployeFormation(id),
    listCompetences: () => api().rh.listCompetences(),
    createCompetence: (input) => api().rh.createCompetence(input),
    listPosteCompetences: (posteId?) => api().rh.listPosteCompetences(posteId),
    setPosteCompetence: (input) => api().rh.setPosteCompetence(input),
    removePosteCompetence: (id) => api().rh.removePosteCompetence(id),
    listEntretiens: (opts?) => api().rh.listEntretiens(opts),
    createEntretien: (input) => api().rh.createEntretien(input),
    updateEntretien: (id, input) => api().rh.updateEntretien(id, input),
    deleteEntretien: (id) => api().rh.deleteEntretien(id),
    listRhDocuments: (employeId?) => api().rh.listRhDocuments(employeId),
    uploadRhDocument: (employeId, type, nom?) => api().rh.uploadRhDocument(employeId, type, nom),
    deleteRhDocument: (id) => api().rh.deleteRhDocument(id),
    openRhDocument: (id) => api().rh.openRhDocument(id),
    getComparatifUnites: (dateDebut?, dateFin?) => api().rh.getComparatifUnites(dateDebut, dateFin),
    getPrevisionsEffectif: (opts?) => api().rh.getPrevisionsEffectif(opts),
    listOnboardingSuivi: (opts?) => api().rh.listOnboardingSuivi(opts),
    completeOnboardingStep: (employeId, stepCode) => api().rh.completeOnboardingStep(employeId, stepCode),
    getPortRhSynthese: () => api().rh.getPortRhSynthese(),
    updateEmployeTypeActivite: (input) => api().rh.updateEmployeTypeActivite(input),
    getRhAiConfig: () => api().rh.getRhAiConfig(),
    buildRhDecisionContext: (hotelId?) => api().rh.buildRhDecisionContext(hotelId),
    generateRhAiAnalysis: (opts?) => api().rh.generateRhAiAnalysis(opts),
    getConformiteDashboard: () => api().rh.getConformiteDashboard(),
    syncCongesLegaux: (annee?) => api().rh.syncCongesLegaux(annee),
    updateConformiteSuivi: (employeId, code, statut, opts?) =>
      api().rh.updateConformiteSuivi(employeId, code, statut, opts),
    listDossierModeles: () => api().rh.listDossierModeles(),
    getDossierEmploye: (employeId) => api().rh.getDossierEmploye(employeId),
    scanDossierFolder: (employeId, modeleCode?) => api().rh.scanDossierFolder(employeId, modeleCode),
    scanSingleDocument: (employeId, modeleCode) => api().rh.scanSingleDocument(employeId, modeleCode),
    soumettreDocumentValidation: (documentId) => api().rh.soumettreDocumentValidation(documentId),
    listValidationsN1: () => api().rh.listValidationsN1(),
    countValidationsN1: () => api().rh.countValidationsN1(),
    validerN1Absence: (id, approuve, commentaire?) => api().rh.validerN1Absence(id, approuve, commentaire),
    validerN1Pointage: (id, approuve) => api().rh.validerN1Pointage(id, approuve),
    validerN1Document: (id, approuve) => api().rh.validerN1Document(id, approuve),
    listRegistrePersonnel: () => api().rh.listRegistrePersonnel(),
    listRegistreConges: (annee) => api().rh.listRegistreConges(annee),
    listAccidentsTravail: () => api().rh.listAccidentsTravail(),
    listVisitesMedicales: () => api().rh.listVisitesMedicales(),
    createAccidentTravail: (input) => api().rh.createAccidentTravail(input),
    createVisiteMedicale: (input) => api().rh.createVisiteMedicale(input),
    exportRegistrePersonnelPdf: () => api().rh.exportRegistrePersonnelPdf(),
    exportRegistrePersonnelCsv: () => api().rh.exportRegistrePersonnelCsv(),
    exportRegistreCongesPdf: (annee) => api().rh.exportRegistreCongesPdf(annee),
    exportRegistreAccidentsPdf: () => api().rh.exportRegistreAccidentsPdf(),
    exportRegistreVisitesPdf: () => api().rh.exportRegistreVisitesPdf(),
    exportBulletinPaiePdf: (bulletinId) => api().rh.exportBulletinPaiePdf(bulletinId),
    previewStc: (input) => api().rh.previewStc(input),
    processRuptureContrat: (input) => api().rh.processRuptureContrat(input),
    listRupturesContrat: () => api().rh.listRupturesContrat(),
    exportCertificatTravailPdf: (ruptureId) => api().rh.exportCertificatTravailPdf(ruptureId),
    exportStcPdf: (ruptureId) => api().rh.exportStcPdf(ruptureId),
    exportDasAnnuelle: (annee) => api().rh.exportDasAnnuelle(annee),
    exportCnasMensuelle: (periode) => api().rh.exportCnasMensuelle(periode),
    exportVirementsPaie: (periode) => api().rh.exportVirementsPaie(periode),
    exportAnemEmbauches: () => api().rh.exportAnemEmbauches(),
    exportDadsUAnnuelle: (annee) => api().rh.exportDadsUAnnuelle(annee),
    getOrganigrammeEgt: (hotelId) => api().rh.getOrganigrammeEgt(hotelId),
    getEffectifsEgt: (hotelId) => api().rh.getEffectifsEgt(hotelId),
    listFichesPoste: (posteId) => api().rh.listFichesPoste(posteId),
    upsertFichePoste: (input) => api().rh.upsertFichePoste(input),
    exportOrganigrammeCsv: (hotelId) => api().rh.exportOrganigrammeCsv(hotelId),
    listPointeuses: (hotelId) => api().rh.listPointeuses(hotelId),
    upsertPointeuse: (input, id) => api().rh.upsertPointeuse(input, id),
    importPointeuseCsv: (hotelId, csvContent, pointeuseId) =>
      api().rh.importPointeuseCsv(hotelId, csvContent, pointeuseId),
    listRawPunches: (hotelId, traite) => api().rh.listRawPunches(hotelId, traite),
    traiterRawPunches: (hotelId, dateDebut, dateFin) =>
      api().rh.traiterRawPunches(hotelId, dateDebut, dateFin),
    setEmployeBadge: (employeId, badgeId) => api().rh.setEmployeBadge(employeId, badgeId),
    syncPointeuseNow: (pointeuseId) => api().rh.syncPointeuseNow(pointeuseId),
    setPointeuseSyncAuto: (pointeuseId, syncAuto, intervalMin) =>
      api().rh.setPointeuseSyncAuto(pointeuseId, syncAuto, intervalMin),
    listPointeusesExtended: (hotelId) => api().rh.listPointeusesExtended(hotelId),
  },
  modules: {
    listEnabled: () => api().modules.listEnabled(),
    listConfig: () => api().modules.listConfig(),
    setEnabled: (moduleId, enabled) => api().modules.setEnabled(moduleId, enabled),
  },
  anomalies: {
    list: (hotelId?, statut?) => api().anomalies.list(hotelId, statut),
    stats: (hotelId) => api().anomalies.stats(hotelId),
    create: (input) => api().anomalies.create(input),
    update: (id, input) => api().anomalies.update(id, input),
    delete: (id) => api().anomalies.delete(id),
  },
  decisions: {
    list: (filters?) => api().decisions.list(filters),
    listForUser: (filters?) => api().decisions.listForUser(filters),
    destinataires: (id) => api().decisions.destinataires(id),
    get: (id) => api().decisions.get(id),
    create: (input) => api().decisions.create(input),
    update: (id, input) => api().decisions.update(id, input),
    marquerLu: (id) => api().decisions.marquerLu(id),
    archiver: (id) => api().decisions.archiver(id),
  },
  reclamations: {
    list: (hotelId?, statut?) => api().reclamations.list(hotelId, statut),
    stats: (hotelId) => api().reclamations.stats(hotelId),
    create: (input) => api().reclamations.create(input),
    update: (id, input) => api().reclamations.update(id, input),
  },
  stocks: {
    listProduits: () => api().stocks.listProduits(),
    createProduit: (input) => api().stocks.createProduit(input),
    getNiveaux: (hotelId) => api().stocks.getNiveaux(hotelId),
    createMouvement: (input) => api().stocks.createMouvement(input),
    listCategories: () => api().stocks.listCategories(),
    listMagasins:(hotelId)=>api().stocks.listMagasins(hotelId),
    createMagasin:(input)=>api().stocks.createMagasin(input),
    listNiveauxMagasins:(hotelId)=>api().stocks.listNiveauxMagasins(hotelId),
    listLots:(hotelId,produitId)=>api().stocks.listLots(hotelId,produitId),
    receiveLot:(input)=>api().stocks.receiveLot(input),
    consumeFefo:(input)=>api().stocks.consumeFefo(input),
    listTransferts:(hotelId)=>api().stocks.listTransferts(hotelId),
    createTransfert:(input)=>api().stocks.createTransfert(input),
    validateTransfert:(id)=>api().stocks.validateTransfert(id),
    listInventaires:(hotelId)=>api().stocks.listInventaires(hotelId),
    createInventaire:(input)=>api().stocks.createInventaire(input),
    getInventoryLines:(id)=>api().stocks.getInventoryLines(id),
    countInventoryLine:(inventaireId,produitId,quantite)=>api().stocks.countInventoryLine(inventaireId,produitId,quantite),
    validateInventory:(id)=>api().stocks.validateInventory(id),
    findByBarcode:(hotelId,barcode)=>api().stocks.findByBarcode(hotelId,barcode),
  },
  cuisine: {
    listRecettes: (hotelId) => api().cuisine.listRecettes(hotelId),
    getRecette: (id) => api().cuisine.getRecette(id),
    createRecette: (input) => api().cuisine.createRecette(input),
    updateRecette: (id, input) => api().cuisine.updateRecette(id, input),
    upsertRecetteLigne: (recetteId, input, ligneId) => api().cuisine.upsertRecetteLigne(recetteId, input, ligneId),
    removeRecetteLigne: (recetteId, ligneId) => api().cuisine.removeRecetteLigne(recetteId, ligneId),
    validerRecette: (id) => api().cuisine.validerRecette(id),
    listOrdres: (hotelId) => api().cuisine.listOrdres(hotelId),
    createOrdre: (input) => api().cuisine.createOrdre(input),
    executerOrdre: (id) => api().cuisine.executerOrdre(id),
    listVentesPos: (hotelId) => api().cuisine.listVentesPos(hotelId),
    enregistrerVentePos: (input) => api().cuisine.enregistrerVentePos(input),
    qualityDashboard:(hotelId,from,to)=>api().cuisine.qualityDashboard(hotelId,from,to),
    listHaccpPlans:(hotelId)=>api().cuisine.listHaccpPlans(hotelId),
    createHaccpPlan:(input)=>api().cuisine.createHaccpPlan(input),
    haccpControls:(planId,from,to)=>api().cuisine.haccpControls(planId,from,to),
    recordHaccpControl:(input)=>api().cuisine.recordHaccpControl(input),
    closeHaccpAction:(id,verification)=>api().cuisine.closeHaccpAction(id,verification),
    listTemperatureEquipment:(hotelId)=>api().cuisine.listTemperatureEquipment(hotelId),
    saveTemperatureEquipment:(input)=>api().cuisine.saveTemperatureEquipment(input),
    recordTemperature:(input)=>api().cuisine.recordTemperature(input),
    listAllergens:()=>api().cuisine.listAllergens(),
    setProductAllergens:(productId,items)=>api().cuisine.setProductAllergens(productId,items),
    syncRecipeAllergens:(recipeId)=>api().cuisine.syncRecipeAllergens(recipeId),
    recipeAllergens:(recipeId)=>api().cuisine.recipeAllergens(recipeId),
    recordWaste:(input)=>api().cuisine.recordWaste(input),
    closeProductionCost:(orderId)=>api().cuisine.closeProductionCost(orderId),
    traceability:(hotelId,search)=>api().cuisine.traceability(hotelId,search),
    menuEngineering:(hotelId,from,to)=>api().cuisine.menuEngineering(hotelId,from,to),
  },
  hardware: {
    dashboard:(hotelId)=>api().hardware.dashboard(hotelId),
    listDevices:(hotelId)=>api().hardware.listDevices(hotelId),
    saveDevice:(input)=>api().hardware.saveDevice(input),
    queueCommand:(input)=>api().hardware.queueCommand(input),
    nextCommands:(hotelId,limit)=>api().hardware.nextCommands(hotelId,limit),
    dispatchCommand:(id)=>api().hardware.dispatchCommand(id),
    commandLogs:(hotelId,deviceId)=>api().hardware.commandLogs(hotelId,deviceId),
    startPayment:(input)=>api().hardware.startPayment(input),
    reversePayment:(id,operation,amount)=>api().hardware.reversePayment(id,operation,amount),
    listPayments:(hotelId)=>api().hardware.listPayments(hotelId),
    issueRoomKey:(input)=>api().hardware.issueRoomKey(input),
    revokeRoomKey:(id)=>api().hardware.revokeRoomKey(id),
    listRoomKeys:(hotelId)=>api().hardware.listRoomKeys(hotelId),
    ingestPbxCall:(input)=>api().hardware.ingestPbxCall(input),
    listPbxCalls:(hotelId)=>api().hardware.listPbxCalls(hotelId),
    setIptvAccess:(input)=>api().hardware.setIptvAccess(input),
    captureScan:(input)=>api().hardware.captureScan(input),
    queueFiscalPrint:(input)=>api().hardware.queueFiscalPrint(input),
  },
  pos: {
    listKds: (pointVenteId) => api().pos.listKds(pointVenteId),
    updateKds: (id, statut) => api().pos.updateKds(id, statut),
    listDevices: (pointVenteId) => api().pos.listDevices(pointVenteId),
    saveDevice: (input) => api().pos.saveDevice(input),
    listPointsVente: (hotelId) => api().pos.listPointsVente(hotelId),
    createPointVente: (input) => api().pos.createPointVente(input),
    listFactions: (pointVenteId) => api().pos.listFactions(pointVenteId),
    createFaction: (input) => api().pos.createFaction(input),
    listSessions: (pointVenteId, dateService) => api().pos.listSessions(pointVenteId, dateService),
    openSession: (input) => api().pos.openSession(input),
    getRapportSession: (sessionId) => api().pos.getRapportSession(sessionId),
    cloturerSession: (input) => api().pos.cloturerSession(input),
    listTickets: (sessionId) => api().pos.listTickets(sessionId),
    createTicket: (input) => api().pos.createTicket(input),
    addTicketLigne: (input) => api().pos.addTicketLigne(input),
    removeTicketLigne: (ligneId) => api().pos.removeTicketLigne(ligneId),
    validerTicket: (input) => api().pos.validerTicket(input),
    annulerTicket: (ticketId) => api().pos.annulerTicket(ticketId),
    listCloturesJournalieres: (pointVenteId) => api().pos.listCloturesJournalieres(pointVenteId),
    cloturerJournee: (input) => api().pos.cloturerJournee(input),
    getHotelClosureStatus: (hotelId, dateJournal) => api().pos.getHotelClosureStatus(hotelId, dateJournal),
    listSalles: (pointVenteId) => api().pos.listSalles(pointVenteId),
    createSalle: (input) => api().pos.createSalle(input),
    listTables: (salleId) => api().pos.listTables(salleId),
    saveTable: (input,tableId) => api().pos.saveTable(input,tableId),
    updateTableStatus: (tableId,statut) => api().pos.updateTableStatus(tableId,statut),
    assignTicketTable: (ticketId,input) => api().pos.assignTicketTable(ticketId,input),
    updateServiceStage: (ticketId,etape) => api().pos.updateServiceStage(ticketId,etape),
    splitTicket: (ticketId,lineIds) => api().pos.splitTicket(ticketId,lineIds),
    applyDiscount: (ticketId,input) => api().pos.applyDiscount(ticketId,input),
    refundTicket: (ticketId,input) => api().pos.refundTicket(ticketId,input),
  },
  achats: {
    listFournisseurs: () => api().achats.listFournisseurs(),
    createFournisseur: (input) => api().achats.createFournisseur(input),
    listBons: (hotelId?, statut?) => api().achats.listBons(hotelId, statut),
    getBonLignes: (bonId) => api().achats.getBonLignes(bonId),
    createBon: (input) => api().achats.createBon(input),
    validerBon: (id) => api().achats.validerBon(id),
    envoyerBon: (id) => api().achats.envoyerBon(id),
    livrerBon: (id, input) => api().achats.livrerBon(id, input),
    listDemandes: (hotelId) => api().achats.listDemandes(hotelId),
    createDemande: (input) => api().achats.createDemande(input),
    submitDemande: (id) => api().achats.submitDemande(id),
    decideDemande: (id,approved) => api().achats.decideDemande(id,approved),
    listConsultations: (hotelId) => api().achats.listConsultations(hotelId),
    createConsultation: (input) => api().achats.createConsultation(input),
    listOffres: (consultationId) => api().achats.listOffres(consultationId),
    createOffre: (input) => api().achats.createOffre(input),
    awardOffre: (id) => api().achats.awardOffre(id),
    listFactures: (hotelId) => api().achats.listFactures(hotelId),
    createFacture: (input) => api().achats.createFacture(input),
    validateFacture: (id,force) => api().achats.validateFacture(id,force),
    payFacture: (id,input) => api().achats.payFacture(id,input),
  },
  appelsOffres: {
    list: (hotelId?) => api().appelsOffres.list(hotelId),
    create: (input) => api().appelsOffres.create(input),
    publier: (id, dateLimiteDepot) => api().appelsOffres.publier(id, dateLimiteDepot),
    annuler: (id, motif) => api().appelsOffres.annuler(id, motif),
    listLots: (appelOffresId) => api().appelsOffres.listLots(appelOffresId),
    createLot: (input) => api().appelsOffres.createLot(input),
    deleteLot: (id) => api().appelsOffres.deleteLot(id),
    listDocuments: (appelOffresId) => api().appelsOffres.listDocuments(appelOffresId),
    uploadDocument: (input) => api().appelsOffres.uploadDocument(input),
    ouvrirDocument: (id) => api().appelsOffres.ouvrirDocument(id),
    deleteDocument: (id) => api().appelsOffres.deleteDocument(id),
    listFournisseurs: (appelOffresId) => api().appelsOffres.listFournisseurs(appelOffresId),
    inviteFournisseurs: (appelOffresId, fournisseurIds) => api().appelsOffres.inviteFournisseurs(appelOffresId, fournisseurIds),
    removeFournisseurInvite: (id) => api().appelsOffres.removeFournisseurInvite(id),
    listCriteres: (appelOffresId) => api().appelsOffres.listCriteres(appelOffresId),
    createCritere: (input) => api().appelsOffres.createCritere(input),
    deleteCritere: (id) => api().appelsOffres.deleteCritere(id),
    saveNote: (input) => api().appelsOffres.saveNote(input),
    listNotes: (lotId) => api().appelsOffres.listNotes(lotId),
    listOffres: (appelOffresId, lotId?) => api().appelsOffres.listOffres(appelOffresId, lotId),
    createOffre: (input) => api().appelsOffres.createOffre(input),
    listCommission: (appelOffresId) => api().appelsOffres.listCommission(appelOffresId),
    listPv: (appelOffresId) => api().appelsOffres.listPv(appelOffresId),
    ouvrirPlis: (input) => api().appelsOffres.ouvrirPlis(input),
    attribuerLot: (input) => api().appelsOffres.attribuerLot(input),
    marquerLotInfructueux: (lotId) => api().appelsOffres.marquerLotInfructueux(lotId),
  },
  veille: {
    list: (filters?) => api().veille.list(filters),
    create: (input) => api().veille.create(input),
    update: (id, input) => api().veille.update(id, input),
    remove: (id) => api().veille.remove(id),
    attachDocument: (id) => api().veille.attachDocument(id),
    ouvrirDocument: (id) => api().veille.ouvrirDocument(id),
  },
  maintenance: {
    listEquipements: (hotelId) => api().maintenance.listEquipements(hotelId),
    createEquipement: (input) => api().maintenance.createEquipement(input),
    listInterventions: (hotelId, statut?) => api().maintenance.listInterventions(hotelId, statut),
    createIntervention: (input) => api().maintenance.createIntervention(input),
    updateIntervention: (id, input) => api().maintenance.updateIntervention(id, input),
    stats: (hotelId) => api().maintenance.stats(hotelId),
    listPlans:(hotelId)=>api().maintenance.listPlans(hotelId),
    createPlan:(input)=>api().maintenance.createPlan(input),
    generateWorkOrders:(through)=>api().maintenance.generateWorkOrders(through),
    refreshSla:(hotelId)=>api().maintenance.refreshSla(hotelId),
    consumePart:(input)=>api().maintenance.consumePart(input),
    logLabor:(input)=>api().maintenance.logLabor(input),
    listContracts:(hotelId)=>api().maintenance.listContracts(hotelId),
    createContract:(input)=>api().maintenance.createContract(input),
    costReport:(hotelId,from,to)=>api().maintenance.costReport(hotelId,from,to),
  },
  housekeeping: {
    listTaches: (hotelId, statut?, datePrevue?) =>
      api().housekeeping.listTaches(hotelId, statut, datePrevue),
    createTache: (input) => api().housekeeping.createTache(input),
    updateTache: (id, input) => api().housekeeping.updateTache(id, input),
    listChecklistItems: (tacheId) => api().housekeeping.listChecklistItems(tacheId),
    updateChecklistItem: (itemId, input) => api().housekeeping.updateChecklistItem(itemId, input),
    stats: (hotelId) => api().housekeeping.stats(hotelId),
    syncFromChambres: (hotelId) => api().housekeeping.syncFromChambres(hotelId),
    chambresMenageSansTache: (hotelId) => api().housekeeping.chambresMenageSansTache(hotelId),
    mobilePlanning:(hotelId,date,assigneeId)=>api().housekeeping.mobilePlanning(hotelId,date,assigneeId),
    balancePlanning:(hotelId,date,userIds)=>api().housekeeping.balancePlanning(hotelId,date,userIds),
    createInspection:(input)=>api().housekeeping.createInspection(input),
    addHousekeepingPhoto:(input)=>api().housekeeping.addHousekeepingPhoto(input),
    recordMinibar:(input)=>api().housekeeping.recordMinibar(input),
    listLinen:(hotelId)=>api().housekeeping.listLinen(hotelId),
    saveLinenArticle:(input)=>api().housekeeping.saveLinenArticle(input),
    moveLinen:(input)=>api().housekeeping.moveLinen(input),
    listLostFound:(hotelId)=>api().housekeeping.listLostFound(hotelId),
    createLostFound:(input)=>api().housekeeping.createLostFound(input),
    updateLostFound:(id,input)=>api().housekeeping.updateLostFound(id,input),
    blockRoom:(input)=>api().housekeeping.blockRoom(input),
    releaseRoom:(id)=>api().housekeeping.releaseRoom(id),
    advancedDashboard:(hotelId,date)=>api().housekeeping.advancedDashboard(hotelId,date),
  },
  commercial: {
    listPartenaires: () => api().commercial.listPartenaires(),
    createPartenaire: (input) => api().commercial.createPartenaire(input),
    listOpportunites: (hotelId?, statut?) => api().commercial.listOpportunites(hotelId, statut),
    createOpportunite: (input) => api().commercial.createOpportunite(input),
    updateOpportunite: (id, input) => api().commercial.updateOpportunite(id, input),
    stats: (hotelId?) => api().commercial.stats(hotelId),
  },
  ged: {
    listVersions: (id) => api().ged.listVersions(id),
    addVersion: (id, note) => api().ged.addVersion(id, note),
    requestOcr: (id, langue) => api().ged.requestOcr(id, langue),
    completeOcr: (id, texte, confidence) => api().ged.completeOcr(id, texte, confidence),
    searchOcr: (query) => api().ged.searchOcr(query),
    listSignatures: (id) => api().ged.listSignatures(id),
    sign: (id, motif) => api().ged.sign(id, motif),
    listCategories: () => api().ged.listCategories(),
    listDocuments: (hotelId?, categorieId?, search?) => api().ged.listDocuments(hotelId, categorieId, search),
    upload: (input) => api().ged.upload(input),
    archiver: (id) => api().ged.archiver(id),
    delete: (id, motif) => api().ged.delete(id, motif),
    ouvrir: (id) => api().ged.ouvrir(id),
  },
  workflow: {
    create: (input) => api().workflow.create(input),
    submit: (workflowId, commentaire) => api().workflow.submit(workflowId, commentaire),
    approve: (workflowId, statut, commentaire) => api().workflow.approve(workflowId, statut, commentaire),
    reject: (workflowId, motif) => api().workflow.reject(workflowId, motif),
    history: (workflowId) => api().workflow.history(workflowId),
    listPending: (filters) => api().workflow.listPending(filters),
    listPendingWithContext: (filters) => api().workflow.listPendingWithContext(filters),
    find: (module, entityType, entityId) => api().workflow.find(module, entityType, entityId),
  },
  workflowProcedures: {
    list: () => api().workflowProcedures.list(),
    update: (code, input) => api().workflowProcedures.update(code, input),
    updateStep: (stepId, input) => api().workflowProcedures.updateStep(stepId, input),
  },
  cloture: {
    create: (hotelId, dateJournal) => api().cloture.create(hotelId, dateJournal),
    prefill: (closureId) => api().cloture.prefill(closureId),
    submit: (closureId) => api().cloture.submit(closureId),
    validateUnit: (closureId) => api().cloture.validateUnit(closureId),
    validateDec: (closureId) => api().cloture.validateDec(closureId),
    reject: (closureId, motif) => api().cloture.reject(closureId, motif),
    close: (closureId) => api().cloture.close(closureId),
    list: (hotelId, dateDebut, dateFin) => api().cloture.list(hotelId, dateDebut, dateFin),
    getPosStatus: (hotelId, dateJournal) => api().cloture.getPosStatus(hotelId, dateJournal),
    getBusinessDate: (hotelId) => api().cloture.getBusinessDate(hotelId),
    getNightAudit: (closureId) => api().cloture.getNightAudit(closureId),
    runNightAudit: (closureId) => api().cloture.runNightAudit(closureId),
    reopenNightAudit: (closureId, motif) => api().cloture.reopenNightAudit(closureId, motif),
  },
  reconciliation: {
    create: (hotelId, dateJournal) => api().reconciliation.create(hotelId, dateJournal),
    prefill: (id) => api().reconciliation.prefill(id),
    justify: (id, justification) => api().reconciliation.justify(id, justification),
    validate: (id) => api().reconciliation.validate(id),
    list: (hotelId, dateDebut, dateFin) => api().reconciliation.list(hotelId, dateDebut, dateFin),
  },
  creances: {
    list: (filters) => api().creances.list(filters),
    fromFacture: (factureId) => api().creances.fromFacture(factureId),
    relance: (creanceId, input) => api().creances.relance(creanceId, input),
    balanceAgee: (hotelId) => api().creances.balanceAgee(hotelId),
    updateStatut: (creanceId, statut) => api().creances.updateStatut(creanceId, statut),
    paiement: (creanceId, montant) => api().creances.paiement(creanceId, montant),
    runRelancesAuto: () => api().creances.runRelancesAuto(),
    getRelancesAuto: () => api().creances.getRelancesAuto(),
    setRelancesAuto: (actif) => api().creances.setRelancesAuto(actif),
  },
  contratsHotel: {
    list: (hotelId?) => api().contratsHotel.list(hotelId),
    get: (id) => api().contratsHotel.get(id),
    create: (input) => api().contratsHotel.create(input),
    update: (id, input) => api().contratsHotel.update(id, input),
    echeances: (jours?) => api().contratsHotel.echeances(jours),
  },
  decCockpit: {
    get: (hotelId) => api().decCockpit.get(hotelId),
    listAlerts: (statut) => api().decCockpit.listAlerts(statut),
    closeAlert: (alertId) => api().decCockpit.closeAlert(alertId),
  },
  dashboardPdg: {
    get: () => api().dashboardPdg.get(),
    exportCsv: () => api().dashboardPdg.exportCsv(),
    exportMensuel: (periode) => api().dashboardPdg.exportMensuel(periode),
  },
  checklist: {
    templates: () => api().checklist.templates(),
    start: (templateId, hotelId) => api().checklist.start(templateId, hotelId),
    get: (runId) => api().checklist.get(runId),
    updateResult: (runId, itemId, input) => api().checklist.updateResult(runId, itemId, input),
    submit: (runId) => api().checklist.submit(runId),
    list: (hotelId) => api().checklist.list(hotelId),
    stats: (hotelId) => api().checklist.stats(hotelId),
  },
  hotelLegal: {
    listFichesPolice: (hotelId, statut) => api().hotelLegal.listFichesPolice(hotelId, statut),
    createFichePolice: (input) => api().hotelLegal.createFichePolice(input),
    updateFichePolice: (ficheId, input) => api().hotelLegal.updateFichePolice(ficheId, input),
    checkoutFichePolice: (ficheId, dateSortie) => api().hotelLegal.checkoutFichePolice(ficheId, dateSortie),
    calculerTaxeSejour: (hotelId, periode, taux) => api().hotelLegal.calculerTaxeSejour(hotelId, periode, taux),
    genererRapportTourisme: (hotelId, periode) => api().hotelLegal.genererRapportTourisme(hotelId, periode),
    listRapportsTourisme: (hotelId) => api().hotelLegal.listRapportsTourisme(hotelId),
    exportFichesPoliceCsv: (hotelId) => api().hotelLegal.exportFichesPoliceCsv(hotelId),
  },
  gedArchivage: {
    listRetentionPolicies: () => api().gedArchivage.listRetentionPolicies(),
    archiveLegally: (documentId, politiqueCode) => api().gedArchivage.archiveLegally(documentId, politiqueCode),
    listLegalArchives: () => api().gedArchivage.listLegalArchives(),
    verifyIntegrity: (archiveId) => api().gedArchivage.verifyIntegrity(archiveId),
  },
  systemHealth: {
    get: () => api().systemHealth.get(),
    gedIntegrity: (limit) => api().systemHealth.gedIntegrity(limit),
  },
  license: {
    getStatus: () => api().license.getStatus(),
    getMachineId: () => api().license.getMachineId(),
    getConfig: () => api().license.getConfig(),
    updateConfig: (input) => api().license.updateConfig(input),
    activate: (key) => api().license.activate(key),
    syncRemote: () => api().license.syncRemote(),
    clear: () => api().license.clear(),
    getPack: () => api().license.getPack(),
  },
  notifications: {
    list: (unreadOnly?, limit?) => api().notifications.list(unreadOnly, limit),
    countUnread: () => api().notifications.countUnread(),
    markRead: (id) => api().notifications.markRead(id),
    markAllRead: () => api().notifications.markAllRead(),
    getRules: () => api().notifications.getRules(),
    updateRule: (input) => api().notifications.updateRule(input),
    generateSystem: () => api().notifications.generateSystem(),
  },
  rgpd: {
    dashboard: () => api().rgpd.dashboard(),
    listTraitements: (actifOnly) => api().rgpd.listTraitements(actifOnly),
    upsertTraitement: (input) => api().rgpd.upsertTraitement(input),
    exportTraitementsCsv: () => api().rgpd.exportTraitementsCsv(),
    listConsentements: (statut) => api().rgpd.listConsentements(statut),
    createConsentement: (input) => api().rgpd.createConsentement(input),
    revokeConsentement: (id, dateRetrait) => api().rgpd.revokeConsentement(id, dateRetrait),
    listDemandes: (statut) => api().rgpd.listDemandes(statut),
    createDemande: (input) => api().rgpd.createDemande(input),
    updateDemande: (id, statut, reponse) => api().rgpd.updateDemande(id, statut, reponse),
    listIncidents: (statut) => api().rgpd.listIncidents(statut),
    createIncident: (input) => api().rgpd.createIncident(input),
    updateIncident: (id, input) => api().rgpd.updateIncident(id, input),
    listConservation: () => api().rgpd.listConservation(),
  },
  reports: {
    overview: () => api().reports.overview(),
    semanticCatalog: () => api().reports.semanticCatalog(),
    compatibleFields: (dimensions, measures) => api().reports.compatibleFields(dimensions, measures),
    previewComposed: (composition, filters) => api().reports.previewComposed(composition, filters),
    exportComposed: (composition, filters, name) => api().reports.exportComposed(composition, filters, name),
    catalog: () => api().reports.catalog(),
    listSources: () => api().reports.listSources(),
    listTemplates: () => api().reports.listTemplates(),
    getTemplate: (id) => api().reports.getTemplate(id),
    createTemplate: (input) => api().reports.createTemplate(input),
    updateTemplate: (id, input) => api().reports.updateTemplate(id, input),
    duplicateTemplate: (id, newName) => api().reports.duplicateTemplate(id, newName),
    deleteTemplate: (id) => api().reports.deleteTemplate(id),
    preview: (dataSource, columns, filters) => api().reports.preview(dataSource, columns, filters),
    previewKpi: (kpiId, filters) => api().reports.previewKpi(kpiId, filters),
    exportTemplate: (templateId) => api().reports.exportTemplate(templateId),
    exportAdHoc: (dataSource, columns, filters, name) => api().reports.exportAdHoc(dataSource, columns, filters, name),
    exportKpi: (kpiId, filters) => api().reports.exportKpi(kpiId, filters),
    listRuns: (limit) => api().reports.listRuns(limit),
  },
  guide: {
    list: () => api().guide.list(),
    get: (slug) => api().guide.get(slug),
    search: (query) => api().guide.search(query),
    sections: () => api().guide.sections(),
    suggested: () => api().guide.suggested(),
    roleProfiles: () => api().guide.roleProfiles(),
  },
};
