import type { Locale } from '@/stores/ui.store';
import generatedEnglish from '@/i18n/en.json';
import generatedArabic from '@/i18n/ar.json';

export const DATE_LOCALES: Record<Locale, string> = {
  fr: 'fr-DZ',
  ar: 'ar-DZ',
  en: 'en-GB',
};

type Messages = Record<string, string>;

const en: Messages = {
  'Changer de langue': 'Change language',
  'Ouvrir le menu': 'Open menu',
  'Déplier le menu latéral': 'Expand sidebar',
  'Replier le menu latéral': 'Collapse sidebar',
  'Menu utilisateur': 'User menu',
  Utilisateur: 'User',
  Paramètres: 'Settings',
  'Changer le mot de passe': 'Change password',
  Déconnexion: 'Sign out',
  Pilotage: 'Management',
  Exploitation: 'Operations',
  'Finances & comptabilité': 'Finance & accounting',
  Opérations: 'Operations',
  'Contrôle interne': 'Internal control',
  'Qualité & relation client': 'Quality & customer relations',
  'Commercial & documents': 'Sales & documents',
  'RH & productivité': 'HR & productivity',
  Administration: 'Administration',
  'Aide & guides': 'Help & guides',
  Système: 'System',
  'Dashboard global': 'Global dashboard',
  'Dashboard PDG': 'Executive dashboard',
  'Modules de pilotage': 'Management modules',
  'Rapports & exports': 'Reports & exports',
  Clients: 'Customers',
  Facturation: 'Billing',
  Rapprochements: 'Reconciliations',
  Créances: 'Receivables',
  Objectifs: 'Targets',
  Workflows: 'Workflows',
  Anomalies: 'Issues',
  Réclamations: 'Complaints',
  Commercial: 'Sales',
  'Gestion documentaire': 'Document management',
  Utilisateurs: 'Users',
  Rôles: 'Roles',
  Rubriques: 'Categories',
  'Manuel utilisateur': 'User manual',
  Synchronisation: 'Synchronization',
  "Journal d'audit": 'Audit log',
  Licence: 'License',
  'Modules activés': 'Enabled modules',
  'Interface & thème': 'Interface & theme',
  Notifications: 'Notifications',
  'Sécurité & accès': 'Security & access',
  'Base de données': 'Database',
  Sauvegarde: 'Backup',
  'Santé système': 'System health',
  Applications: 'Applications',
  'Pilotage Global': 'Global management',
  'Compte et préférences': 'Account and preferences',
  'Mot de passe, session et politique de connexion': 'Password, session and sign-in policy',
  Période: 'Period',
  Année: 'Year',
  Mois: 'Month',
  Chargement: 'Loading',
  'Aucune donnée': 'No data',
  Rechercher: 'Search',
  Ajouter: 'Add',
  Modifier: 'Edit',
  Supprimer: 'Delete',
  Annuler: 'Cancel',
  Enregistrer: 'Save',
  Valider: 'Confirm',
  Fermer: 'Close',
  Retour: 'Back',
  Actions: 'Actions',
  Statut: 'Status',
  Date: 'Date',
  Nom: 'Name',
  Description: 'Description',
  Montant: 'Amount',
  Total: 'Total',
  Actif: 'Active',
  Inactif: 'Inactive',
  Oui: 'Yes',
  Non: 'No',
  'en attente': 'pending',
  échec: 'failed',
  'sync en échec': 'sync failed',
  Connexion: 'Sign in',
  'Se connecter': 'Sign in',
  'Adresse e-mail': 'Email address',
  'Mot de passe': 'Password',
  'Masquer le mot de passe': 'Hide password',
  'Afficher le mot de passe': 'Show password',
  'Mémoriser la session sur cet ordinateur': 'Remember this session on this computer',
  'Accédez à votre espace de pilotage hôtelier et portuaire.': 'Access your hotel and port management workspace.',
  'Identifiants incorrects.': 'Incorrect credentials.',
  'Comptes administrateur': 'Administrator accounts',
  'Profils démo': 'Demo profiles',
  'Mot de passe commun': 'Shared password',
  'Réinitialiser la session locale': 'Reset local session',
  'ERP de pilotage hôtelier': 'Hotel management ERP',
  'Multi-unités': 'Multi-property',
  'KPI temps réel': 'Real-time KPIs',
  'chambre(s) en ménage': 'room(s) being cleaned',
  'chambre(s) en ménage sans tâche (': 'room(s) being cleaned without an assigned task (',
  'pointage(s)': 'attendance record(s)',
  'pointage(s) —': 'attendance record(s) —',
  'pointage(s) en attente de validation.': 'attendance record(s) awaiting approval.',
  'rubriques sélectionnées.': 'revenue categories selected.',
  'Clôture journalière': 'Daily closing',
  'Chiffre d’affaires': 'Revenue',
  'chiffre d’affaires': 'revenue',
  'Encaissements & trésorerie': 'Collections & cash management',
  'Saisie journalière': 'Daily entry',
  'Saisie mensuelle': 'Monthly entry',
  'Hébergement & occupation': 'Rooms & occupancy',
  'Housekeeping': 'Housekeeping',
  'ex: STD, SUP, DLX': 'e.g. STD, SUP, DLX',
};

const ar: Messages = {
  'Changer de langue': 'تغيير اللغة',
  'Ouvrir le menu': 'فتح القائمة',
  'Déplier le menu latéral': 'توسيع القائمة الجانبية',
  'Replier le menu latéral': 'طي القائمة الجانبية',
  'Menu utilisateur': 'قائمة المستخدم',
  Utilisateur: 'المستخدم',
  Paramètres: 'الإعدادات',
  'Changer le mot de passe': 'تغيير كلمة المرور',
  Déconnexion: 'تسجيل الخروج',
  Pilotage: 'القيادة',
  Exploitation: 'الاستغلال',
  'Finances & comptabilité': 'المالية والمحاسبة',
  Opérations: 'العمليات',
  'Contrôle interne': 'الرقابة الداخلية',
  'Qualité & relation client': 'الجودة وعلاقات العملاء',
  'Commercial & documents': 'التجارة والوثائق',
  'RH & productivité': 'الموارد البشرية والإنتاجية',
  Administration: 'الإدارة',
  'Aide & guides': 'المساعدة والأدلة',
  Système: 'النظام',
  'Dashboard global': 'لوحة القيادة العامة',
  'Dashboard PDG': 'لوحة قيادة المدير العام',
  'Modules de pilotage': 'وحدات القيادة',
  'Rapports & exports': 'التقارير والتصدير',
  Clients: 'العملاء',
  Facturation: 'الفوترة',
  Rapprochements: 'المطابقات',
  Créances: 'المستحقات',
  Objectifs: 'الأهداف',
  Workflows: 'سير العمل',
  Anomalies: 'المخالفات',
  Réclamations: 'الشكاوى',
  Commercial: 'التجاري',
  'Gestion documentaire': 'إدارة الوثائق',
  Utilisateurs: 'المستخدمون',
  Rôles: 'الأدوار',
  Rubriques: 'الأقسام',
  'Manuel utilisateur': 'دليل المستخدم',
  Synchronisation: 'المزامنة',
  "Journal d'audit": 'سجل التدقيق',
  Licence: 'الرخصة',
  'Modules activés': 'الوحدات المفعلة',
  'Interface & thème': 'الواجهة والمظهر',
  Notifications: 'الإشعارات',
  'Sécurité & accès': 'الأمان والوصول',
  'Base de données': 'قاعدة البيانات',
  Sauvegarde: 'النسخ الاحتياطي',
  'Santé système': 'حالة النظام',
  Applications: 'التطبيقات',
  'Pilotage Global': 'القيادة العامة',
  'Compte et préférences': 'الحساب والتفضيلات',
  'Mot de passe, session et politique de connexion': 'كلمة المرور والجلسة وسياسة الدخول',
  Période: 'الفترة',
  Année: 'السنة',
  Mois: 'الشهر',
  Chargement: 'جارٍ التحميل',
  'Aucune donnée': 'لا توجد بيانات',
  Rechercher: 'بحث',
  Ajouter: 'إضافة',
  Modifier: 'تعديل',
  Supprimer: 'حذف',
  Annuler: 'إلغاء',
  Enregistrer: 'حفظ',
  Valider: 'تأكيد',
  Fermer: 'إغلاق',
  Retour: 'رجوع',
  Actions: 'الإجراءات',
  Statut: 'الحالة',
  Date: 'التاريخ',
  Nom: 'الاسم',
  Description: 'الوصف',
  Montant: 'المبلغ',
  Total: 'المجموع',
  Actif: 'نشط',
  Inactif: 'غير نشط',
  Oui: 'نعم',
  Non: 'لا',
  'en attente': 'قيد الانتظار',
  échec: 'فشل',
  'sync en échec': 'فشل المزامنة',
  Connexion: 'تسجيل الدخول',
  'Se connecter': 'تسجيل الدخول',
  'Adresse e-mail': 'البريد الإلكتروني',
  'Mot de passe': 'كلمة المرور',
  'Masquer le mot de passe': 'إخفاء كلمة المرور',
  'Afficher le mot de passe': 'إظهار كلمة المرور',
  'Mémoriser la session sur cet ordinateur': 'تذكر الجلسة على هذا الجهاز',
  'Accédez à votre espace de pilotage hôtelier et portuaire.': 'ادخل إلى مساحة إدارة الفندق والميناء.',
  'Identifiants incorrects.': 'بيانات الدخول غير صحيحة.',
  'Comptes administrateur': 'حسابات الإدارة',
  'Profils démo': 'حسابات تجريبية',
  'Mot de passe commun': 'كلمة المرور المشتركة',
  'Réinitialiser la session locale': 'إعادة ضبط الجلسة المحلية',
  'ERP de pilotage hôtelier': 'نظام إدارة فندقية',
  'Multi-unités': 'متعدد الوحدات',
  'KPI temps réel': 'مؤشرات فورية',
  'chambre(s) en ménage': 'غرفة قيد التنظيف',
  'chambre(s) en ménage sans tâche (': 'غرفة قيد التنظيف دون مهمة مسندة (',
  'pointage(s)': 'سجل حضور',
  'pointage(s) —': 'سجل حضور —',
  'pointage(s) en attente de validation.': 'سجل حضور في انتظار المصادقة.',
  'rubriques sélectionnées.': 'بنود الإيرادات المحددة.',
  'Clôture journalière': 'الإقفال اليومي',
  'Chiffre d’affaires': 'رقم الأعمال',
  'chiffre d’affaires': 'رقم الأعمال',
  'Encaissements & trésorerie': 'التحصيلات والخزينة',
  'Saisie journalière': 'الإدخال اليومي',
  'Saisie mensuelle': 'الإدخال الشهري',
  'Hébergement & occupation': 'الإيواء والإشغال',
  'Housekeeping': 'التدبير الفندقي',
  'ex: STD, SUP, DLX': 'مثال: STD، SUP، DLX',
};

const messages: Record<Locale, Messages> = {
  fr: {},
  en: { ...generatedEnglish, ...en },
  ar: { ...generatedArabic, ...ar },
};

export function translate(locale: Locale, text: string): string {
  return messages[locale][text] ?? text;
}

export function translateRenderedText(locale: Locale, value: string): string {
  if (locale === 'fr' || !value.trim()) return value;

  const leading = value.match(/^\s*/)?.[0] ?? '';
  const trailing = value.match(/\s*$/)?.[0] ?? '';
  const content = value.slice(leading.length, value.length - trailing.length);
  const exact = messages[locale][content];
  if (exact) return `${leading}${exact}${trailing}`;

  const counted = content.match(/^(\d+(?:[.,]\d+)?)\s+(.+)$/);
  if (counted) {
    const translatedLabel = messages[locale][counted[2]];
    if (translatedLabel) return `${leading}${counted[1]} ${translatedLabel}${trailing}`;
  }

  return value;
}

export function applyDocumentLocale(locale: Locale): void {
  document.documentElement.lang = locale;
  document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr';
}
