import { MODULES } from '@/modules/moduleCatalog';

/** Routes principales à vérifier en smoke test (chargement sans crash). */
export const SMOKE_ROUTES: string[] = [
  '/dashboard',
  '/modules',
  '/admin/users',
  '/admin/hotels',
  '/admin/roles',
  '/admin/rubriques',
  '/recettes/journalieres',
  '/recettes/historique',
  '/recettes/validation',
  '/recettes/mensuelles',
  '/objectifs',
  '/portmaster',
  '/portmaster/bateaux',
  '/portmaster/contrats',
  '/portmaster/clients',
  '/portmaster/factures',
  '/portmaster/mouvements',
  '/portmaster/recouvrement',
  '/encaissements',
  '/encaissements/liste',
  '/facturation',
  '/facturation/factures',
  '/clients',
  '/hebergement',
  '/tarifs',
  '/rh',
  '/rh/pilotage',
  '/rh/employes',
  '/anomalies',
  '/decisions',
  '/reclamations',
  '/parking',
  '/plage',
  '/stocks',
  '/achats',
  '/maintenance',
  '/commercial',
  '/ged',
  '/rapports',
  '/settings',
  '/settings/modules',
  '/settings/interface',
  '/settings/notifications',
  '/settings/backup',
  '/settings/database',
  '/audit/logs',
  '/system/sync',
  ...MODULES.filter((m) => m.existingRoute).map((m) => m.existingRoute as string),
  ...MODULES.map((m) => `/modules/${m.id}`),
];
