import { contextBridge, ipcRenderer } from 'electron';
import type { IpcApi } from '../src/shared/types/ipc';

const api: IpcApi = {
  app: {
    getVersion: () => ipcRenderer.invoke('app:getVersion') as Promise<string>,
    ping: () =>
      ipcRenderer.invoke('app:ping') as Promise<{ ok: boolean; timestamp: number }>,
  },
  auth: {
    login: (payload) => ipcRenderer.invoke('auth:login', payload),
    logout: (sessionToken) => ipcRenderer.invoke('auth:logout', sessionToken),
    restore: (sessionToken) => ipcRenderer.invoke('auth:restore', sessionToken),
    getCurrentUser: () => ipcRenderer.invoke('auth:getCurrentUser'),
    getProfile: () => ipcRenderer.invoke('auth:getProfile'),
    changePassword: (payload) => ipcRenderer.invoke('auth:changePassword', payload),
    listDemoAccounts: () => ipcRenderer.invoke('auth:listDemoAccounts'),
  },
  users: {
    list: (search) => ipcRenderer.invoke('users:list', search),
    get: (id) => ipcRenderer.invoke('users:get', id),
    create: (input) => ipcRenderer.invoke('users:create', input),
    update: (id, input) =>
      ipcRenderer.invoke('users:update', id, input),
    deactivate: (id, reason) =>
      ipcRenderer.invoke('users:deactivate', id, reason),
    pendingCount: () => ipcRenderer.invoke('users:pendingCount'),
    activatePending: (id) => ipcRenderer.invoke('users:activatePending', id),
  },
  hotels: {
    list: () => ipcRenderer.invoke('hotels:list'),
    get: (id) => ipcRenderer.invoke('hotels:get', id),
    create: (input) => ipcRenderer.invoke('hotels:create', input),
    update: (id, input) =>
      ipcRenderer.invoke('hotels:update', id, input),
    pickLogo: (hotelId) => ipcRenderer.invoke('hotels:pickLogo', hotelId),
    removeLogo: (hotelId) => ipcRenderer.invoke('hotels:removeLogo', hotelId),
    deactivate: (id, reason) =>
      ipcRenderer.invoke('hotels:deactivate', id, reason),
  },
  roles: {
    list: () => ipcRenderer.invoke('roles:list'),
    listForSelect: () => ipcRenderer.invoke('roles:listForSelect'),
    listPermissions: () => ipcRenderer.invoke('roles:listPermissions'),
    updatePermissions: (roleId, permissionCodes) =>
      ipcRenderer.invoke('roles:updatePermissions', roleId, permissionCodes),
  },
  rubriques: {
    list: () => ipcRenderer.invoke('rubriques:list'),
    create: (input) => ipcRenderer.invoke('rubriques:create', input),
    update: (id, input) =>
      ipcRenderer.invoke('rubriques:update', id, input),
    delete: (id) => ipcRenderer.invoke('rubriques:delete', id),
    reorder: (items) =>
      ipcRenderer.invoke('rubriques:reorder', items),
  },
  audit: {
    list: (filters) => ipcRenderer.invoke('audit:list', filters),
  },
  recettes: {
    rubriques: () => ipcRenderer.invoke('recettes:rubriques'),
    getSaisie: (hotelId, dateJournal) =>
      ipcRenderer.invoke('recettes:getSaisie', hotelId, dateJournal),
    saveSaisie: (input) =>
      ipcRenderer.invoke('recettes:saveSaisie', input),
    historique: (filters) =>
      ipcRenderer.invoke('recettes:historique', filters),
    historiqueGrouped: (filters) =>
      ipcRenderer.invoke('recettes:historiqueGrouped', filters),
    updateLigne: (id, montant, observation, motif) =>
      ipcRenderer.invoke('recettes:updateLigne', id, montant, observation, motif),
    deleteLigne: (id, motif) =>
      ipcRenderer.invoke('recettes:deleteLigne', id, motif),
    deleteJournee: (hotelId, dateJournal, motif) =>
      ipcRenderer.invoke('recettes:deleteJournee', hotelId, dateJournal, motif),
    listAValider: (hotelId) =>
      ipcRenderer.invoke('recettes:listAValider', hotelId),
    validerJour: (hotelId, dateJournal, motif) =>
      ipcRenderer.invoke('recettes:validerJour', hotelId, dateJournal, motif),
    refuserJour: (hotelId, dateJournal, motif) =>
      ipcRenderer.invoke('recettes:refuserJour', hotelId, dateJournal, motif),
    getMensuelle: (hotelId, annee, mois) =>
      ipcRenderer.invoke('recettes:getMensuelle', hotelId, annee, mois),
    saveMensuelle: (hotelId, annee, mois, payload) =>
      ipcRenderer.invoke('recettes:saveMensuelle', hotelId, annee, mois, payload),
  },
  objectifs: {
    list: (filters) =>
      ipcRenderer.invoke('objectifs:list', filters),
    get: (hotelId, annee, mois) =>
      ipcRenderer.invoke('objectifs:get', hotelId, annee, mois),
    save: (input) =>
      ipcRenderer.invoke('objectifs:save', input),
  },
  dashboard: {
    get: (filters) =>
      ipcRenderer.invoke('dashboard:get', filters),
  },
  portmaster: {
    dashboard: () => ipcRenderer.invoke('portmaster:dashboard'),
    listBateaux: (search) =>
      ipcRenderer.invoke('portmaster:bateaux:list', search),
    getBateau: (id) =>
      ipcRenderer.invoke('portmaster:bateaux:get', id),
    createBateau: (input) =>
      ipcRenderer.invoke('portmaster:bateaux:create', input),
    updateBateau: (id, input) =>
      ipcRenderer.invoke('portmaster:bateaux:update', id, input),
    deactivateBateau: (id) =>
      ipcRenderer.invoke('portmaster:bateaux:deactivate', id),
    listEmplacements: () =>
      ipcRenderer.invoke('portmaster:emplacements:list'),
    listEmplacementsLibres: () =>
      ipcRenderer.invoke('portmaster:emplacements:libres'),
    listContrats: (statut) =>
      ipcRenderer.invoke('portmaster:contrats:list', statut),
    getContrat: (id) =>
      ipcRenderer.invoke('portmaster:contrats:get', id),
    saveContrat: (input, id) =>
      ipcRenderer.invoke('portmaster:contrats:save', input, id),
    submitContrat: (id) =>
      ipcRenderer.invoke('portmaster:contrats:submit', id),
    addEncaissement: (input) =>
      ipcRenderer.invoke('portmaster:encaissements:add', input),
    bateauxOptions: () =>
      ipcRenderer.invoke('portmaster:bateaux:options'),
    listClients: (search) =>
      ipcRenderer.invoke('portmaster:clients:list', search),
    getClient: (id) =>
      ipcRenderer.invoke('portmaster:clients:get', id),
    saveClient: (input, id) =>
      ipcRenderer.invoke('portmaster:clients:save', input, id),
    clientsOptions: () =>
      ipcRenderer.invoke('portmaster:clients:options'),
    listBassins: () =>
      ipcRenderer.invoke('portmaster:referentiel:bassins'),
    listQuais: (bassinId) =>
      ipcRenderer.invoke('portmaster:referentiel:quais', bassinId),
    listEmplacementsDetail: (filters) =>
      ipcRenderer.invoke('portmaster:referentiel:emplacements', filters),
    searchReferentiel: (query) =>
      ipcRenderer.invoke('portmaster:referentiel:search', query),
    listAlertes: () =>
      ipcRenderer.invoke('portmaster:alertes:list'),
    listTarifs: () => ipcRenderer.invoke('portmaster:tarifs:list'),
    getTarif: (id) => ipcRenderer.invoke('portmaster:tarifs:get', id),
    saveTarif: (input, id) =>
      ipcRenderer.invoke('portmaster:tarifs:save', input, id),
    simulerTarif: (tarifId, longueurM) =>
      ipcRenderer.invoke('portmaster:tarifs:simuler', tarifId, longueurM),
    listFactures: (statut) =>
      ipcRenderer.invoke('portmaster:factures:list', statut),
    getFacture: (id) =>
      ipcRenderer.invoke('portmaster:factures:get', id),
    createFacture: (input) =>
      ipcRenderer.invoke('portmaster:factures:create', input),
    createFactureFromContrat: (contratId, tarifId) =>
      ipcRenderer.invoke('portmaster:factures:fromContrat', contratId, tarifId),
    submitFacture: (id) =>
      ipcRenderer.invoke('portmaster:factures:submit', id),
    addPaiementFacture: (input) =>
      ipcRenderer.invoke('portmaster:factures:addPaiement', input),
    listValidations: () =>
      ipcRenderer.invoke('portmaster:validations:list'),
    validerEntite: (entityType, entityId, motif) =>
      ipcRenderer.invoke('portmaster:validations:valider', entityType, entityId, motif),
    rejeterEntite: (entityType, entityId, motif) =>
      ipcRenderer.invoke('portmaster:validations:rejeter', entityType, entityId, motif),
    listMouvements: () =>
      ipcRenderer.invoke('portmaster:mouvements:list'),
    createMouvement: (input) =>
      ipcRenderer.invoke('portmaster:mouvements:create', input),
    recouvrementSummary: () =>
      ipcRenderer.invoke('portmaster:recouvrement:summary'),
    listCreances: () =>
      ipcRenderer.invoke('portmaster:recouvrement:creances'),
    listRelances: () =>
      ipcRenderer.invoke('portmaster:recouvrement:relances'),
    createRelance: (input) =>
      ipcRenderer.invoke('portmaster:recouvrement:relanceCreate', input),
    marquerRelanceEnvoyee: (id) =>
      ipcRenderer.invoke('portmaster:recouvrement:relanceEnvoyee', id),
  },
  settings: {
    getBranding: () => ipcRenderer.invoke('settings:getBranding'),
    getBusinessSector: () => ipcRenderer.invoke('settings:getBusinessSector'),
    getAppInfo: () => ipcRenderer.invoke('settings:getAppInfo'),
    update: (input) => ipcRenderer.invoke('settings:update', input),
    pickBrandAsset: (asset) => ipcRenderer.invoke('settings:pickBrandAsset', asset),
    removeBrandAsset: (asset) => ipcRenderer.invoke('settings:removeBrandAsset', asset),
    getUiPreferences: () => ipcRenderer.invoke('settings:getUiPreferences'),
    saveUiPreferences: (prefs) => ipcRenderer.invoke('settings:saveUiPreferences', prefs),
  },
  database: {
    getInfo: () => ipcRenderer.invoke('database:getInfo'),
    integrityCheck: () => ipcRenderer.invoke('database:integrityCheck'),
    vacuum: () => ipcRenderer.invoke('database:vacuum'),
    pickImportFile: () => ipcRenderer.invoke('database:pickImportFile'),
    importLegacy: (filePath) =>
      ipcRenderer.invoke('database:importLegacy', filePath),
  },
  backup: {
    list: () => ipcRenderer.invoke('backup:list'),
    create: () => ipcRenderer.invoke('backup:create'),
    restore: (filename) =>
      ipcRenderer.invoke('backup:restore', filename),
    delete: (filename) =>
      ipcRenderer.invoke('backup:delete', filename),
  },
  sync: {
    getConfig: () => ipcRenderer.invoke('sync:config:get'),
    updateConfig: (input) =>
      ipcRenderer.invoke('sync:config:update', input),
    getStatus: () => ipcRenderer.invoke('sync:status'),
    listQueue: () => ipcRenderer.invoke('sync:queue:list'),
    retryFailed: () => ipcRenderer.invoke('sync:queue:retryFailed'),
    listConflicts: () => ipcRenderer.invoke('sync:conflicts:list'),
    resolveConflict: (conflictId, decision, note) => ipcRenderer.invoke('sync:conflicts:resolve', conflictId, decision, note),
    run: () => ipcRenderer.invoke('sync:run'),
  },
  export: {
    excel: (kind) => ipcRenderer.invoke('export:excel', kind),
    facturePdf: (factureId) =>
      ipcRenderer.invoke('export:facturePdf', factureId),
    dashboardExcel: (filters) =>
      ipcRenderer.invoke('export:dashboardExcel', filters),
    dashboardPdf: (filters) =>
      ipcRenderer.invoke('export:dashboardPdf', filters),
  },
  clients: {
    getDashboard: () => ipcRenderer.invoke('clients:getDashboard'),
    list: (filters) => ipcRenderer.invoke('clients:list', filters),
    get: (id) => ipcRenderer.invoke('clients:get', id),
    create: (input) => ipcRenderer.invoke('clients:create', input),
    update: (id, input) => ipcRenderer.invoke('clients:update', id, input),
    toggleActif: (id) => ipcRenderer.invoke('clients:toggleActif', id),
    delete: (id) => ipcRenderer.invoke('clients:delete', id),
    listContacts: (clientId) => ipcRenderer.invoke('clients:contacts:list', clientId),
    createContact: (clientId, input) => ipcRenderer.invoke('clients:contacts:create', clientId, input),
    updateContact: (contactId, input) => ipcRenderer.invoke('clients:contacts:update', contactId, input),
    deleteContact: (contactId) => ipcRenderer.invoke('clients:contacts:delete', contactId),
  },
  tresorerie: {
    getDashboard: (hotelId) =>
      ipcRenderer.invoke('tresorerie:dashboard', hotelId),
    listEncaissements: (filters) =>
      ipcRenderer.invoke('tresorerie:encaissements:list', filters),
    createEncaissement: (input) =>
      ipcRenderer.invoke('tresorerie:encaissements:create', input),
    updateEncaissement: (id, input) =>
      ipcRenderer.invoke('tresorerie:encaissements:update', id, input),
    confirmerEncaissement: (id) =>
      ipcRenderer.invoke('tresorerie:encaissements:confirmer', id),
    rejeterEncaissement: (id, motif) =>
      ipcRenderer.invoke('tresorerie:encaissements:rejeter', id, motif),
    deleteEncaissement: (id) =>
      ipcRenderer.invoke('tresorerie:encaissements:delete', id),
    listComptes: (hotelId) =>
      ipcRenderer.invoke('tresorerie:comptes:list', hotelId),
    createCompte: (input) =>
      ipcRenderer.invoke('tresorerie:comptes:create', input),
    updateCompte: (id, input) =>
      ipcRenderer.invoke('tresorerie:comptes:update', id, input),
    deleteCompte: (id) =>
      ipcRenderer.invoke('tresorerie:comptes:delete', id),
    getJournalCaisse: (hotelId, dateDebut, dateFin) =>
      ipcRenderer.invoke('tresorerie:caisse:list', hotelId, dateDebut, dateFin),
    addOperationCaisse: (input) =>
      ipcRenderer.invoke('tresorerie:caisse:add', input),
    deleteOperationCaisse: (id) =>
      ipcRenderer.invoke('tresorerie:caisse:delete', id),
    listPaymentOrders: (hotelId) => ipcRenderer.invoke('tresorerie:ordres:list',hotelId),
    createPaymentOrder: (input) => ipcRenderer.invoke('tresorerie:ordres:create',input),
    decidePaymentOrder: (id,approved) => ipcRenderer.invoke('tresorerie:ordres:decide',id,approved),
    executePaymentOrder: (id) => ipcRenderer.invoke('tresorerie:ordres:execute',id),
    listForecast: (hotelId,from,to) => ipcRenderer.invoke('tresorerie:forecast:list',hotelId,from,to),
    createForecast: (input) => ipcRenderer.invoke('tresorerie:forecast:create',input),
    importBankStatement: (input) => ipcRenderer.invoke('tresorerie:bank:import',input),
    listBankLines: (accountId) => ipcRenderer.invoke('tresorerie:bank:lines',accountId),
    suggestReconciliation: (lineId) => ipcRenderer.invoke('tresorerie:bank:suggest',lineId),
    confirmReconciliation: (input) => ipcRenderer.invoke('tresorerie:bank:confirm',input),
    listCostCenters: (hotelId) => ipcRenderer.invoke('tresorerie:cost-centers:list',hotelId),
    createCostCenter: (input) => ipcRenderer.invoke('tresorerie:cost-centers:create',input),
    allocateCost: (input) => ipcRenderer.invoke('tresorerie:cost-centers:allocate',input),
    analyticalReport: (hotelId,from,to) => ipcRenderer.invoke('tresorerie:analytics:report',hotelId,from,to),
  },
  facturation: {
    getDashboard: (hotelId) =>
      ipcRenderer.invoke('facturation:getDashboard', hotelId),
    listFactures: (filters) =>
      ipcRenderer.invoke('facturation:listFactures', filters),
    getFacture: (id) =>
      ipcRenderer.invoke('facturation:getFacture', id),
    createFacture: (input) =>
      ipcRenderer.invoke('facturation:createFacture', input),
    updateFacture: (id, input) =>
      ipcRenderer.invoke('facturation:updateFacture', id, input),
    soumettre: (id) =>
      ipcRenderer.invoke('facturation:soumettre', id),
    valider: (id) =>
      ipcRenderer.invoke('facturation:valider', id),
    annuler: (id) =>
      ipcRenderer.invoke('facturation:annuler', id),
    deleteFacture: (id) =>
      ipcRenderer.invoke('facturation:deleteFacture', id),
    addPaiement: (input) =>
      ipcRenderer.invoke('facturation:addPaiement', input),
    deletePaiement: (id) =>
      ipcRenderer.invoke('facturation:deletePaiement', id),
    listClients: (search) =>
      ipcRenderer.invoke('facturation:listClients', search),
    createClient: (input) =>
      ipcRenderer.invoke('facturation:createClient', input),
    updateClient: (id, input) =>
      ipcRenderer.invoke('facturation:updateClient', id, input),
    deleteClient: (id) =>
      ipcRenderer.invoke('facturation:deleteClient', id),
    exportPdf: (factureId) =>
      ipcRenderer.invoke('facturation:exportPdf', factureId),
    createAvoir: (input) =>
      ipcRenderer.invoke('facturation:createAvoir', input),
    listRegistre: (filters) =>
      ipcRenderer.invoke('facturation:registre:list', filters),
    exportRegistreCsv: (filters) =>
      ipcRenderer.invoke('facturation:registre:exportCsv', filters),
  },
  comptabilite: {
    listComptes: (classe) => ipcRenderer.invoke('comptabilite:comptes:list', classe),
    listJournaux: () => ipcRenderer.invoke('comptabilite:journaux:list'),
    listExercices: () => ipcRenderer.invoke('comptabilite:exercices:list'),
    createExercice: (input) => ipcRenderer.invoke('comptabilite:exercices:create', input),
    cloturerExercice: (exerciceId) => ipcRenderer.invoke('comptabilite:exercices:cloturer', exerciceId),
    listEcritures: (filters) => ipcRenderer.invoke('comptabilite:ecritures:list', filters),
    getEcriture: (id) => ipcRenderer.invoke('comptabilite:ecritures:get', id),
    createEcriture: (input) => ipcRenderer.invoke('comptabilite:ecritures:create', input),
    validerEcriture: (id) => ipcRenderer.invoke('comptabilite:ecritures:valider', id),
    getGrandLivre: (compteNumero, dateDebut, dateFin) =>
      ipcRenderer.invoke('comptabilite:grandLivre', compteNumero, dateDebut, dateFin),
    getBalance: (exerciceId, dateDebut, dateFin) =>
      ipcRenderer.invoke('comptabilite:balance', exerciceId, dateDebut, dateFin),
    listLignesLettrables: (compteNumero) => ipcRenderer.invoke('comptabilite:lettrage:lignes', compteNumero),
    listLettrages: () => ipcRenderer.invoke('comptabilite:lettrage:list'),
    creerLettrage: (ligneIds) => ipcRenderer.invoke('comptabilite:lettrage:create', ligneIds),
    annulerLettrage: (id) => ipcRenderer.invoke('comptabilite:lettrage:cancel', id),
  },
  fiscalite: {
    listRegistreTva: (periode) => ipcRenderer.invoke('fiscalite:registreTva:list', periode),
    genererRegistreTva: (periode) => ipcRenderer.invoke('fiscalite:registreTva:generer', periode),
    exportRegistreTvaCsv: (periode) => ipcRenderer.invoke('fiscalite:registreTva:exportCsv', periode),
    calculerDeclarationTva: (periode) => ipcRenderer.invoke('fiscalite:declaration:calculer', periode),
    getDeclarationTva: (periode) => ipcRenderer.invoke('fiscalite:declaration:get', periode),
    listDeclarationsTva: () => ipcRenderer.invoke('fiscalite:declaration:list'),
    createRetenue: (input) => ipcRenderer.invoke('fiscalite:retenue:create', input),
    listRetenues: () => ipcRenderer.invoke('fiscalite:retenue:list'),
    genererLiasse: (exercice) => ipcRenderer.invoke('fiscalite:liasse:generer', exercice),
    listLiasse: (exercice) => ipcRenderer.invoke('fiscalite:liasse:list', exercice),
    exportLiasseCsv: (exercice) => ipcRenderer.invoke('fiscalite:liasse:exportCsv', exercice),
    listAchats: (periode) => ipcRenderer.invoke('fiscalite:achats:list', periode),
    createAchat: (input) => ipcRenderer.invoke('fiscalite:achats:create', input),
    importAchatsFromBons: (periode) => ipcRenderer.invoke('fiscalite:achats:importBons', periode),
    exportAchatsCsv: (periode) => ipcRenderer.invoke('fiscalite:achats:exportCsv', periode),
    genererLiasseAvancee: (exercice) => ipcRenderer.invoke('fiscalite:liasse:genererAvancee', exercice),
    exportTeledeclTvaG50: (periode) => ipcRenderer.invoke('fiscalite:teledecl:exportTvaG50', periode),
    listTeledeclarations: (typeDecl) => ipcRenderer.invoke('fiscalite:teledecl:list', typeDecl),
    marquerTeledeclDeclaree: (id, referenceDgi) => ipcRenderer.invoke('fiscalite:teledecl:marquerDeclaree', id, referenceDgi),
  },
  sifec: {
    dashboard: () => ipcRenderer.invoke('sifec:dashboard'),
    getConfig: () => ipcRenderer.invoke('sifec:config:get'),
    updateConfig: (input) => ipcRenderer.invoke('sifec:config:update', input),
    testConnection: () => ipcRenderer.invoke('sifec:config:test'),
    listFactures: (statut) => ipcRenderer.invoke('sifec:factures:list', statut),
    prepareFacture: (factureId) => ipcRenderer.invoke('sifec:factures:prepare', factureId),
    submitFacture: (factureId) => ipcRenderer.invoke('sifec:factures:submit', factureId),
    submitBatch: (factureIds) => ipcRenderer.invoke('sifec:factures:submitBatch', factureIds),
    listTransmissions: (limit) => ipcRenderer.invoke('sifec:transmissions:list', limit),
  },
  modulesLegaux: {
    dashboard: () => ipcRenderer.invoke('modulesLegaux:dashboard'),
    immo: {
      list: (actifOnly) => ipcRenderer.invoke('immo:list', actifOnly),
      upsert: (input, id) => ipcRenderer.invoke('immo:upsert', input, id),
      genererPlan: (immobilisationId) => ipcRenderer.invoke('immo:genererPlan', immobilisationId),
      listAmortissements: (immobilisationId, periode) => ipcRenderer.invoke('immo:listAmortissements', immobilisationId, periode),
      comptabiliserMensuel: (periode) => ipcRenderer.invoke('immo:comptabiliserMensuel', periode),
      exportCsv: () => ipcRenderer.invoke('immo:exportCsv'),
    },
    casnos: {
      listAffilies: (actifOnly) => ipcRenderer.invoke('casnos:affilies:list', actifOnly),
      upsertAffilie: (input, id) => ipcRenderer.invoke('casnos:affilies:upsert', input, id),
      listDeclarations: (periode) => ipcRenderer.invoke('casnos:declarations:list', periode),
      calculerDeclaration: (affilieId, periode, revenu) => ipcRenderer.invoke('casnos:declarations:calculer', affilieId, periode, revenu),
      calculerPeriode: (periode) => ipcRenderer.invoke('casnos:declarations:calculerPeriode', periode),
      marquerDeclaree: (id, referenceCasnos) => ipcRenderer.invoke('casnos:declarations:marquerDeclaree', id, referenceCasnos),
      exportCsv: (periode) => ipcRenderer.invoke('casnos:exportCsv', periode),
    },
    inventaire: {
      listSessions: (exercice) => ipcRenderer.invoke('inventaireLegal:sessions:list', exercice),
      createSession: (input) => ipcRenderer.invoke('inventaireLegal:sessions:create', input),
      listLignes: (sessionId) => ipcRenderer.invoke('inventaireLegal:lignes:list', sessionId),
      updateLigne: (ligneId, quantitePhysique, motifEcart) => ipcRenderer.invoke('inventaireLegal:lignes:update', ligneId, quantitePhysique, motifEcart),
      cloturerSession: (sessionId) => ipcRenderer.invoke('inventaireLegal:sessions:cloturer', sessionId),
      exportCsv: (sessionId) => ipcRenderer.invoke('inventaireLegal:exportCsv', sessionId),
    },
  },
  hebergement: {
    listTypesChambre: (hotelId?) => ipcRenderer.invoke('hebergement:listTypesChambre', hotelId),
    createTypeChambre: (input) => ipcRenderer.invoke('hebergement:createTypeChambre', input),
    deleteTypeChambre: (id) => ipcRenderer.invoke('hebergement:deleteTypeChambre', id),
    listChambres: (hotelId?, statut?) => ipcRenderer.invoke('hebergement:listChambres', hotelId, statut),
    createChambre: (input) => ipcRenderer.invoke('hebergement:createChambre', input),
    updateChambre: (id, input) => ipcRenderer.invoke('hebergement:updateChambre', id, input),
    updateStatutChambre: (id, statut) => ipcRenderer.invoke('hebergement:updateStatutChambre', id, statut),
    deleteChambre: (id) => ipcRenderer.invoke('hebergement:deleteChambre', id),
    listReservations: (hotelId?, dateDebut?, dateFin?, statut?) =>
      ipcRenderer.invoke('hebergement:listReservations', hotelId, dateDebut, dateFin, statut),
    getReservation: (id) => ipcRenderer.invoke('hebergement:getReservation', id),
    createReservation: (input) => ipcRenderer.invoke('hebergement:createReservation', input),
    updateReservationStatut: (id, statut) => ipcRenderer.invoke('hebergement:updateReservationStatut', id, statut),
    deleteReservation: (id) => ipcRenderer.invoke('hebergement:deleteReservation', id),
    estimatePrice: (input) => ipcRenderer.invoke('hebergement:estimatePrice', input),
    createFactureFromReservation: (reservationId) =>
      ipcRenderer.invoke('hebergement:createFactureFromReservation', reservationId),
    getOccupationKpis: (dateDebut, dateFin, hotelId?) =>
      ipcRenderer.invoke('hebergement:getOccupationKpis', dateDebut, dateFin, hotelId),
    getFolio: (reservationId) => ipcRenderer.invoke('hebergement:getFolio', reservationId),
    createFolio: (reservationId) => ipcRenderer.invoke('hebergement:createFolio', reservationId),
    addFolioLine: (folioId, input) => ipcRenderer.invoke('hebergement:addFolioLine', folioId, input),
    closeFolioToFacture: (reservationId) => ipcRenderer.invoke('hebergement:closeFolioToFacture', reservationId),
    listGroupes: (hotelId) => ipcRenderer.invoke('pms:groupes:list', hotelId),
    createGroupe: (input) => ipcRenderer.invoke('pms:groupes:create', input),
    addReservationToGroupe: (groupeId, reservationId) => ipcRenderer.invoke('pms:groupes:addReservation', groupeId, reservationId),
    listDepots: (reservationId) => ipcRenderer.invoke('pms:depots:list', reservationId),
    createDepot: (input) => ipcRenderer.invoke('pms:depots:create', input),
    listChannelConnectors: () => ipcRenderer.invoke('pms:channels:list'),
    saveChannelConnector: (input) => ipcRenderer.invoke('pms:channels:save', input),
    importChannelReservation: (input) => ipcRenderer.invoke('pms:channels:import', input),
    updateReservation: (reservationId, input) => ipcRenderer.invoke('pms:reservations:update', reservationId, input),
    moveReservationRoom: (reservationId, input) => ipcRenderer.invoke('pms:reservations:moveRoom', reservationId, input),
    listRoomMoves: (reservationId) => ipcRenderer.invoke('pms:reservations:roomMoves', reservationId),
    listOccupants: (reservationId) => ipcRenderer.invoke('pms:occupants:list', reservationId),
    saveOccupant: (reservationId, input, occupantId) => ipcRenderer.invoke('pms:occupants:save', reservationId, input, occupantId),
    deleteOccupant: (occupantId) => ipcRenderer.invoke('pms:occupants:delete', occupantId),
    listWaitlist: (hotelId) => ipcRenderer.invoke('pms:waitlist:list', hotelId),
    createWaitlist: (input) => ipcRenderer.invoke('pms:waitlist:create', input),
    updateWaitlistStatus: (id, statut) => ipcRenderer.invoke('pms:waitlist:status', id, statut),
    promoteWaitlist: (id, input) => ipcRenderer.invoke('pms:waitlist:promote', id, input),
    listCancellationPolicies: (hotelId) => ipcRenderer.invoke('pms:cancellationPolicies:list', hotelId),
    createCancellationPolicy: (input) => ipcRenderer.invoke('pms:cancellationPolicies:create', input),
    cancelReservation: (reservationId, input) => ipcRenderer.invoke('pms:reservations:cancel', reservationId, input),
    markReservationNoShow: (reservationId, input) => ipcRenderer.invoke('pms:reservations:noShow', reservationId, input),
    operateDeposit: (depotId, input) => ipcRenderer.invoke('pms:depots:operate', depotId, input),
    transferFolioLines: (input) => ipcRenderer.invoke('pms:folios:transfer', input),
    shareFolio: (input) => ipcRenderer.invoke('pms:folios:share', input),
  },
  tarifs: {
    listComposants:    (hotelId?)             => ipcRenderer.invoke('tarifs:listComposants', hotelId),
    createComposant:   (input)                => ipcRenderer.invoke('tarifs:createComposant', input),
    deleteComposant:   (id)                   => ipcRenderer.invoke('tarifs:deleteComposant', id),
    listFormules:      (hotelId?)             => ipcRenderer.invoke('tarifs:listFormules', hotelId),
    createFormule:     (input)                => ipcRenderer.invoke('tarifs:createFormule', input),
    deleteFormule:     (id)                   => ipcRenderer.invoke('tarifs:deleteFormule', id),
    listPlans:         (hotelId?)             => ipcRenderer.invoke('tarifs:listPlans', hotelId),
    createPlan:        (input)                => ipcRenderer.invoke('tarifs:createPlan', input),
    deletePlan:        (id)                   => ipcRenderer.invoke('tarifs:deletePlan', id),
    getGrille:         (hotelId, planId, dateDebut, dateFin, formuleId?) =>
                         ipcRenderer.invoke('tarifs:getGrille', hotelId, planId, dateDebut, dateFin, formuleId),
    upsertTarif:       (input)                => ipcRenderer.invoke('tarifs:upsertTarif', input),
    upsertBulk:        (input)                => ipcRenderer.invoke('tarifs:upsertBulk', input),
    listPromotions:    (hotelId?)             => ipcRenderer.invoke('tarifs:listPromotions', hotelId),
    createPromotion:   (input)                => ipcRenderer.invoke('tarifs:createPromotion', input),
    togglePromotion:   (id, actif)            => ipcRenderer.invoke('tarifs:togglePromotion', id, actif),
    deletePromotion:   (id)                   => ipcRenderer.invoke('tarifs:deletePromotion', id),
    listConventions:   (hotelId?, clientId?)  => ipcRenderer.invoke('tarifs:listConventions', hotelId, clientId),
    createConvention:  (input)                => ipcRenderer.invoke('tarifs:createConvention', input),
    toggleConvention:  (id, actif)            => ipcRenderer.invoke('tarifs:toggleConvention', id, actif),
    deleteConvention:  (id)                   => ipcRenderer.invoke('tarifs:deleteConvention', id),
    simuler:           (input)                => ipcRenderer.invoke('tarifs:simuler', input),
  },
  yield: {
    listRules:          (hotelId?)  => ipcRenderer.invoke('yield:listRules', hotelId),
    createRule:         (input)     => ipcRenderer.invoke('yield:createRule', input),
    updateRule:         (id, input) => ipcRenderer.invoke('yield:updateRule', id, input),
    toggleRule:         (id, actif) => ipcRenderer.invoke('yield:toggleRule', id, actif),
    deleteRule:         (id)        => ipcRenderer.invoke('yield:deleteRule', id),
    computeSuggestions: (input)     => ipcRenderer.invoke('yield:computeSuggestions', input),
    applySuggestions:   (input)     => ipcRenderer.invoke('yield:applySuggestions', input),
  },
  rh: {
    getDashboard: (dateDebut?, dateFin?, hotelId?) =>
      ipcRenderer.invoke('rh:dashboard', dateDebut, dateFin, hotelId),
    pendingAccountsCount: () => ipcRenderer.invoke('rh:pendingAccountsCount'),
    getMonEspace: () => ipcRenderer.invoke('rh:monEspace'),
    listDirections: () => ipcRenderer.invoke('rh:directions:list'),
    createDirection: (input) => ipcRenderer.invoke('rh:directions:create', input),
    updateDirection: (id, input) => ipcRenderer.invoke('rh:directions:update', id, input),
    listDepartements: (directionId) => ipcRenderer.invoke('rh:departements:list', directionId),
    createDepartement: (input) => ipcRenderer.invoke('rh:departements:create', input),
    updateDepartement: (id, input) => ipcRenderer.invoke('rh:departements:update', id, input),
    listPostes: (departementId) => ipcRenderer.invoke('rh:postes:list', departementId),
    createPoste: (input) => ipcRenderer.invoke('rh:postes:create', input),
    updatePoste: (id, input) => ipcRenderer.invoke('rh:postes:update', id, input),
    listEmployes: (search?) => ipcRenderer.invoke('rh:employes:list', search),
    getEmploye: (id) => ipcRenderer.invoke('rh:employes:get', id),
    createEmploye: (input) => ipcRenderer.invoke('rh:employes:create', input),
    createEmployeWizard: (input) => ipcRenderer.invoke('rh:employes:createWizard', input),
    updateEmploye: (id, input) => ipcRenderer.invoke('rh:employes:update', id, input),
    sortirEmploye: (id, input) => ipcRenderer.invoke('rh:employes:sortir', id, input),
    listRecrutements: (statut?) => ipcRenderer.invoke('rh:recrutements:list', statut),
    createRecrutement: (input) => ipcRenderer.invoke('rh:recrutements:create', input),
    validerRecrutement: (id) => ipcRenderer.invoke('rh:recrutements:valider', id),
    refuserRecrutement: (id, motif?) => ipcRenderer.invoke('rh:recrutements:refuser', id, motif),
    listOffresEmploi: (statut?) => ipcRenderer.invoke('rh:ats:offres:list', statut),
    createOffreEmploi: (input) => ipcRenderer.invoke('rh:ats:offres:create', input),
    updateOffreEmploi: (id, input) => ipcRenderer.invoke('rh:ats:offres:update', id, input),
    getPipelineRecrutement: (offreId?) => ipcRenderer.invoke('rh:ats:pipeline', offreId),
    createCandidature: (input) => ipcRenderer.invoke('rh:ats:candidatures:create', input),
    avancerCandidature: (input) => ipcRenderer.invoke('rh:ats:candidatures:avancer', input),
    listEntretiensRecrutement: (recrutementId) => ipcRenderer.invoke('rh:ats:entretiens:list', recrutementId),
    createEntretienRecrutement: (input) => ipcRenderer.invoke('rh:ats:entretiens:create', input),
    updateEntretienRecrutement: (id, input) => ipcRenderer.invoke('rh:ats:entretiens:update', id, input),
    listHistoriqueCandidature: (recrutementId) => ipcRenderer.invoke('rh:ats:historique', recrutementId),
    runReconciliationTemps: (dateDebut, dateFin, hotelId) => ipcRenderer.invoke('rh:temps:reconcilier', dateDebut, dateFin, hotelId),
    listReconciliationsTemps: (opts) => ipcRenderer.invoke('rh:temps:reconciliations:list', opts),
    listTempsAlertes: (statut) => ipcRenderer.invoke('rh:temps:alertes:list', statut),
    traiterTempsAlerte: (alerteId, action) => ipcRenderer.invoke('rh:temps:alertes:traiter', alerteId, action),
    getReconciliationPaie: (periode) => ipcRenderer.invoke('rh:temps:paie:reconciliation', periode),
    validerReconciliationPaie: (employeId, dateDebut, dateFin) => ipcRenderer.invoke('rh:temps:paie:valider', employeId, dateDebut, dateFin),
    exportReconciliationCsv: (dateDebut, dateFin) => ipcRenderer.invoke('rh:temps:exportCsv', dateDebut, dateFin),
    listEmployeCompetences: (employeId) => ipcRenderer.invoke('rh:gpec:employeCompetences:list', employeId),
    setEmployeCompetence: (input) => ipcRenderer.invoke('rh:gpec:employeCompetences:set', input),
    getMatriceGpec: (employeId) => ipcRenderer.invoke('rh:gpec:matrice', employeId),
    listCampagnesEvaluation: () => ipcRenderer.invoke('rh:gpec:campagnes:list'),
    createCampagneEvaluation: (input) => ipcRenderer.invoke('rh:gpec:campagnes:create', input),
    updateCampagneEvaluation: (id, input) => ipcRenderer.invoke('rh:gpec:campagnes:update', id, input),
    lancerCampagneEvaluation: (campagneId) => ipcRenderer.invoke('rh:gpec:campagnes:lancer', campagneId),
    cloturerCampagneEvaluation: (campagneId) => ipcRenderer.invoke('rh:gpec:campagnes:cloturer', campagneId),
    getCampagneSynthese: (campagneId) => ipcRenderer.invoke('rh:gpec:campagnes:synthese', campagneId),
    listCampagneEvaluations: (campagneId, employeId) => ipcRenderer.invoke('rh:gpec:evaluations:list', campagneId, employeId),
    soumettreEvaluationLigne: (ligneId, input) => ipcRenderer.invoke('rh:gpec:evaluations:soumettre', ligneId, input),
    validerEvaluationLigne: (ligneId) => ipcRenderer.invoke('rh:gpec:evaluations:valider', ligneId),
    listContrats: (employeId) => ipcRenderer.invoke('rh:contrats:list', employeId),
    createContrat: (input) => ipcRenderer.invoke('rh:contrats:create', input),
    listAllContrats: () => ipcRenderer.invoke('rh:contrats:listAll'),
    listPointages: (dateDebut?, dateFin?, employeId?) =>
      ipcRenderer.invoke('rh:pointages:list', dateDebut, dateFin, employeId),
    upsertPointage: (input) => ipcRenderer.invoke('rh:pointages:upsert', input),
    soumettrePointage: (id) => ipcRenderer.invoke('rh:pointages:soumettre', id),
    validerPointage: (id, approuve) => ipcRenderer.invoke('rh:pointages:valider', id, approuve),
    listAbsences: (statut?, opts?) => ipcRenderer.invoke('rh:absences:list', statut, opts),
    createAbsence: (input) => ipcRenderer.invoke('rh:absences:create', input),
    deciderAbsence: (id, approuve) => ipcRenderer.invoke('rh:absences:decider', id, approuve),
    cancelAbsence: (id, motif) => ipcRenderer.invoke('rh:absences:cancel', id, motif),
    listAffectations: (opts?) => ipcRenderer.invoke('rh:affectations:list', opts),
    createAffectation: (input) => ipcRenderer.invoke('rh:affectations:create', input),
    terminerAffectation: (id, dateFin?) => ipcRenderer.invoke('rh:affectations:terminer', id, dateFin),
    listOrganisation: (hotelId?) => ipcRenderer.invoke('rh:organisation:list', hotelId),
    upsertOrganisation: (input) => ipcRenderer.invoke('rh:organisation:upsert', input),
    deleteOrganisation: (id) => ipcRenderer.invoke('rh:organisation:delete', id),
    listSoldesConges: (opts?) => ipcRenderer.invoke('rh:soldes:list', opts),
    upsertSoldeConges: (input) => ipcRenderer.invoke('rh:soldes:upsert', input),
    listPlannings: (opts?) => ipcRenderer.invoke('rh:plannings:list', opts),
    createPlanning: (input) => ipcRenderer.invoke('rh:plannings:create', input),
    deletePlanning: (id) => ipcRenderer.invoke('rh:plannings:delete', id),
    getPlanningSynthese: (dateDebut, dateFin, hotelId?) =>
      ipcRenderer.invoke('rh:plannings:synthese', dateDebut, dateFin, hotelId),
    getSuggestionsRenfort: (seuil?) => ipcRenderer.invoke('rh:plannings:suggestionsRenfort', seuil),
    listEquipes: (chefEmployeId?) => ipcRenderer.invoke('rh:equipes:list', chefEmployeId),
    addEquipeMembre: (input) => ipcRenderer.invoke('rh:equipes:add', input),
    removeEquipeMembre: (id) => ipcRenderer.invoke('rh:equipes:remove', id),
    listBulletins: (periode?) => ipcRenderer.invoke('rh:paie:bulletins:list', periode),
    generatePrePaie: (periode) => ipcRenderer.invoke('rh:paie:generate', periode),
    validerBulletin: (id) => ipcRenderer.invoke('rh:paie:bulletins:valider', id),
    getPaieCloture: (periode) => ipcRenderer.invoke('rh:paie:cloture:get', periode),
    listPaieClotures: () => ipcRenderer.invoke('rh:paie:cloture:list'),
    validerPaieMensuelle: (periode) => ipcRenderer.invoke('rh:paie:cloture:valider', periode),
    cloturerPaieMensuelle: (periode) => ipcRenderer.invoke('rh:paie:cloture:cloturer', periode),
    getPaieParams: () => ipcRenderer.invoke('rh:paie:params:get'),
    comptabiliserBulletin: (id, hotelId, dateOperation) =>
      ipcRenderer.invoke('rh:paie:bulletins:comptabiliser', id, hotelId, dateOperation),
    listPrimes: (periode?, employeId?) => ipcRenderer.invoke('rh:paie:primes:list', periode, employeId),
    createPrime: (input) => ipcRenderer.invoke('rh:paie:primes:create', input),
    deletePrime: (id) => ipcRenderer.invoke('rh:paie:primes:delete', id),
    getDlgConfig: () => ipcRenderer.invoke('rh:dlg:config:get'),
    setDlgConfig: (input) => ipcRenderer.invoke('rh:dlg:config:set', input),
    pickDlgFolder: (kind) => ipcRenderer.invoke('rh:dlg:pickFolder', kind),
    pickDlgImportFile: () => ipcRenderer.invoke('rh:dlg:pickImportFile'),
    exportVersDlg: (periode) => ipcRenderer.invoke('rh:dlg:export', periode),
    importDepuisDlg: (periode, sourceFile) => ipcRenderer.invoke('rh:dlg:import', periode, sourceFile),
    listDlgJournal: (limit?) => ipcRenderer.invoke('rh:dlg:journal', limit),
    listFormationsCatalog: (actifOnly?) => ipcRenderer.invoke('rh:formations:catalog', actifOnly),
    createFormationCatalog: (input) => ipcRenderer.invoke('rh:formations:catalog:create', input),
    updateFormationCatalog: (id, input) => ipcRenderer.invoke('rh:formations:catalog:update', id, input),
    listEmployeFormations: (opts?) => ipcRenderer.invoke('rh:formations:employe:list', opts),
    assignEmployeFormation: (input) => ipcRenderer.invoke('rh:formations:employe:assign', input),
    updateEmployeFormation: (id, input) => ipcRenderer.invoke('rh:formations:employe:update', id, input),
    deleteEmployeFormation: (id) => ipcRenderer.invoke('rh:formations:employe:delete', id),
    listCompetences: () => ipcRenderer.invoke('rh:competences:list'),
    createCompetence: (input) => ipcRenderer.invoke('rh:competences:create', input),
    listPosteCompetences: (posteId?) => ipcRenderer.invoke('rh:competences:poste:list', posteId),
    setPosteCompetence: (input) => ipcRenderer.invoke('rh:competences:poste:set', input),
    removePosteCompetence: (id) => ipcRenderer.invoke('rh:competences:poste:remove', id),
    listEntretiens: (opts?) => ipcRenderer.invoke('rh:entretiens:list', opts),
    createEntretien: (input) => ipcRenderer.invoke('rh:entretiens:create', input),
    updateEntretien: (id, input) => ipcRenderer.invoke('rh:entretiens:update', id, input),
    deleteEntretien: (id) => ipcRenderer.invoke('rh:entretiens:delete', id),
    listRhDocuments: (employeId?) => ipcRenderer.invoke('rh:documents:list', employeId),
    uploadRhDocument: (employeId, type, nom?) =>
      ipcRenderer.invoke('rh:documents:upload', employeId, type, nom),
    deleteRhDocument: (id) => ipcRenderer.invoke('rh:documents:delete', id),
    openRhDocument: (id) => ipcRenderer.invoke('rh:documents:open', id),
    getComparatifUnites: (dateDebut?, dateFin?) => ipcRenderer.invoke('rh:pilotage:comparatif', dateDebut, dateFin),
    getPrevisionsEffectif: (opts?) => ipcRenderer.invoke('rh:pilotage:previsions', opts),
    listOnboardingSuivi: (opts?) => ipcRenderer.invoke('rh:pilotage:onboarding:list', opts),
    completeOnboardingStep: (employeId, stepCode) =>
      ipcRenderer.invoke('rh:pilotage:onboarding:complete', employeId, stepCode),
    getPortRhSynthese: () => ipcRenderer.invoke('rh:pilotage:port:synthese'),
    updateEmployeTypeActivite: (input) => ipcRenderer.invoke('rh:pilotage:port:typeActivite', input),
    getRhAiConfig: () => ipcRenderer.invoke('rh:ai:config'),
    buildRhDecisionContext: (hotelId?) => ipcRenderer.invoke('rh:ai:context', hotelId),
    generateRhAiAnalysis: (opts?) => ipcRenderer.invoke('rh:ai:analyze', opts),
    getConformiteDashboard: () => ipcRenderer.invoke('rh:conformite:dashboard'),
    syncCongesLegaux: (annee?) => ipcRenderer.invoke('rh:conformite:syncConges', annee),
    updateConformiteSuivi: (employeId, code, statut, opts?) =>
      ipcRenderer.invoke('rh:conformite:suivi:update', employeId, code, statut, opts),
    listDossierModeles: () => ipcRenderer.invoke('rh:ged:modeles'),
    getDossierEmploye: (employeId) => ipcRenderer.invoke('rh:ged:dossier', employeId),
    scanDossierFolder: (employeId, modeleCode?) =>
      ipcRenderer.invoke('rh:ged:scanFolder', employeId, modeleCode),
    scanSingleDocument: (employeId, modeleCode) =>
      ipcRenderer.invoke('rh:ged:scanSingle', employeId, modeleCode),
    soumettreDocumentValidation: (documentId) => ipcRenderer.invoke('rh:ged:soumettre', documentId),
    listValidationsN1: () => ipcRenderer.invoke('rh:validations:n1:list'),
    countValidationsN1: () => ipcRenderer.invoke('rh:validations:n1:count'),
    validerN1Absence: (id, approuve, commentaire?) =>
      ipcRenderer.invoke('rh:validations:n1:absence', id, approuve, commentaire),
    validerN1Pointage: (id, approuve) => ipcRenderer.invoke('rh:validations:n1:pointage', id, approuve),
    validerN1Document: (id, approuve) => ipcRenderer.invoke('rh:validations:n1:document', id, approuve),
    listRegistrePersonnel: () => ipcRenderer.invoke('rh:registres:personnel:list'),
    listRegistreConges: (annee) => ipcRenderer.invoke('rh:registres:conges:list', annee),
    listAccidentsTravail: () => ipcRenderer.invoke('rh:registres:accidents:list'),
    listVisitesMedicales: () => ipcRenderer.invoke('rh:registres:visites:list'),
    createAccidentTravail: (input) => ipcRenderer.invoke('rh:registres:accidents:create', input),
    createVisiteMedicale: (input) => ipcRenderer.invoke('rh:registres:visites:create', input),
    exportRegistrePersonnelPdf: () => ipcRenderer.invoke('rh:registres:personnel:exportPdf'),
    exportRegistrePersonnelCsv: () => ipcRenderer.invoke('rh:registres:personnel:exportCsv'),
    exportRegistreCongesPdf: (annee) => ipcRenderer.invoke('rh:registres:conges:exportPdf', annee),
    exportRegistreAccidentsPdf: () => ipcRenderer.invoke('rh:registres:accidents:exportPdf'),
    exportRegistreVisitesPdf: () => ipcRenderer.invoke('rh:registres:visites:exportPdf'),
    exportBulletinPaiePdf: (bulletinId) => ipcRenderer.invoke('rh:paie:bulletin:exportPdf', bulletinId),
    previewStc: (input) => ipcRenderer.invoke('rh:rupture:previewStc', input),
    processRuptureContrat: (input) => ipcRenderer.invoke('rh:rupture:process', input),
    listRupturesContrat: () => ipcRenderer.invoke('rh:rupture:list'),
    exportCertificatTravailPdf: (ruptureId) => ipcRenderer.invoke('rh:rupture:certificat:exportPdf', ruptureId),
    exportStcPdf: (ruptureId) => ipcRenderer.invoke('rh:rupture:stc:exportPdf', ruptureId),
    exportDasAnnuelle: (annee) => ipcRenderer.invoke('rh:declarations:exportDas', annee),
    exportCnasMensuelle: (periode) => ipcRenderer.invoke('rh:declarations:exportCnas', periode),
    exportVirementsPaie: (periode) => ipcRenderer.invoke('rh:declarations:exportVirements', periode),
    exportAnemEmbauches: () => ipcRenderer.invoke('rh:declarations:exportAnem'),
    exportDadsUAnnuelle: (annee) => ipcRenderer.invoke('rh:declarations:exportDadsU', annee),
    getOrganigrammeEgt: (hotelId) => ipcRenderer.invoke('rh:egt:organigramme', hotelId),
    getEffectifsEgt: (hotelId) => ipcRenderer.invoke('rh:egt:effectifs', hotelId),
    listFichesPoste: (posteId) => ipcRenderer.invoke('rh:fichesPoste:list', posteId),
    upsertFichePoste: (input) => ipcRenderer.invoke('rh:fichesPoste:upsert', input),
    exportOrganigrammeCsv: (hotelId) => ipcRenderer.invoke('rh:egt:exportCsv', hotelId),
    listPointeuses: (hotelId: number) => ipcRenderer.invoke('rh:pointeuses:list', hotelId),
    upsertPointeuse: (input: unknown, id?: number) => ipcRenderer.invoke('rh:pointeuses:upsert', input, id),
    importPointeuseCsv: (hotelId: number, csvContent: string, pointeuseId?: number) =>
      ipcRenderer.invoke('rh:pointeuses:importCsv', hotelId, csvContent, pointeuseId),
    listRawPunches: (hotelId: number, traite?: boolean) =>
      ipcRenderer.invoke('rh:pointeuses:rawPunches', hotelId, traite),
    traiterRawPunches: (hotelId: number, dateDebut?: string, dateFin?: string) =>
      ipcRenderer.invoke('rh:pointeuses:traiter', hotelId, dateDebut, dateFin),
    setEmployeBadge: (employeId: number, badgeId: string | null) =>
      ipcRenderer.invoke('rh:pointeuses:setBadge', employeId, badgeId),
    syncPointeuseNow: (pointeuseId: number) => ipcRenderer.invoke('rh:pointeuses:syncNow', pointeuseId),
    setPointeuseSyncAuto: (pointeuseId: number, syncAuto: boolean, intervalMin?: number) =>
      ipcRenderer.invoke('rh:pointeuses:setSyncAuto', pointeuseId, syncAuto, intervalMin),
    listPointeusesExtended: (hotelId: number) => ipcRenderer.invoke('rh:pointeuses:listExtended', hotelId),
  },
  modules: {
    listEnabled: () => ipcRenderer.invoke('modules:listEnabled'),
    listConfig: () => ipcRenderer.invoke('modules:listConfig'),
    setEnabled: (moduleId: string, enabled: boolean) =>
      ipcRenderer.invoke('modules:setEnabled', moduleId, enabled),
  },
  anomalies: {
    list: (hotelId?: number, statut?: string) => ipcRenderer.invoke('anomalies:list', hotelId, statut),
    stats: (hotelId: number) => ipcRenderer.invoke('anomalies:stats', hotelId),
    create: (input: unknown) => ipcRenderer.invoke('anomalies:create', input),
    update: (id: number, input: unknown) => ipcRenderer.invoke('anomalies:update', id, input),
    delete: (id: number) => ipcRenderer.invoke('anomalies:delete', id),
  },
  decisions: {
    list: (filters?: unknown) => ipcRenderer.invoke('decisions:list', filters),
    listForUser: (filters?: unknown) => ipcRenderer.invoke('decisions:listForUser', filters),
    destinataires: (id: number) => ipcRenderer.invoke('decisions:destinataires', id),
    get: (id: number) => ipcRenderer.invoke('decisions:get', id),
    create: (input: unknown) => ipcRenderer.invoke('decisions:create', input),
    update: (id: number, input: unknown) => ipcRenderer.invoke('decisions:update', id, input),
    marquerLu: (id: number) => ipcRenderer.invoke('decisions:marquerLu', id),
    archiver: (id: number) => ipcRenderer.invoke('decisions:archiver', id),
  },
  reclamations: {
    list: (hotelId?: number, statut?: string) => ipcRenderer.invoke('reclamations:list', hotelId, statut),
    stats: (hotelId: number) => ipcRenderer.invoke('reclamations:stats', hotelId),
    create: (input: unknown) => ipcRenderer.invoke('reclamations:create', input),
    update: (id: number, input: unknown) => ipcRenderer.invoke('reclamations:update', id, input),
  },
  stocks: {
    listProduits: () => ipcRenderer.invoke('stocks:listProduits'),
    createProduit: (input: unknown) => ipcRenderer.invoke('stocks:createProduit', input),
    getNiveaux: (hotelId: number) => ipcRenderer.invoke('stocks:getNiveaux', hotelId),
    createMouvement: (input: unknown) => ipcRenderer.invoke('stocks:createMouvement', input),
    listCategories: () => ipcRenderer.invoke('stocks:listCategories'),
    listMagasins:(hotelId)=>ipcRenderer.invoke('stocks:magasins:list',hotelId),
    createMagasin:(input)=>ipcRenderer.invoke('stocks:magasins:create',input),
    listNiveauxMagasins:(hotelId)=>ipcRenderer.invoke('stocks:magasins:niveaux',hotelId),
    listLots:(hotelId,produitId)=>ipcRenderer.invoke('stocks:lots:list',hotelId,produitId),
    receiveLot:(input)=>ipcRenderer.invoke('stocks:lots:receive',input),
    consumeFefo:(input)=>ipcRenderer.invoke('stocks:lots:consumeFefo',input),
    listTransferts:(hotelId)=>ipcRenderer.invoke('stocks:transferts:list',hotelId),
    createTransfert:(input)=>ipcRenderer.invoke('stocks:transferts:create',input),
    validateTransfert:(id)=>ipcRenderer.invoke('stocks:transferts:validate',id),
    listInventaires:(hotelId)=>ipcRenderer.invoke('stocks:inventaires:list',hotelId),
    createInventaire:(input)=>ipcRenderer.invoke('stocks:inventaires:create',input),
    getInventoryLines:(id)=>ipcRenderer.invoke('stocks:inventaires:lines',id),
    countInventoryLine:(inventaireId,produitId,quantite)=>ipcRenderer.invoke('stocks:inventaires:count',inventaireId,produitId,quantite),
    validateInventory:(id)=>ipcRenderer.invoke('stocks:inventaires:validate',id),
    findByBarcode:(hotelId,barcode)=>ipcRenderer.invoke('stocks:barcode',hotelId,barcode),
  },
  cuisine: {
    listRecettes: (hotelId: number) => ipcRenderer.invoke('cuisine:recettes:list', hotelId),
    getRecette: (id: number) => ipcRenderer.invoke('cuisine:recettes:get', id),
    createRecette: (input: unknown) => ipcRenderer.invoke('cuisine:recettes:create', input),
    updateRecette: (id: number, input: unknown) => ipcRenderer.invoke('cuisine:recettes:update', id, input),
    upsertRecetteLigne: (recetteId: number, input: unknown, ligneId?: number) =>
      ipcRenderer.invoke('cuisine:recettes:ligne:upsert', recetteId, input, ligneId),
    removeRecetteLigne: (recetteId: number, ligneId: number) =>
      ipcRenderer.invoke('cuisine:recettes:ligne:remove', recetteId, ligneId),
    validerRecette: (id: number) => ipcRenderer.invoke('cuisine:recettes:valider', id),
    listOrdres: (hotelId: number) => ipcRenderer.invoke('cuisine:ordres:list', hotelId),
    createOrdre: (input: unknown) => ipcRenderer.invoke('cuisine:ordres:create', input),
    executerOrdre: (id: number) => ipcRenderer.invoke('cuisine:ordres:executer', id),
    listVentesPos: (hotelId: number) => ipcRenderer.invoke('cuisine:pos:list', hotelId),
    enregistrerVentePos: (input: unknown) => ipcRenderer.invoke('cuisine:pos:vente', input),
  },
  pos: {
    listKds: (pointVenteId) => ipcRenderer.invoke('pos:kds:list', pointVenteId),
    updateKds: (id, statut) => ipcRenderer.invoke('pos:kds:update', id, statut),
    listDevices: (pointVenteId) => ipcRenderer.invoke('pos:devices:list', pointVenteId),
    saveDevice: (input) => ipcRenderer.invoke('pos:devices:save', input),
    listPointsVente: (hotelId: number) => ipcRenderer.invoke('pos:points:list', hotelId),
    createPointVente: (input: unknown) => ipcRenderer.invoke('pos:points:create', input),
    listFactions: (pointVenteId: number) => ipcRenderer.invoke('pos:factions:list', pointVenteId),
    createFaction: (input: unknown) => ipcRenderer.invoke('pos:factions:create', input),
    listSessions: (pointVenteId: number, dateService?: string) => ipcRenderer.invoke('pos:sessions:list', pointVenteId, dateService),
    openSession: (input: unknown) => ipcRenderer.invoke('pos:sessions:open', input),
    getRapportSession: (sessionId: number) => ipcRenderer.invoke('pos:sessions:rapport', sessionId),
    cloturerSession: (input: unknown) => ipcRenderer.invoke('pos:sessions:cloturer', input),
    listTickets: (sessionId: number) => ipcRenderer.invoke('pos:tickets:list', sessionId),
    createTicket: (input: unknown) => ipcRenderer.invoke('pos:tickets:create', input),
    addTicketLigne: (input: unknown) => ipcRenderer.invoke('pos:tickets:addLigne', input),
    removeTicketLigne: (ligneId: number) => ipcRenderer.invoke('pos:tickets:removeLigne', ligneId),
    validerTicket: (input: unknown) => ipcRenderer.invoke('pos:tickets:valider', input),
    annulerTicket: (ticketId: number) => ipcRenderer.invoke('pos:tickets:annuler', ticketId),
    listCloturesJournalieres: (pointVenteId: number) => ipcRenderer.invoke('pos:clotures:list', pointVenteId),
    cloturerJournee: (input: unknown) => ipcRenderer.invoke('pos:clotures:journee', input),
    getHotelClosureStatus: (hotelId: number, dateJournal: string) => ipcRenderer.invoke('pos:hotelClosureStatus', hotelId, dateJournal),
    listSalles: (pointVenteId) => ipcRenderer.invoke('pos:salles:list',pointVenteId),
    createSalle: (input) => ipcRenderer.invoke('pos:salles:create',input),
    listTables: (salleId) => ipcRenderer.invoke('pos:tables:list',salleId),
    saveTable: (input,tableId) => ipcRenderer.invoke('pos:tables:save',input,tableId),
    updateTableStatus: (tableId,statut) => ipcRenderer.invoke('pos:tables:status',tableId,statut),
    assignTicketTable: (ticketId,input) => ipcRenderer.invoke('pos:tickets:assignTable',ticketId,input),
    updateServiceStage: (ticketId,etape) => ipcRenderer.invoke('pos:tickets:serviceStage',ticketId,etape),
    splitTicket: (ticketId,lineIds) => ipcRenderer.invoke('pos:tickets:split',ticketId,lineIds),
    applyDiscount: (ticketId,input) => ipcRenderer.invoke('pos:tickets:discount',ticketId,input),
    refundTicket: (ticketId,input) => ipcRenderer.invoke('pos:tickets:refund',ticketId,input),
  },
  achats: {
    listFournisseurs: () => ipcRenderer.invoke('achats:listFournisseurs'),
    createFournisseur: (input: unknown) => ipcRenderer.invoke('achats:createFournisseur', input),
    listBons: (hotelId?: number, statut?: string) => ipcRenderer.invoke('achats:listBons', hotelId, statut),
    createBon: (input: unknown) => ipcRenderer.invoke('achats:createBon', input),
    validerBon: (id: number) => ipcRenderer.invoke('achats:validerBon', id),
    envoyerBon: (id: number) => ipcRenderer.invoke('achats:envoyerBon', id),
    livrerBon: (id: number, input?: unknown) => ipcRenderer.invoke('achats:livrerBon', id, input),
    getBonLignes: (bonId: number) => ipcRenderer.invoke('achats:getBonLignes', bonId),
    listDemandes: (hotelId) => ipcRenderer.invoke('achats:demandes:list',hotelId),
    createDemande: (input) => ipcRenderer.invoke('achats:demandes:create',input),
    submitDemande: (id) => ipcRenderer.invoke('achats:demandes:submit',id),
    decideDemande: (id,approved) => ipcRenderer.invoke('achats:demandes:decide',id,approved),
    listConsultations: (hotelId) => ipcRenderer.invoke('achats:consultations:list',hotelId),
    createConsultation: (input) => ipcRenderer.invoke('achats:consultations:create',input),
    listOffres: (consultationId) => ipcRenderer.invoke('achats:offres:list',consultationId),
    createOffre: (input) => ipcRenderer.invoke('achats:offres:create',input),
    awardOffre: (id) => ipcRenderer.invoke('achats:offres:award',id),
    listFactures: (hotelId) => ipcRenderer.invoke('achats:factures:list',hotelId),
    createFacture: (input) => ipcRenderer.invoke('achats:factures:create',input),
    validateFacture: (id,force) => ipcRenderer.invoke('achats:factures:validate',id,force),
    payFacture: (id,input) => ipcRenderer.invoke('achats:factures:pay',id,input),
  },
  maintenance: {
    listEquipements: (hotelId: number) => ipcRenderer.invoke('maintenance:listEquipements', hotelId),
    createEquipement: (input: unknown) => ipcRenderer.invoke('maintenance:createEquipement', input),
    listInterventions: (hotelId: number, statut?: string) => ipcRenderer.invoke('maintenance:listInterventions', hotelId, statut),
    createIntervention: (input: unknown) => ipcRenderer.invoke('maintenance:createIntervention', input),
    updateIntervention: (id: number, input: unknown) => ipcRenderer.invoke('maintenance:updateIntervention', id, input),
    stats: (hotelId: number) => ipcRenderer.invoke('maintenance:stats', hotelId),
    listPlans:(hotelId:number)=>ipcRenderer.invoke('maintenance:plans:list',hotelId),
    createPlan:(input:unknown)=>ipcRenderer.invoke('maintenance:plans:create',input),
    generateWorkOrders:(through:string)=>ipcRenderer.invoke('maintenance:plans:generate',through),
    refreshSla:(hotelId:number)=>ipcRenderer.invoke('maintenance:sla:refresh',hotelId),
    consumePart:(input:unknown)=>ipcRenderer.invoke('maintenance:parts:consume',input),
    logLabor:(input:unknown)=>ipcRenderer.invoke('maintenance:labor:log',input),
    listContracts:(hotelId:number)=>ipcRenderer.invoke('maintenance:contracts:list',hotelId),
    createContract:(input:unknown)=>ipcRenderer.invoke('maintenance:contracts:create',input),
    costReport:(hotelId:number,from:string,to:string)=>ipcRenderer.invoke('maintenance:costs:report',hotelId,from,to),
  },
  housekeeping: {
    listTaches: (hotelId: number, statut?: string, datePrevue?: string) =>
      ipcRenderer.invoke('housekeeping:listTaches', hotelId, statut, datePrevue),
    createTache: (input: unknown) => ipcRenderer.invoke('housekeeping:createTache', input),
    updateTache: (id: number, input: unknown) => ipcRenderer.invoke('housekeeping:updateTache', id, input),
    listChecklistItems: (tacheId: number) => ipcRenderer.invoke('housekeeping:listChecklistItems', tacheId),
    updateChecklistItem: (itemId: number, input: unknown) => ipcRenderer.invoke('housekeeping:updateChecklistItem', itemId, input),
    stats: (hotelId: number) => ipcRenderer.invoke('housekeeping:stats', hotelId),
    syncFromChambres: (hotelId: number) => ipcRenderer.invoke('housekeeping:syncFromChambres', hotelId),
    chambresMenageSansTache: (hotelId: number) => ipcRenderer.invoke('housekeeping:chambresMenageSansTache', hotelId),
  },
  commercial: {
    listPartenaires: () => ipcRenderer.invoke('commercial:listPartenaires'),
    createPartenaire: (input: unknown) => ipcRenderer.invoke('commercial:createPartenaire', input),
    listOpportunites: (hotelId?: number, statut?: string) => ipcRenderer.invoke('commercial:listOpportunites', hotelId, statut),
    createOpportunite: (input: unknown) => ipcRenderer.invoke('commercial:createOpportunite', input),
    updateOpportunite: (id: number, input: unknown) => ipcRenderer.invoke('commercial:updateOpportunite', id, input),
    stats: (hotelId?: number) => ipcRenderer.invoke('commercial:stats', hotelId),
  },
  ged: {
    listVersions: (id) => ipcRenderer.invoke('ged:versions:list', id),
    addVersion: (id, note) => ipcRenderer.invoke('ged:versions:add', id, note),
    requestOcr: (id, langue) => ipcRenderer.invoke('ged:ocr:request', id, langue),
    completeOcr: (id, texte, confidence) => ipcRenderer.invoke('ged:ocr:complete', id, texte, confidence),
    searchOcr: (query) => ipcRenderer.invoke('ged:ocr:search', query),
    listSignatures: (id) => ipcRenderer.invoke('ged:signatures:list', id),
    sign: (id, motif) => ipcRenderer.invoke('ged:signatures:add', id, motif),
    listCategories: () => ipcRenderer.invoke('ged:listCategories'),
    listDocuments: (hotelId?: number, categorieId?: number, search?: string) => ipcRenderer.invoke('ged:listDocuments', hotelId, categorieId, search),
    upload: (input: unknown) => ipcRenderer.invoke('ged:upload', input),
    archiver: (id: number) => ipcRenderer.invoke('ged:archiver', id),
    delete: (id: number, motif?: string) => ipcRenderer.invoke('ged:delete', id, motif),
    ouvrir: (id: number) => ipcRenderer.invoke('ged:ouvrir', id),
  },
  workflow: {
    create: (input) => ipcRenderer.invoke('workflow:create', input),
    submit: (workflowId, commentaire) => ipcRenderer.invoke('workflow:submit', workflowId, commentaire),
    approve: (workflowId, statut, commentaire) => ipcRenderer.invoke('workflow:approve', workflowId, statut, commentaire),
    reject: (workflowId, motif) => ipcRenderer.invoke('workflow:reject', workflowId, motif),
    history: (workflowId) => ipcRenderer.invoke('workflow:history', workflowId),
    listPending: (filters) => ipcRenderer.invoke('workflow:listPending', filters),
    listPendingWithContext: (filters) => ipcRenderer.invoke('workflow:listPendingWithContext', filters),
    find: (module, entityType, entityId) => ipcRenderer.invoke('workflow:find', module, entityType, entityId),
  },
  workflowProcedures: {
    list: () => ipcRenderer.invoke('workflowProcedures:list'),
    update: (code, input) => ipcRenderer.invoke('workflowProcedures:update', code, input),
    updateStep: (stepId, input) => ipcRenderer.invoke('workflowProcedures:updateStep', stepId, input),
  },
  cloture: {
    create: (hotelId, dateJournal) => ipcRenderer.invoke('cloture:create', hotelId, dateJournal),
    prefill: (closureId) => ipcRenderer.invoke('cloture:prefill', closureId),
    submit: (closureId) => ipcRenderer.invoke('cloture:submit', closureId),
    validateUnit: (closureId) => ipcRenderer.invoke('cloture:validateUnit', closureId),
    validateDec: (closureId) => ipcRenderer.invoke('cloture:validateDec', closureId),
    reject: (closureId, motif) => ipcRenderer.invoke('cloture:reject', closureId, motif),
    close: (closureId) => ipcRenderer.invoke('cloture:close', closureId),
    list: (hotelId, dateDebut, dateFin) => ipcRenderer.invoke('cloture:list', hotelId, dateDebut, dateFin),
    getPosStatus: (hotelId, dateJournal) => ipcRenderer.invoke('cloture:posStatus', hotelId, dateJournal),
    getBusinessDate: (hotelId) => ipcRenderer.invoke('cloture:nightAudit:businessDate', hotelId),
    getNightAudit: (closureId) => ipcRenderer.invoke('cloture:nightAudit:get', closureId),
    runNightAudit: (closureId) => ipcRenderer.invoke('cloture:nightAudit:run', closureId),
    reopenNightAudit: (closureId, motif) => ipcRenderer.invoke('cloture:nightAudit:reopen', closureId, motif),
  },
  reconciliation: {
    create: (hotelId, dateJournal) => ipcRenderer.invoke('reconciliation:create', hotelId, dateJournal),
    prefill: (id) => ipcRenderer.invoke('reconciliation:prefill', id),
    justify: (id, justification) => ipcRenderer.invoke('reconciliation:justify', id, justification),
    validate: (id) => ipcRenderer.invoke('reconciliation:validate', id),
    list: (hotelId, dateDebut, dateFin) => ipcRenderer.invoke('reconciliation:list', hotelId, dateDebut, dateFin),
  },
  creances: {
    list: (filters) => ipcRenderer.invoke('creances:list', filters),
    fromFacture: (factureId) => ipcRenderer.invoke('creances:fromFacture', factureId),
    relance: (creanceId, input) => ipcRenderer.invoke('creances:relance', creanceId, input),
    balanceAgee: (hotelId) => ipcRenderer.invoke('creances:balanceAgee', hotelId),
    updateStatut: (creanceId, statut) => ipcRenderer.invoke('creances:updateStatut', creanceId, statut),
    paiement: (creanceId, montant) => ipcRenderer.invoke('creances:paiement', creanceId, montant),
    runRelancesAuto: () => ipcRenderer.invoke('creances:runRelancesAuto'),
    getRelancesAuto: () => ipcRenderer.invoke('creances:getRelancesAuto'),
    setRelancesAuto: (actif) => ipcRenderer.invoke('creances:setRelancesAuto', actif),
  },
  contratsHotel: {
    list: (hotelId) => ipcRenderer.invoke('contratsHotel:list', hotelId),
    get: (id) => ipcRenderer.invoke('contratsHotel:get', id),
    create: (input) => ipcRenderer.invoke('contratsHotel:create', input),
    update: (id, input) => ipcRenderer.invoke('contratsHotel:update', id, input),
    echeances: (jours) => ipcRenderer.invoke('contratsHotel:echeances', jours),
  },
  decCockpit: {
    get: (hotelId) => ipcRenderer.invoke('dec:cockpit:get', hotelId),
    listAlerts: (statut) => ipcRenderer.invoke('dec:alerts:list', statut),
    closeAlert: (alertId) => ipcRenderer.invoke('dec:alerts:close', alertId),
  },
  dashboardPdg: {
    get: () => ipcRenderer.invoke('dashboard:pdg:get'),
    exportCsv: () => ipcRenderer.invoke('dashboard:pdg:exportCsv'),
    exportMensuel: (periode) => ipcRenderer.invoke('dashboard:pdg:exportMensuel', periode),
  },
  systemHealth: {
    get: () => ipcRenderer.invoke('systemHealth:get'),
    gedIntegrity: (limit) => ipcRenderer.invoke('systemHealth:gedIntegrity', limit),
  },
  license: {
    getStatus: () => ipcRenderer.invoke('license:getStatus'),
    getMachineId: () => ipcRenderer.invoke('license:getMachineId'),
    getConfig: () => ipcRenderer.invoke('license:getConfig'),
    updateConfig: (input) => ipcRenderer.invoke('license:updateConfig', input),
    activate: (key) => ipcRenderer.invoke('license:activate', key),
    syncRemote: () => ipcRenderer.invoke('license:syncRemote'),
    clear: () => ipcRenderer.invoke('license:clear'),
    getPack: () => ipcRenderer.invoke('license:getPack'),
  },
  notifications: {
    list: (unreadOnly?: boolean, limit?: number) => ipcRenderer.invoke('notifications:list', unreadOnly, limit),
    countUnread: () => ipcRenderer.invoke('notifications:countUnread'),
    markRead: (id) => ipcRenderer.invoke('notifications:markRead', id),
    markAllRead: () => ipcRenderer.invoke('notifications:markAllRead'),
    getRules: () => ipcRenderer.invoke('notifications:getRules'),
    updateRule: (input) => ipcRenderer.invoke('notifications:updateRule', input),
    generateSystem: () => ipcRenderer.invoke('notifications:generateSystem'),
  },
  rgpd: {
    dashboard: () => ipcRenderer.invoke('rgpd:dashboard'),
    listTraitements: (actifOnly) => ipcRenderer.invoke('rgpd:traitements:list', actifOnly),
    upsertTraitement: (input) => ipcRenderer.invoke('rgpd:traitements:upsert', input),
    exportTraitementsCsv: () => ipcRenderer.invoke('rgpd:traitements:exportCsv'),
    listConsentements: (statut) => ipcRenderer.invoke('rgpd:consentements:list', statut),
    createConsentement: (input) => ipcRenderer.invoke('rgpd:consentements:create', input),
    revokeConsentement: (id, dateRetrait) => ipcRenderer.invoke('rgpd:consentements:revoke', id, dateRetrait),
    listDemandes: (statut) => ipcRenderer.invoke('rgpd:demandes:list', statut),
    createDemande: (input) => ipcRenderer.invoke('rgpd:demandes:create', input),
    updateDemande: (id, statut, reponse) => ipcRenderer.invoke('rgpd:demandes:update', id, statut, reponse),
    listIncidents: (statut) => ipcRenderer.invoke('rgpd:incidents:list', statut),
    createIncident: (input) => ipcRenderer.invoke('rgpd:incidents:create', input),
    updateIncident: (id, input) => ipcRenderer.invoke('rgpd:incidents:update', id, input),
    listConservation: () => ipcRenderer.invoke('rgpd:conservation:list'),
  },
  checklist: {
    templates: () => ipcRenderer.invoke('checklist:templates'),
    start: (templateId, hotelId) => ipcRenderer.invoke('checklist:start', templateId, hotelId),
    get: (runId) => ipcRenderer.invoke('checklist:get', runId),
    updateResult: (runId, itemId, input) => ipcRenderer.invoke('checklist:updateResult', runId, itemId, input),
    submit: (runId) => ipcRenderer.invoke('checklist:submit', runId),
    list: (hotelId) => ipcRenderer.invoke('checklist:list', hotelId),
    stats: (hotelId) => ipcRenderer.invoke('checklist:stats', hotelId),
  },
  hotelLegal: {
    listFichesPolice: (hotelId, statut) => ipcRenderer.invoke('hotelLegal:fichePolice:list', hotelId, statut),
    createFichePolice: (input) => ipcRenderer.invoke('hotelLegal:fichePolice:create', input),
    updateFichePolice: (ficheId, input) => ipcRenderer.invoke('hotelLegal:fichePolice:update', ficheId, input),
    checkoutFichePolice: (ficheId, dateSortie) => ipcRenderer.invoke('hotelLegal:fichePolice:checkout', ficheId, dateSortie),
    calculerTaxeSejour: (hotelId, periode, taux) => ipcRenderer.invoke('hotelLegal:taxeSejour:calculer', hotelId, periode, taux),
    genererRapportTourisme: (hotelId, periode) => ipcRenderer.invoke('hotelLegal:tourisme:generer', hotelId, periode),
    listRapportsTourisme: (hotelId) => ipcRenderer.invoke('hotelLegal:tourisme:list', hotelId),
    exportFichesPoliceCsv: (hotelId) => ipcRenderer.invoke('hotelLegal:fichePolice:exportCsv', hotelId),
  },
  gedArchivage: {
    listRetentionPolicies: () => ipcRenderer.invoke('ged:retention:list'),
    archiveLegally: (documentId, politiqueCode) => ipcRenderer.invoke('ged:legal:archive', documentId, politiqueCode),
    listLegalArchives: () => ipcRenderer.invoke('ged:legal:list'),
    verifyIntegrity: (archiveId) => ipcRenderer.invoke('ged:legal:verify', archiveId),
  },
  reports: {
    overview: () => ipcRenderer.invoke('reports:overview'),
    semanticCatalog: () => ipcRenderer.invoke('reports:semanticCatalog'),
    compatibleFields: (dimensions: string[], measures: string[]) =>
      ipcRenderer.invoke('reports:compatibleFields', dimensions, measures),
    previewComposed: (composition: unknown, filters?: unknown) =>
      ipcRenderer.invoke('reports:previewComposed', composition, filters),
    exportComposed: (composition: unknown, filters?: unknown, name?: string) =>
      ipcRenderer.invoke('reports:exportComposed', composition, filters, name),
    catalog: () => ipcRenderer.invoke('reports:catalog'),
    listSources: () => ipcRenderer.invoke('reports:listSources'),
    listTemplates: () => ipcRenderer.invoke('reports:listTemplates'),
    getTemplate: (id: number) => ipcRenderer.invoke('reports:getTemplate', id),
    createTemplate: (input: unknown) => ipcRenderer.invoke('reports:createTemplate', input),
    updateTemplate: (id: number, input: unknown) => ipcRenderer.invoke('reports:updateTemplate', id, input),
    duplicateTemplate: (id: number, newName?: string) => ipcRenderer.invoke('reports:duplicateTemplate', id, newName),
    deleteTemplate: (id: number) => ipcRenderer.invoke('reports:deleteTemplate', id),
    preview: (dataSource: string, columns: string[], filters?: unknown) =>
      ipcRenderer.invoke('reports:preview', dataSource, columns, filters),
    previewKpi: (kpiId: string, filters?: unknown) => ipcRenderer.invoke('reports:previewKpi', kpiId, filters),
    exportTemplate: (templateId: number) => ipcRenderer.invoke('reports:exportTemplate', templateId),
    exportAdHoc: (dataSource: string, columns: string[], filters?: unknown, name?: string) =>
      ipcRenderer.invoke('reports:exportAdHoc', dataSource, columns, filters, name),
    exportKpi: (kpiId: string, filters?: unknown) => ipcRenderer.invoke('reports:exportKpi', kpiId, filters),
    listRuns: (limit?: number) => ipcRenderer.invoke('reports:listRuns', limit),
  },
  guide: {
    list: () => ipcRenderer.invoke('guide:list'),
    get: (slug: string) => ipcRenderer.invoke('guide:get', slug),
    search: (query: string) => ipcRenderer.invoke('guide:search', query),
    sections: () => ipcRenderer.invoke('guide:sections'),
    suggested: () => ipcRenderer.invoke('guide:suggested'),
    roleProfiles: () => ipcRenderer.invoke('guide:roleProfiles'),
  },
};

contextBridge.exposeInMainWorld('electronAPI', api);
