import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ipcClient } from '@/lib/ipcClient';
import { unwrapIpc } from '@/lib/ipcHelpers';
import { notify } from '@/lib/toast';
import { useHotelsList } from '@/hooks/useHotelsList';
import { formatMoney } from '@/lib/formatters';
import type { ChannelConnector, PmsAttente, PmsDepot, PmsGroupe, PmsPolitiqueAnnulation } from '@/shared/types/hebergement';

const today=()=>new Date().toISOString().slice(0,10);
const later=(days:number)=>{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10);};

export function PmsOperationsPage(){
  const qc=useQueryClient();const {hotels,defaultHotelId}=useHotelsList();const [hotelId,setHotelId]=useState(defaultHotelId||0);
  const [group,setGroup]=useState({nom:'',dateArrivee:today(),dateDepart:later(1),allotement:1});
  const [depot,setDepot]=useState({reservationId:0,montant:0,mode:'carte',reference:'',dateDepot:today()});
  const [channel,setChannel]=useState({code:'booking',label:'Booking.com',endpointUrl:'',actif:true});
  const [booking,setBooking]=useState<{actif:boolean;domaine:string;acompteType:'pourcentage'|'montant'|'aucun';acompteValeur:number;paiementProvider:string;emailConfirmation:boolean;smsConfirmation:boolean}>({actif:true,domaine:'',acompteType:'pourcentage',acompteValeur:30,paiementProvider:'satim',emailConfirmation:true,smsConfirmation:false});
  const [wait,setWait]=useState({clientNom:'',clientPrenom:'',clientEmail:'',clientTelephone:'',dateArrivee:today(),dateDepart:later(1),nbAdultes:1,nbEnfants:0,priorite:3,notes:''});
  const [policy,setPolicy]=useState({nom:'Flexible',delaiSansFraisJours:2,penaliteType:'pourcentage' as const,penaliteValeur:50,noShowType:'pourcentage' as const,noShowValeur:100});
  const field='w-full rounded-lg border bg-background px-3 py-2 text-sm';
  const refresh=(key:string)=>void qc.invalidateQueries({queryKey:[key]});

  const groups=useQuery({queryKey:['pms-groupes',hotelId],queryFn:async()=>unwrapIpc(await ipcClient.hebergement.listGroupes(hotelId)) as PmsGroupe[],enabled:hotelId>0});
  const deposits=useQuery({queryKey:['pms-depots'],queryFn:async()=>unwrapIpc(await ipcClient.hebergement.listDepots()) as PmsDepot[]});
  const channels=useQuery({queryKey:['pms-channels'],queryFn:async()=>unwrapIpc(await ipcClient.hebergement.listChannelConnectors()) as ChannelConnector[]});
  const waitlist=useQuery({queryKey:['pms-waitlist',hotelId],queryFn:async()=>unwrapIpc(await ipcClient.hebergement.listWaitlist(hotelId)) as PmsAttente[],enabled:hotelId>0});
  const policies=useQuery({queryKey:['pms-policies',hotelId],queryFn:async()=>unwrapIpc(await ipcClient.hebergement.listCancellationPolicies(hotelId)) as PmsPolitiqueAnnulation[],enabled:hotelId>0});
  const distribution=useQuery({queryKey:['distribution-dashboard',hotelId],queryFn:async()=>unwrapIpc(await ipcClient.hebergement.getDistributionDashboard(hotelId)) as {connectors:number;actifs:number;jobsAttente:number;jobsEchec:number;commandesWeb:number;confirmeesWeb:number;caWeb:number},enabled:hotelId>0});

  const createGroup=useMutation({mutationFn:async()=>unwrapIpc(await ipcClient.hebergement.createGroupe({hotelId,...group})),onSuccess:()=>{refresh('pms-groupes');setGroup({...group,nom:''});notify.success('Dossier groupe créé');},onError:(e)=>notify.error(e instanceof Error?e.message:'Création impossible')});
  const createDeposit=useMutation({mutationFn:async()=>unwrapIpc(await ipcClient.hebergement.createDepot(depot)),onSuccess:()=>{refresh('pms-depots');notify.success('Dépôt enregistré');},onError:(e)=>notify.error(e instanceof Error?e.message:'Dépôt impossible')});
  const saveChannel=useMutation({mutationFn:async()=>unwrapIpc(await ipcClient.hebergement.saveChannelConnector({hotelId,...channel})),onSuccess:()=>{refresh('pms-channels');notify.success('Connecteur enregistré');},onError:(e)=>notify.error(e instanceof Error?e.message:'Connecteur invalide')});
  const saveBooking=useMutation({mutationFn:async()=>unwrapIpc(await ipcClient.hebergement.saveBookingEngineConfig({hotelId,...booking})),onSuccess:()=>{refresh('distribution-dashboard');notify.success('Booking Engine configuré');},onError:(e)=>notify.error(e instanceof Error?e.message:'Configuration impossible')});
  const createWait=useMutation({mutationFn:async()=>unwrapIpc(await ipcClient.hebergement.createWaitlist({hotelId,...wait})),onSuccess:()=>{refresh('pms-waitlist');setWait({...wait,clientNom:'',clientPrenom:'',clientEmail:'',clientTelephone:'',notes:''});notify.success("Client ajouté à la liste d'attente");},onError:e=>notify.error(e instanceof Error?e.message:'Ajout impossible')});
  const createPolicy=useMutation({mutationFn:async()=>unwrapIpc(await ipcClient.hebergement.createCancellationPolicy({hotelId,...policy})),onSuccess:()=>{refresh('pms-policies');notify.success("Politique d'annulation créée");},onError:e=>notify.error(e instanceof Error?e.message:'Création impossible')});

  const operateDeposit=async(d:PmsDepot,type:'remboursement'|'annulation')=>{const motif=prompt(type==='remboursement'?'Motif du remboursement :':"Motif de l'annulation de l'acompte :");if(!motif)return;try{unwrapIpc(await ipcClient.hebergement.operateDeposit(d.id,{type,motif}));refresh('pms-depots');notify.success(type==='remboursement'?'Acompte remboursé':'Acompte annulé');}catch(e){notify.error(e instanceof Error?e.message:'Opération impossible');}};
  const setWaitStatus=async(id:number,statut:PmsAttente['statut'])=>{try{unwrapIpc(await ipcClient.hebergement.updateWaitlistStatus(id,statut));refresh('pms-waitlist');}catch(e){notify.error(e instanceof Error?e.message:'Opération impossible');}};
  const promote=async(w:PmsAttente)=>{const raw=prompt('N° interne de la chambre à affecter :');if(!raw)return;try{unwrapIpc(await ipcClient.hebergement.promoteWaitlist(w.id,{chambreId:Number(raw)}));refresh('pms-waitlist');notify.success('Liste d’attente convertie en réservation');}catch(e){notify.error(e instanceof Error?e.message:'Conversion impossible');}};

  return <div className="space-y-5"><header><h2 className="text-xl font-semibold">Opérations PMS avancées</h2><p className="text-sm text-muted-foreground">Groupes, acomptes, attente, annulations et distribution.</p></header>
    <select className="max-w-md rounded-lg border bg-background px-3 py-2 text-sm" value={hotelId||''} onChange={e=>setHotelId(Number(e.target.value))}><option value="">Sélectionner un hôtel</option>{hotels.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="space-y-3 rounded-xl border bg-card p-4"><h3 className="font-semibold">Liste d’attente</h3><div className="grid grid-cols-2 gap-2"><input className={field} placeholder="Nom client *" value={wait.clientNom} onChange={e=>setWait({...wait,clientNom:e.target.value})}/><input className={field} placeholder="Prénom" value={wait.clientPrenom} onChange={e=>setWait({...wait,clientPrenom:e.target.value})}/><input type="date" className={field} value={wait.dateArrivee} onChange={e=>setWait({...wait,dateArrivee:e.target.value})}/><input type="date" className={field} value={wait.dateDepart} onChange={e=>setWait({...wait,dateDepart:e.target.value})}/><input type="number" min="1" max="5" className={field} aria-label="Priorité" value={wait.priorite} onChange={e=>setWait({...wait,priorite:Number(e.target.value)})}/><input className={field} placeholder="Téléphone" value={wait.clientTelephone} onChange={e=>setWait({...wait,clientTelephone:e.target.value})}/></div><button disabled={!hotelId||!wait.clientNom||createWait.isPending} className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-50" onClick={()=>createWait.mutate()}>Ajouter à l’attente</button><div className="max-h-64 space-y-2 overflow-y-auto">{waitlist.data?.map(w=><div key={w.id} className="rounded-lg border p-2 text-sm"><strong>{w.clientNom} {w.clientPrenom??''}</strong><div className="text-muted-foreground">{w.dateArrivee} → {w.dateDepart} · priorité {w.priorite} · {w.statut}</div>{['attente','contacte'].includes(w.statut)&&<div className="mt-2 flex gap-2"><button className="text-xs text-primary" onClick={()=>void setWaitStatus(w.id,'contacte')}>Marquer contacté</button><button className="text-xs text-emerald-700" onClick={()=>void promote(w)}>Convertir</button><button className="text-xs text-destructive" onClick={()=>void setWaitStatus(w.id,'annulee')}>Annuler</button></div>}</div>)}</div></section>

      <section className="space-y-3 rounded-xl border bg-card p-4"><h3 className="font-semibold">Politiques d’annulation</h3><input className={field} placeholder="Nom de la politique" value={policy.nom} onChange={e=>setPolicy({...policy,nom:e.target.value})}/><div className="grid grid-cols-2 gap-2"><label className="text-xs">Délai sans frais (jours)<input type="number" min="0" className={field} value={policy.delaiSansFraisJours} onChange={e=>setPolicy({...policy,delaiSansFraisJours:Number(e.target.value)})}/></label><label className="text-xs">Pénalité (%)<input type="number" min="0" className={field} value={policy.penaliteValeur} onChange={e=>setPolicy({...policy,penaliteValeur:Number(e.target.value)})}/></label><label className="text-xs">No-show (%)<input type="number" min="0" className={field} value={policy.noShowValeur} onChange={e=>setPolicy({...policy,noShowValeur:Number(e.target.value)})}/></label></div><button disabled={!hotelId||!policy.nom||createPolicy.isPending} className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-50" onClick={()=>createPolicy.mutate()}>Créer la politique</button>{policies.data?.map(p=><div key={p.id} className="rounded-lg border p-2 text-sm"><strong>{p.nom}</strong><div className="text-muted-foreground">Sans frais jusqu’à J-{p.delaiSansFraisJours} · pénalité {p.penaliteValeur}% · no-show {p.noShowValeur}%</div></div>)}</section>

      <section className="space-y-3 rounded-xl border bg-card p-4"><h3 className="font-semibold">Dépôts et acomptes</h3><div className="grid grid-cols-2 gap-2"><input aria-label="Réservation" type="number" min="1" className={field} placeholder="N° réservation" value={depot.reservationId||''} onChange={e=>setDepot({...depot,reservationId:Number(e.target.value)})}/><input aria-label="Montant" type="number" min="0.01" className={field} placeholder="Montant" value={depot.montant||''} onChange={e=>setDepot({...depot,montant:Number(e.target.value)})}/><select className={field} value={depot.mode} onChange={e=>setDepot({...depot,mode:e.target.value})}><option value="carte">Carte</option><option value="especes">Espèces</option><option value="virement">Virement</option><option value="cheque">Chèque</option></select><input className={field} placeholder="Référence" value={depot.reference} onChange={e=>setDepot({...depot,reference:e.target.value})}/></div><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-50" disabled={!depot.reservationId||depot.montant<=0} onClick={()=>createDeposit.mutate()}>Enregistrer le dépôt</button>{deposits.data?.slice(0,10).map(d=><div key={d.id} className="rounded-lg border p-2 text-sm"><strong>Réservation #{d.reservationId} · {formatMoney(d.montant)}</strong><div className="text-muted-foreground">{d.clientNom} · {d.mode} · {d.statut}</div>{['recu','affecte'].includes(d.statut)&&<div className="mt-2 flex gap-3"><button className="text-xs text-amber-700" onClick={()=>void operateDeposit(d,'remboursement')}>Rembourser</button><button className="text-xs text-destructive" onClick={()=>void operateDeposit(d,'annulation')}>Annuler l’acompte</button></div>}</div>)}</section>

      <section className="space-y-3 rounded-xl border bg-card p-4"><h3 className="font-semibold">Réservations groupes</h3><input className={field} placeholder="Nom du groupe" value={group.nom} onChange={e=>setGroup({...group,nom:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input aria-label="Arrivée groupe" type="date" className={field} value={group.dateArrivee} onChange={e=>setGroup({...group,dateArrivee:e.target.value})}/><input aria-label="Départ groupe" type="date" className={field} value={group.dateDepart} onChange={e=>setGroup({...group,dateDepart:e.target.value})}/></div><input aria-label="Allotement" type="number" min="1" className={field} value={group.allotement} onChange={e=>setGroup({...group,allotement:Number(e.target.value)})}/><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-50" disabled={!hotelId||!group.nom||!group.dateDepart} onClick={()=>createGroup.mutate()}>Créer le groupe</button>{groups.data?.map(g=><div key={g.id} className="rounded-lg border p-2 text-sm"><strong>{g.code} · {g.nom}</strong><div className="text-muted-foreground">{g.dateArrivee} → {g.dateDepart} · {g.reservationsCount}/{g.allotement}</div></div>)}</section>

      <section className="space-y-3 rounded-xl border bg-card p-4 xl:col-span-2"><h3 className="font-semibold">Channel Manager temps réel</h3><div className="grid gap-2 md:grid-cols-3"><input className={field} placeholder="Code canal" value={channel.code} onChange={e=>setChannel({...channel,code:e.target.value})}/><input className={field} placeholder="Libellé" value={channel.label} onChange={e=>setChannel({...channel,label:e.target.value})}/><input className={field} placeholder="URL API du connecteur" value={channel.endpointUrl} onChange={e=>setChannel({...channel,endpointUrl:e.target.value})}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={channel.actif} onChange={e=>setChannel({...channel,actif:e.target.checked})}/>Connecteur actif</label><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-50" disabled={!hotelId||!channel.code||!channel.label} onClick={()=>saveChannel.mutate()}>Enregistrer</button><div className="grid gap-2 md:grid-cols-2">{channels.data?.map(c=><div key={c.id} className="rounded-lg border p-3 text-sm"><strong>{c.label}</strong><div className="text-muted-foreground">{c.hotelName} · {c.statut} · {c.lastSyncAt??'jamais synchronisé'}</div><button className="mt-2 text-xs text-primary" onClick={()=>void ipcClient.hebergement.queueChannelSync(c.id,today(),later(365)).then(()=>{refresh('distribution-dashboard');notify.success('Disponibilités, tarifs et restrictions mis en file');})}>Synchroniser 365 jours</button></div>)}</div><p className="text-xs text-muted-foreground">Files idempotentes, retries exponentiels, journal HTTP, mappings chambre/tarif et webhooks signés sont actifs côté connecteur.</p></section>

      <section className="space-y-3 rounded-xl border bg-card p-4 xl:col-span-2"><h3 className="font-semibold">Booking Engine — vente directe</h3><div className="grid gap-2 md:grid-cols-3"><input className={field} placeholder="Domaine public" value={booking.domaine} onChange={e=>setBooking({...booking,domaine:e.target.value})}/><select className={field} value={booking.acompteType} onChange={e=>setBooking({...booking,acompteType:e.target.value as 'pourcentage'|'montant'|'aucun'})}><option value="pourcentage">Acompte en %</option><option value="montant">Acompte fixe</option><option value="aucun">Sans acompte</option></select><input type="number" className={field} value={booking.acompteValeur} onChange={e=>setBooking({...booking,acompteValeur:Number(e.target.value)})}/></div><div className="flex flex-wrap gap-4 text-sm"><label><input type="checkbox" checked={booking.actif} onChange={e=>setBooking({...booking,actif:e.target.checked})}/> Actif</label><label><input type="checkbox" checked={booking.emailConfirmation} onChange={e=>setBooking({...booking,emailConfirmation:e.target.checked})}/> Confirmation e-mail</label><label><input type="checkbox" checked={booking.smsConfirmation} onChange={e=>setBooking({...booking,smsConfirmation:e.target.checked})}/> Confirmation SMS</label></div><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground" disabled={!hotelId} onClick={()=>saveBooking.mutate()}>Enregistrer le moteur direct</button><div className="grid grid-cols-2 gap-2 md:grid-cols-6">{[['Connecteurs',distribution.data?.connectors],['Actifs',distribution.data?.actifs],['Sync attente',distribution.data?.jobsAttente],['Sync échec',distribution.data?.jobsEchec],['Web confirmées',distribution.data?.confirmeesWeb],['CA direct',distribution.data?formatMoney(distribution.data.caWeb):'—']].map(([l,v])=><div key={String(l)} className="rounded-lg border p-2"><p className="text-xs text-muted-foreground">{l}</p><strong>{v??0}</strong></div>)}</div><p className="text-xs text-muted-foreground">Disponibilité PMS instantanée, restrictions de séjour, codes promo, paiement/acompte idempotent et confirmations en file d’envoi.</p></section>
    </div>
  </div>;
}
