import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ipcClient } from '@/lib/ipcClient';
import { unwrapIpc } from '@/lib/ipcHelpers';
import { notify } from '@/lib/toast';
import { useHotelsList } from '@/hooks/useHotelsList';
import { formatMoney } from '@/lib/formatters';
import type { ChannelConnector, PmsDepot, PmsGroupe } from '@/shared/types/hebergement';

const today=()=>new Date().toISOString().slice(0,10);
export function PmsOperationsPage(){
 const qc=useQueryClient(); const {hotels,defaultHotelId}=useHotelsList(); const [hotelId,setHotelId]=useState(defaultHotelId||0);
 const [group,setGroup]=useState({nom:'',dateArrivee:today(),dateDepart:'',allotement:1}); const [depot,setDepot]=useState({reservationId:0,montant:0,mode:'carte',reference:'',dateDepot:today()}); const [channel,setChannel]=useState({code:'booking',label:'Booking.com',endpointUrl:'',actif:true});
 const groups=useQuery({queryKey:['pms-groupes',hotelId],queryFn:async()=>unwrapIpc(await ipcClient.hebergement.listGroupes(hotelId)) as PmsGroupe[],enabled:hotelId>0});
 const deposits=useQuery({queryKey:['pms-depots'],queryFn:async()=>unwrapIpc(await ipcClient.hebergement.listDepots()) as PmsDepot[]});
 const channels=useQuery({queryKey:['pms-channels'],queryFn:async()=>unwrapIpc(await ipcClient.hebergement.listChannelConnectors()) as ChannelConnector[]});
 const createGroup=useMutation({mutationFn:async()=>unwrapIpc(await ipcClient.hebergement.createGroupe({hotelId,...group})),onSuccess:()=>{void qc.invalidateQueries({queryKey:['pms-groupes']});setGroup({...group,nom:''});notify.success('Dossier groupe créé');},onError:(e)=>notify.error(e instanceof Error?e.message:'Création impossible')});
 const createDeposit=useMutation({mutationFn:async()=>unwrapIpc(await ipcClient.hebergement.createDepot(depot)),onSuccess:()=>{void qc.invalidateQueries({queryKey:['pms-depots']});notify.success('Dépôt enregistré');},onError:(e)=>notify.error(e instanceof Error?e.message:'Dépôt impossible')});
 const saveChannel=useMutation({mutationFn:async()=>unwrapIpc(await ipcClient.hebergement.saveChannelConnector({hotelId,...channel})),onSuccess:()=>{void qc.invalidateQueries({queryKey:['pms-channels']});notify.success('Connecteur enregistré');},onError:(e)=>notify.error(e instanceof Error?e.message:'Connecteur invalide')});
 const field='rounded-lg border bg-background px-3 py-2 text-sm';
 return <div className="space-y-5"><header><h2 className="text-xl font-semibold">Opérations PMS</h2><p className="text-sm text-muted-foreground">Groupes, acomptes et distribution multicanale.</p></header>
 <select className={field} value={hotelId||''} onChange={e=>setHotelId(Number(e.target.value))}><option value="">Sélectionner un hôtel</option>{hotels.map(h=><option key={h.id} value={h.id}>{h.name}</option>)}</select>
 <div className="grid gap-5 xl:grid-cols-3">
  <section className="space-y-3 rounded-xl border bg-card p-4"><h3 className="font-semibold">Réservations groupes</h3><input className={field} placeholder="Nom du groupe" value={group.nom} onChange={e=>setGroup({...group,nom:e.target.value})}/><div className="flex gap-2"><input aria-label="Arrivée groupe" type="date" className={field} value={group.dateArrivee} onChange={e=>setGroup({...group,dateArrivee:e.target.value})}/><input aria-label="Départ groupe" type="date" className={field} value={group.dateDepart} onChange={e=>setGroup({...group,dateDepart:e.target.value})}/></div><input aria-label="Allotement" type="number" min="1" className={field} value={group.allotement} onChange={e=>setGroup({...group,allotement:Number(e.target.value)})}/><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-50" disabled={!hotelId||!group.nom||!group.dateDepart} onClick={()=>createGroup.mutate()}>Créer le groupe</button>{groups.data?.map(g=><div key={g.id} className="rounded-lg border p-2 text-sm"><strong>{g.code} · {g.nom}</strong><div className="text-muted-foreground">{g.dateArrivee} → {g.dateDepart} · {g.reservationsCount}/{g.allotement}</div></div>)}</section>
  <section className="space-y-3 rounded-xl border bg-card p-4"><h3 className="font-semibold">Dépôts et acomptes</h3><input aria-label="Réservation" type="number" min="1" className={field} placeholder="N° réservation" value={depot.reservationId||''} onChange={e=>setDepot({...depot,reservationId:Number(e.target.value)})}/><input aria-label="Montant" type="number" min="0.01" className={field} placeholder="Montant" value={depot.montant||''} onChange={e=>setDepot({...depot,montant:Number(e.target.value)})}/><select className={field} value={depot.mode} onChange={e=>setDepot({...depot,mode:e.target.value})}><option value="carte">Carte</option><option value="especes">Espèces</option><option value="virement">Virement</option><option value="cheque">Chèque</option></select><input className={field} placeholder="Référence" value={depot.reference} onChange={e=>setDepot({...depot,reference:e.target.value})}/><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-50" disabled={!depot.reservationId||depot.montant<=0} onClick={()=>createDeposit.mutate()}>Enregistrer le dépôt</button>{deposits.data?.slice(0,8).map(d=><div key={d.id} className="rounded-lg border p-2 text-sm"><strong>Réservation #{d.reservationId} · {formatMoney(d.montant)}</strong><div className="text-muted-foreground">{d.clientNom} · {d.mode} · {d.statut}</div></div>)}</section>
  <section className="space-y-3 rounded-xl border bg-card p-4"><h3 className="font-semibold">Channel manager</h3><input className={field} placeholder="Code canal" value={channel.code} onChange={e=>setChannel({...channel,code:e.target.value})}/><input className={field} placeholder="Libellé" value={channel.label} onChange={e=>setChannel({...channel,label:e.target.value})}/><input className={field} placeholder="URL du connecteur" value={channel.endpointUrl} onChange={e=>setChannel({...channel,endpointUrl:e.target.value})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={channel.actif} onChange={e=>setChannel({...channel,actif:e.target.checked})}/>Connecteur actif</label><button className="rounded-lg bg-primary px-3 py-2 text-sm text-primary-foreground disabled:opacity-50" disabled={!hotelId||!channel.code||!channel.label} onClick={()=>saveChannel.mutate()}>Enregistrer</button>{channels.data?.map(c=><div key={c.id} className="rounded-lg border p-2 text-sm"><strong>{c.label}</strong><div className="text-muted-foreground">{c.hotelName} · {c.statut} · {c.lastSyncAt??'jamais synchronisé'}</div></div>)}</section>
 </div></div>;
}
