import { useEffect, useState } from 'react';
import { BedDouble, ReceiptText, ShieldAlert, UserPlus, X } from 'lucide-react';
import { ipcClient } from '@/lib/ipcClient';
import { unwrapIpc } from '@/lib/ipcHelpers';
import { notify } from '@/lib/toast';
import type { Chambre, PmsOccupant, PmsPolitiqueAnnulation, Reservation, UpdateReservationInput } from '@/shared/types/hebergement';

type Folio = { id:number; statut:string; totalTtc:number; lignes:Array<{id:number;designation:string;montantTtc:number}> };

export function ReservationAdvancedModal({reservation,onClose,onSaved}:{reservation:Reservation;onClose:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState<UpdateReservationInput>({dateArrivee:reservation.dateArrivee,dateDepart:reservation.dateDepart,nbAdultes:reservation.nbAdultes,nbEnfants:reservation.nbEnfants,montantTotal:reservation.montantTotal,notes:reservation.notes,politiqueAnnulationId:reservation.politiqueAnnulationId});
  const [rooms,setRooms]=useState<Chambre[]>([]);const [occupants,setOccupants]=useState<PmsOccupant[]>([]);const [policies,setPolicies]=useState<PmsPolitiqueAnnulation[]>([]);const [folio,setFolio]=useState<Folio|null>(null);
  const [roomMove,setRoomMove]=useState({newRoomId:0,motif:'',surbookingAutorise:false});
  const [occupant,setOccupant]=useState({nom:'',prenom:'',dateNaissance:'',nationalite:'',typeDocument:'',numeroDocument:'',principal:false});
  const [cancel,setCancel]=useState({motif:'',policyId:reservation.politiqueAnnulationId??0});
  const [transfer,setTransfer]=useState({destinationReservationId:0,motif:'',lineIds:[] as number[]});
  const [shareReservationId,setShareReservationId]=useState(0);const [busy,setBusy]=useState(false);
  const field='w-full rounded-lg border bg-background px-3 py-2 text-sm';

  const reload=async()=>{
    const [r,o,p,f]=await Promise.all([ipcClient.hebergement.listChambres(reservation.hotelId),ipcClient.hebergement.listOccupants(reservation.id),ipcClient.hebergement.listCancellationPolicies(reservation.hotelId),ipcClient.hebergement.getFolio(reservation.id)]);
    setRooms(unwrapIpc(r));setOccupants(unwrapIpc(o));setPolicies(unwrapIpc(p));setFolio(unwrapIpc(f) as Folio|null);
  };
  useEffect(()=>{void reload().catch(e=>notify.error(e instanceof Error?e.message:'Chargement impossible'));},[reservation.id]);
  const run=async(fn:()=>Promise<unknown>,success:string)=>{setBusy(true);try{await fn();notify.success(success);await reload();onSaved();}catch(e){notify.error(e instanceof Error?e.message:'Opération impossible');}finally{setBusy(false);}};

  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4 backdrop-blur-sm"><div className="max-h-[94vh] w-full max-w-5xl overflow-y-auto rounded-2xl bg-white shadow-2xl">
    <header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-6 py-4"><div><h2 className="text-lg font-semibold">Réservation #{reservation.id} — {reservation.clientNom}</h2><p className="text-xs text-muted-foreground">Modification, occupants, chambre, annulation et folio</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-muted"><X className="h-5 w-5"/></button></header>
    <div className="grid gap-5 p-6 lg:grid-cols-2">
      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><ReceiptText className="h-4 w-4"/>Dossier de réservation</h3><div className="grid grid-cols-2 gap-3"><label className="text-xs">Arrivée<input type="date" className={field} value={form.dateArrivee??''} onChange={e=>setForm({...form,dateArrivee:e.target.value})}/></label><label className="text-xs">Départ<input type="date" className={field} value={form.dateDepart??''} onChange={e=>setForm({...form,dateDepart:e.target.value})}/></label><label className="text-xs">Adultes<input type="number" min="1" className={field} value={form.nbAdultes??1} onChange={e=>setForm({...form,nbAdultes:Number(e.target.value)})}/></label><label className="text-xs">Enfants<input type="number" min="0" className={field} value={form.nbEnfants??0} onChange={e=>setForm({...form,nbEnfants:Number(e.target.value)})}/></label><label className="text-xs">Montant total<input type="number" min="0" className={field} value={form.montantTotal??0} onChange={e=>setForm({...form,montantTotal:Number(e.target.value)})}/></label><label className="text-xs">Politique d’annulation<select className={field} value={form.politiqueAnnulationId??''} onChange={e=>setForm({...form,politiqueAnnulationId:e.target.value?Number(e.target.value):null})}><option value="">Aucune</option>{policies.map(p=><option key={p.id} value={p.id}>{p.nom}</option>)}</select></label></div><textarea className={field} rows={2} placeholder="Notes" value={form.notes??''} onChange={e=>setForm({...form,notes:e.target.value})}/><button disabled={busy} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50" onClick={()=>void run(async()=>unwrapIpc(await ipcClient.hebergement.updateReservation(reservation.id,form)),'Réservation modifiée')}>Enregistrer les modifications</button></section>

      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><BedDouble className="h-4 w-4"/>Déplacement de chambre</h3><p className="text-xs text-muted-foreground">Chambre actuelle : {reservation.chambreNumero??'non affectée'}</p><select className={field} value={roomMove.newRoomId||''} onChange={e=>setRoomMove({...roomMove,newRoomId:Number(e.target.value)})}><option value="">Nouvelle chambre</option>{rooms.filter(r=>r.id!==reservation.chambreId).map(r=><option key={r.id} value={r.id}>Ch. {r.numero} — {r.typeChambreLabel??'sans type'}</option>)}</select><input className={field} placeholder="Motif obligatoire" value={roomMove.motif} onChange={e=>setRoomMove({...roomMove,motif:e.target.value})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={roomMove.surbookingAutorise} onChange={e=>setRoomMove({...roomMove,surbookingAutorise:e.target.checked})}/>Autoriser exceptionnellement le surbooking</label><button disabled={busy||!roomMove.newRoomId||!roomMove.motif} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50" onClick={()=>void run(async()=>unwrapIpc(await ipcClient.hebergement.moveReservationRoom(reservation.id,roomMove)),'Chambre déplacée')}>Déplacer</button></section>

      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><UserPlus className="h-4 w-4"/>Occupants multiples</h3><div className="grid grid-cols-2 gap-2"><input className={field} placeholder="Nom *" value={occupant.nom} onChange={e=>setOccupant({...occupant,nom:e.target.value})}/><input className={field} placeholder="Prénom" value={occupant.prenom} onChange={e=>setOccupant({...occupant,prenom:e.target.value})}/><input type="date" className={field} aria-label="Date de naissance" value={occupant.dateNaissance} onChange={e=>setOccupant({...occupant,dateNaissance:e.target.value})}/><input className={field} placeholder="Nationalité" value={occupant.nationalite} onChange={e=>setOccupant({...occupant,nationalite:e.target.value})}/><input className={field} placeholder="Type document" value={occupant.typeDocument} onChange={e=>setOccupant({...occupant,typeDocument:e.target.value})}/><input className={field} placeholder="N° document" value={occupant.numeroDocument} onChange={e=>setOccupant({...occupant,numeroDocument:e.target.value})}/></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={occupant.principal} onChange={e=>setOccupant({...occupant,principal:e.target.checked})}/>Occupant principal</label><button disabled={busy||!occupant.nom} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50" onClick={()=>void run(async()=>{unwrapIpc(await ipcClient.hebergement.saveOccupant(reservation.id,{...occupant,prenom:occupant.prenom||null,dateNaissance:occupant.dateNaissance||null,nationalite:occupant.nationalite||null,typeDocument:occupant.typeDocument||null,numeroDocument:occupant.numeroDocument||null}));setOccupant({nom:'',prenom:'',dateNaissance:'',nationalite:'',typeDocument:'',numeroDocument:'',principal:false});},'Occupant ajouté')}>Ajouter</button><div className="space-y-1">{occupants.map(o=><div key={o.id} className="flex items-center justify-between rounded-lg bg-muted/50 px-3 py-2 text-sm"><span>{o.nom} {o.prenom??''}{o.principal?' · principal':''}</span><button className="text-xs text-destructive" onClick={()=>void run(async()=>unwrapIpc(await ipcClient.hebergement.deleteOccupant(o.id)),'Occupant supprimé')}>Supprimer</button></div>)}</div></section>

      <section className="space-y-3 rounded-xl border p-4"><h3 className="flex items-center gap-2 font-semibold"><ShieldAlert className="h-4 w-4"/>Annulation contrôlée</h3><select className={field} value={cancel.policyId||''} onChange={e=>setCancel({...cancel,policyId:Number(e.target.value)})}><option value="">Politique affectée au dossier</option>{policies.map(p=><option key={p.id} value={p.id}>{p.nom}</option>)}</select><textarea className={field} rows={2} placeholder="Motif obligatoire" value={cancel.motif} onChange={e=>setCancel({...cancel,motif:e.target.value})}/><button disabled={busy||!cancel.motif||reservation.statut==='annulee'} className="rounded-lg bg-destructive px-4 py-2 text-sm font-medium text-destructive-foreground disabled:opacity-50" onClick={()=>{if(confirm('Confirmer l’annulation de cette réservation ?'))void run(async()=>{const r=unwrapIpc(await ipcClient.hebergement.cancelReservation(reservation.id,{motif:cancel.motif,policyId:cancel.policyId||undefined}));notify.info(`Pénalité : ${r.montantPenalite.toLocaleString('fr-DZ')} DA · remboursable : ${r.montantRemboursable.toLocaleString('fr-DZ')} DA`);},'Réservation annulée');}}>Calculer et annuler</button></section>

      <section className="space-y-3 rounded-xl border p-4 lg:col-span-2"><h3 className="font-semibold">Partage et transfert de folio</h3>{folio?<><p className="text-sm">Folio #{folio.id} · {folio.statut} · {folio.totalTtc.toLocaleString('fr-DZ')} DA</p><div className="grid gap-2 md:grid-cols-2">{folio.lignes.map(l=><label key={l.id} className="flex items-center gap-2 rounded-lg border p-2 text-sm"><input type="checkbox" checked={transfer.lineIds.includes(l.id)} onChange={e=>setTransfer({...transfer,lineIds:e.target.checked?[...transfer.lineIds,l.id]:transfer.lineIds.filter(id=>id!==l.id)})}/>{l.designation} · {l.montantTtc.toLocaleString('fr-DZ')} DA</label>)}</div><div className="grid gap-2 md:grid-cols-3"><input type="number" min="1" className={field} placeholder="Réservation destination" value={transfer.destinationReservationId||''} onChange={e=>setTransfer({...transfer,destinationReservationId:Number(e.target.value)})}/><input className={field} placeholder="Motif du transfert" value={transfer.motif} onChange={e=>setTransfer({...transfer,motif:e.target.value})}/><button disabled={busy||!transfer.destinationReservationId||!transfer.motif||!transfer.lineIds.length} className="rounded-lg bg-primary px-4 py-2 text-sm text-primary-foreground disabled:opacity-50" onClick={()=>void run(async()=>unwrapIpc(await ipcClient.hebergement.transferFolioLines({sourceReservationId:reservation.id,...transfer})),'Lignes transférées')}>Transférer les lignes</button><input type="number" min="1" className={field} placeholder="Réservation à partager" value={shareReservationId||''} onChange={e=>setShareReservationId(Number(e.target.value))}/><button disabled={busy||!shareReservationId} className="rounded-lg border px-4 py-2 text-sm disabled:opacity-50" onClick={()=>void run(async()=>unwrapIpc(await ipcClient.hebergement.shareFolio({folioReservationId:reservation.id,sharedReservationId:shareReservationId})),'Folio partagé')}>Partager le folio</button></div></>:<button className="rounded-lg border px-4 py-2 text-sm" onClick={()=>void run(async()=>unwrapIpc(await ipcClient.hebergement.createFolio(reservation.id)),'Folio créé')}>Créer le folio</button>}</section>
    </div>
  </div></div>;
}
