import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { BarChart3, Gift, Mail, MessageSquareText, RefreshCw, ShieldCheck, Star, UserRoundSearch, UsersRound } from 'lucide-react';
import { ipcClient } from '@/lib/ipcClient';
import { unwrapIpc } from '@/lib/ipcHelpers';
import { notify } from '@/lib/toast';
import { useHotelsList } from '@/hooks/useHotelsList';

type Tab = 'clients' | 'segments' | 'campagnes' | 'fidelite' | 'nps' | 'reputation' | 'portail';
const tabs: Array<[Tab, string]> = [['clients','Vue client 360°'],['segments','Segments'],['campagnes','Campagnes'],['fidelite','Fidélité'],['nps','Enquêtes & NPS'],['reputation','Réputation'],['portail','Portail & pré-check-in']];
const field = 'rounded-lg border bg-background px-3 py-2 text-sm';
const button = 'rounded-lg bg-primary px-3 py-2 text-sm font-medium text-primary-foreground';

export default function CrmPage() {
  const qc = useQueryClient();
  const { operationalHotels, defaultHotelId } = useHotelsList();
  const [hotelId,setHotelId]=useState(0); const [tab,setTab]=useState<Tab>('clients'); const [clientId,setClientId]=useState(0);
  useEffect(()=>{if(!hotelId&&defaultHotelId)setHotelId(defaultHotelId);},[defaultHotelId,hotelId]);
  const dashboard=useQuery({queryKey:['crm-dashboard',hotelId],enabled:hotelId>0,queryFn:async()=>unwrapIpc(await ipcClient.clients.crmDashboard(hotelId))as any});
  const segments=useQuery({queryKey:['crm-segments'],queryFn:async()=>unwrapIpc(await ipcClient.clients.listCrmSegments())as any[]});
  const client=useQuery({queryKey:['crm-client360',clientId],enabled:clientId>0,queryFn:async()=>unwrapIpc(await ipcClient.clients.crmClient360(clientId))as any});
  const nps=useQuery({queryKey:['crm-nps',hotelId],enabled:hotelId>0,queryFn:async()=>unwrapIpc(await ipcClient.clients.crmNpsDashboard(hotelId))as any});
  const reviews=useQuery({queryKey:['crm-reviews',hotelId],enabled:hotelId>0,queryFn:async()=>unwrapIpc(await ipcClient.clients.listCrmReviews(hotelId))as any[]});
  const refresh=()=>void qc.invalidateQueries({queryKey:['crm']});
  const run=async(fn:()=>Promise<unknown>,message:string)=>{try{await fn();refresh();notify.success(message);}catch(e){notify.error(e instanceof Error?e.message:'Opération impossible');}};
  const createSegment=()=>run(async()=>{const nom=prompt('Nom du segment :');if(!nom)return;const code=prompt('Code :',nom.toUpperCase().replace(/\W+/g,'_'));if(!code)return;const minStays=Number(prompt('Nombre minimum de séjours :','1'));const minRevenue=Number(prompt('Chiffre d’affaires minimum (DA) :','0'));unwrapIpc(await ipcClient.clients.createCrmSegment({code,nom,criteres:{minStays,minRevenue}}));},'Segment créé et calculé');
  const createCampaign=()=>run(async()=>{const segmentId=Number(prompt('Identifiant du segment :',String(segments.data?.[0]?.id??'')));const nom=prompt('Nom de la campagne :');const contenu=prompt('Message :');if(!segmentId||!nom||!contenu)return;const created=unwrapIpc(await ipcClient.clients.createCrmCampaign({segmentId,nom,canal:'multicanal',contenu}))as any;const result=unwrapIpc(await ipcClient.clients.prepareCrmCampaign(created.id))as any;notify.success(`${result.queued} message(s) mis en file, ${result.skipped} ignoré(s)`);},'Campagne préparée');
  const addPoints=()=>run(async()=>{if(!clientId)throw new Error('Sélectionnez un client.');const points=Number(prompt('Points à ajouter :','100'));const motif=prompt('Motif :','Séjour')??'Séjour';unwrapIpc(await ipcClient.clients.moveLoyaltyPoints({clientId,type:'gain',points,motif}));},'Points ajoutés');
  const consent=()=>run(async()=>{if(!clientId)throw new Error('Sélectionnez un client.');const channel=(prompt('Canal : email, sms ou whatsapp','email')??'email')as 'email'|'sms'|'whatsapp';unwrapIpc(await ipcClient.clients.recordCrmConsent({clientId,finalite:`marketing_${channel}`,accorde:true,source:'accueil',preuve:'Consentement explicite enregistré par le personnel',versionNotice:'18-07-v1'}));},'Consentement enregistré');
  const invitePortal=()=>run(async()=>{if(!clientId)throw new Error('Sélectionnez un client.');const result=unwrapIpc(await ipcClient.clients.inviteCrmPortal(clientId))as any;await navigator.clipboard?.writeText(result.token);},'Invitation portail créée, jeton copié');
  const invitePrecheckin=()=>run(async()=>{const reservationId=Number(prompt('Identifiant de la réservation :'));if(!reservationId)return;const result=unwrapIpc(await ipcClient.clients.invitePrecheckin(reservationId))as any;await navigator.clipboard?.writeText(result.token);},'Pré-check-in créé, jeton copié');
  const createSurvey=()=>run(async()=>{const nom=prompt('Nom de l’enquête :','Satisfaction après séjour');if(!nom)return;unwrapIpc(await ipcClient.clients.createCrmSurvey({hotelId,nom,declencheur:'checkout',questions:[{id:'nps',type:'nps',label:'Nous recommanderiez-vous ?'},{id:'commentaire',type:'texte',label:'Votre commentaire'}]}));},'Enquête créée');
  const ingestReview=()=>run(async()=>{const auteur=prompt('Auteur de l’avis :');if(!auteur)return;const note=Number(prompt('Note sur 5 :','5'));const commentaire=prompt('Commentaire :')??'';unwrapIpc(await ipcClient.clients.ingestCrmReview({hotelId,source:'manuel',externalId:crypto.randomUUID(),auteur,note,commentaire}));},'Avis importé');

  const cards=[['Clients actifs',dashboard.data?.clients?.total??0,UsersRound],['Membres fidélité',dashboard.data?.loyalty?.membres??0,Gift],['Score NPS',dashboard.data?.nps?.score??0,BarChart3],['Avis sans réponse',dashboard.data?.reputation?.sans_reponse??0,Star]] as const;
  return <div className="space-y-5 p-6">
    <header className="flex flex-wrap items-center gap-3"><div><h1 className="text-2xl font-bold">CRM & expérience client</h1><p className="text-sm text-muted-foreground">Relation client 360°, fidélité, consentements et communications omnicanales</p></div><select className={`${field} ml-auto`}value={hotelId}onChange={e=>setHotelId(Number(e.target.value))}>{operationalHotels.map(h=><option key={h.id}value={h.id}>{h.name}</option>)}</select><button className="rounded-lg border p-2"onClick={refresh}><RefreshCw className="h-4 w-4"/></button></header>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value,Icon])=><div key={label}className="rounded-xl border bg-card p-4"><span className="flex items-center gap-2 text-xs text-muted-foreground"><Icon className="h-4 w-4"/>{label}</span><b className="mt-2 block text-3xl">{value}</b></div>)}</div>
    <nav className="flex flex-wrap gap-1 border-b">{tabs.map(([id,label])=><button key={id}onClick={()=>setTab(id)}className={`px-3 py-2 text-sm ${tab===id?'border-b-2 border-primary font-semibold text-primary':'text-muted-foreground'}`}>{label}</button>)}</nav>
    {tab==='clients'&&<section className="space-y-4"><div className="flex gap-2"><input className={field}type="number"placeholder="Identifiant client"value={clientId||''}onChange={e=>setClientId(Number(e.target.value))}/><button className={button}onClick={()=>void client.refetch()}><UserRoundSearch className="mr-1 inline h-4 w-4"/>Charger</button><button className="rounded-lg border px-3 text-sm"onClick={()=>void consent()}><ShieldCheck className="mr-1 inline h-4 w-4"/>Consentement</button></div>{client.data&&<div className="grid gap-4 lg:grid-cols-3"><Info title="Identité"><b>{client.data.client.prenom} {client.data.client.nom}</b><p>{client.data.client.email||'Sans e-mail'}</p><p>{client.data.client.mobile||client.data.client.telephone||'Sans téléphone'}</p><p>{client.data.client.vip?'Client VIP':'Client standard'}</p></Info><Info title="Valeur"><p>{client.data.totals.sejours} séjour(s)</p><p>{Number(client.data.totals.ca_pms).toLocaleString()} DA de CA PMS</p><p>Dernier séjour : {client.data.totals.dernier_sejour||'—'}</p></Info><Info title="Relation"><p>{client.data.messages.length} message(s)</p><p>{client.data.surveys.length} enquête(s)</p><p>{client.data.consents.filter((x:any)=>x.accorde).length} consentement(s) actif(s)</p></Info></div>}</section>}
    {tab==='segments'&&<section><button className={`${button} mb-3`}onClick={()=>void createSegment()}>Nouveau segment dynamique</button><div className="rounded-xl border bg-card">{segments.data?.map(s=><div key={s.id}className="flex items-center border-b p-3 text-sm"><div><b>{s.nom}</b><p className="text-xs text-muted-foreground">{s.code} · {s.membres} membre(s)</p></div><button className="ml-auto text-primary"onClick={()=>run(async()=>{unwrapIpc(await ipcClient.clients.recomputeCrmSegment(s.id));},'Segment recalculé')}>Recalculer</button></div>)}</div></section>}
    {tab==='campagnes'&&<section className="grid gap-4 lg:grid-cols-2"><Info title="Campagnes omnicanales"><p>La préparation respecte le dernier consentement par finalité et exclut les coordonnées absentes.</p><button className={`${button} mt-3`}onClick={()=>void createCampaign()}><Mail className="mr-1 inline h-4 w-4"/>Créer et préparer</button></Info><Info title="File d’envoi"><p>{dashboard.data?.messages?.total??0} message(s) · {dashboard.data?.messages?.envoyes??0} envoyé(s) · {dashboard.data?.messages?.echecs??0} échec(s)</p><p className="mt-2 text-xs text-muted-foreground">5 tentatives maximum avec délai exponentiel et clé d’idempotence par destinataire/canal.</p></Info></section>}
    {tab==='fidelite'&&<section className="grid gap-4 lg:grid-cols-2"><Info title="Compte fidélité"><p>Sélectionnez un client dans la vue 360°, puis adhérez-le ou créditez ses points.</p><div className="mt-3 flex gap-2"><button className={button}onClick={()=>run(async()=>{if(!clientId)throw new Error('Sélectionnez un client.');unwrapIpc(await ipcClient.clients.enrollLoyalty(clientId));},'Adhésion fidélité créée')}>Adhérer</button><button className="rounded-lg border px-3 text-sm"onClick={()=>void addPoints()}>Ajouter des points</button></div></Info><Info title="Niveaux automatiques"><p>Classic · Silver dès 1 500 · Gold dès 5 000 · Platinum dès 10 000 points à vie.</p><p className="mt-2 text-xs text-muted-foreground">Les utilisations et expirations refusent tout solde négatif.</p></Info></section>}
    {tab==='nps'&&<section className="space-y-4"><button className={button}onClick={()=>void createSurvey()}>Créer une enquête post-séjour</button><div className="grid gap-3 md:grid-cols-4">{[['Score',nps.data?.score??0],['Promoteurs',nps.data?.promoteurs??0],['Passifs',nps.data?.passifs??0],['Détracteurs',nps.data?.detracteurs??0]].map(([x,v])=><Info key={x as string}title={x as string}><b className="text-2xl">{v}</b></Info>)}</div></section>}
    {tab==='reputation'&&<section><button className={`${button} mb-3`}onClick={()=>void ingestReview()}>Importer un avis</button><div className="space-y-2">{reviews.data?.map(r=><article key={r.id}className="rounded-xl border bg-card p-4"><div className="flex justify-between"><b>{r.auteur} · {r.source}</b><span>{r.note}/5</span></div><p className="text-sm">{r.commentaire}</p>{r.reponse?<p className="mt-2 border-l-2 pl-2 text-xs text-muted-foreground">Réponse : {r.reponse}</p>:<button className="mt-2 text-sm text-primary"onClick={()=>{const response=prompt('Réponse publique :');if(response)void run(async()=>{unwrapIpc(await ipcClient.clients.respondCrmReview(r.id,response));},'Réponse enregistrée');}}>Répondre</button>}</article>)}</div></section>}
    {tab==='portail'&&<section className="grid gap-4 lg:grid-cols-2"><Info title="Portail client"><p>Invitation sécurisée valable 48 heures, accès aux réservations et factures.</p><button className={`${button} mt-3`}onClick={()=>void invitePortal()}>Inviter le client sélectionné</button></Info><Info title="Pré-check-in"><p>Identité, document, heure d’arrivée et consentement fiche de police, puis validation réception.</p><button className={`${button} mt-3`}onClick={()=>void invitePrecheckin()}>Inviter une réservation</button></Info></section>}
  </div>;
}

function Info({title,children}:{title:string;children:ReactNode}){return <article className="rounded-xl border bg-card p-4"><h2 className="mb-2 flex items-center gap-2 font-semibold"><MessageSquareText className="h-4 w-4 text-primary"/>{title}</h2><div className="text-sm text-muted-foreground">{children}</div></article>}
