import {
  Anchor,
  BadgeCheck,
  FileText,
  LayoutDashboard,
  MapPin,
  Receipt,
  Ship,
  Tags,
  Users,
  Wallet,
} from 'lucide-react';
import type { OdooAppDefinition } from '@/components/apps/OdooAppLauncher';

export const PORTMASTER_APP_GROUPS = [
  'Pilotage',
  'Référentiel',
  'Clients & flotte',
  'Facturation',
  'Opérations',
] as const;

export const PORTMASTER_APPS: OdooAppDefinition[] = [
  {
    id: 'dashboard',
    name: 'Tableau de bord',
    description: 'KPIs, graphiques et plan d\'amarrage',
    route: '/portmaster/dashboard',
    group: 'Pilotage',
    color: '#1A5276',
    icon: LayoutDashboard,
  },
  {
    id: 'referentiel',
    name: 'Référentiel port',
    description: 'Zones, types et paramètres',
    route: '/portmaster/referentiel',
    group: 'Référentiel',
    color: '#5278B8',
    icon: Anchor,
  },
  {
    id: 'emplacements',
    name: 'Emplacements',
    description: 'Places et statuts d\'occupation',
    route: '/portmaster/emplacements',
    group: 'Référentiel',
    color: '#148F77',
    icon: MapPin,
  },
  {
    id: 'clients',
    name: 'Clients port',
    description: 'Armateurs et dossiers clients',
    route: '/portmaster/clients',
    group: 'Clients & flotte',
    color: '#3498DB',
    icon: Users,
  },
  {
    id: 'bateaux',
    name: 'Bateaux',
    description: 'Flotte enregistrée',
    route: '/portmaster/bateaux',
    group: 'Clients & flotte',
    color: '#00B4D8',
    icon: Ship,
  },
  {
    id: 'contrats',
    name: 'Contrats',
    description: 'Contrats d\'amarrage',
    route: '/portmaster/contrats',
    group: 'Clients & flotte',
    color: '#875A7B',
    icon: FileText,
  },
  {
    id: 'factures',
    name: 'Factures',
    description: 'Facturation portuaire',
    route: '/portmaster/factures',
    group: 'Facturation',
    color: '#00A09D',
    icon: Receipt,
  },
  {
    id: 'tarifs',
    name: 'Tarifs port',
    description: 'Grilles et barèmes',
    route: '/portmaster/tarifs',
    group: 'Facturation',
    color: '#E99D00',
    icon: Tags,
  },
  {
    id: 'recouvrement',
    name: 'Recouvrement',
    description: 'Créances et relances',
    route: '/portmaster/recouvrement',
    group: 'Facturation',
    color: '#DC6965',
    icon: Wallet,
  },
  {
    id: 'mouvements',
    name: 'Mouvements',
    description: 'Entrées / sorties des navires',
    route: '/portmaster/mouvements',
    group: 'Opérations',
    color: '#5B8DEE',
    icon: Ship,
  },
  {
    id: 'validations',
    name: 'Validations',
    description: 'File de validation N+1',
    route: '/portmaster/validations',
    group: 'Opérations',
    color: '#714B67',
    icon: BadgeCheck,
  },
];
