import Electron from '../lib/electronApi';
import { wrapIpc } from './ipcHelpers';
import { assertAmount, assertDateJournal, assertObject, assertPositiveInteger, assertText } from './validation';
import * as svc from '../services/pms-extensions.service';

export function registerPmsExtensionsIpc():void {
  Electron.ipcMain.handle('pms:groupes:list',(e,hotelId?:number)=>wrapIpc(e,uid=>svc.listGroupes(uid,hotelId)));
  Electron.ipcMain.handle('pms:groupes:create',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.createGroupe(uid,{hotelId:assertPositiveInteger(o.hotelId,'hotelId'),nom:assertText(o.nom,'nom',{required:true,maxLength:150}),dateArrivee:assertDateJournal(o.dateArrivee,'dateArrivee'),dateDepart:assertDateJournal(o.dateDepart,'dateDepart'),allotement:assertPositiveInteger(o.allotement,'allotement'),contactNom:o.contactNom?assertText(o.contactNom,'contactNom',{maxLength:150}):undefined,contactEmail:o.contactEmail?assertText(o.contactEmail,'contactEmail',{maxLength:200}):undefined,contactTelephone:o.contactTelephone?assertText(o.contactTelephone,'contactTelephone',{maxLength:40}):undefined,notes:o.notes?assertText(o.notes,'notes',{maxLength:2000}):undefined});}));
  Electron.ipcMain.handle('pms:groupes:addReservation',(e,groupeId:unknown,reservationId:unknown)=>wrapIpc(e,uid=>svc.addReservationToGroupe(uid,assertPositiveInteger(groupeId,'groupeId'),assertPositiveInteger(reservationId,'reservationId'))));
  Electron.ipcMain.handle('pms:depots:list',(e,reservationId?:number)=>wrapIpc(e,uid=>svc.listDepots(uid,reservationId)));
  Electron.ipcMain.handle('pms:depots:create',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.createDepot(uid,{reservationId:assertPositiveInteger(o.reservationId,'reservationId'),montant:assertAmount(o.montant,'montant'),mode:assertText(o.mode,'mode',{required:true,maxLength:20}),reference:o.reference?assertText(o.reference,'reference',{maxLength:100}):undefined,dateDepot:assertDateJournal(o.dateDepot,'dateDepot')});}));
  Electron.ipcMain.handle('pms:channels:list',(e)=>wrapIpc(e,uid=>svc.listConnectors(uid)));
  Electron.ipcMain.handle('pms:channels:save',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.saveConnector(uid,{hotelId:assertPositiveInteger(o.hotelId,'hotelId'),code:assertText(o.code,'code',{required:true,maxLength:30}),label:assertText(o.label,'label',{required:true,maxLength:100}),endpointUrl:o.endpointUrl?assertText(o.endpointUrl,'endpointUrl',{maxLength:500}):undefined,actif:o.actif===true});}));
  Electron.ipcMain.handle('pms:channels:import',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.importChannelReservation(uid,{connectorId:assertPositiveInteger(o.connectorId,'connectorId'),externalReference:assertText(o.externalReference,'externalReference',{required:true,maxLength:100}),hotelId:assertPositiveInteger(o.hotelId,'hotelId'),clientNom:assertText(o.clientNom,'clientNom',{required:true,maxLength:150}),dateArrivee:assertDateJournal(o.dateArrivee,'dateArrivee'),dateDepart:assertDateJournal(o.dateDepart,'dateDepart'),montantTotal:o.montantTotal!==undefined?assertAmount(o.montantTotal,'montantTotal'):undefined,notes:o.notes?assertText(o.notes,'notes',{maxLength:2000}):undefined});}));
}
