import Electron from '../lib/electronApi';
import { wrapIpc } from './ipcHelpers';
import { assertAmount, assertArray, assertDateJournal, assertEnum, assertObject, assertPositiveInteger, assertText } from './validation';
import * as svc from '../services/pms-extensions.service';
import * as advanced from '../services/pms-advanced.service';
import type { PmsAttente, PmsOccupant, PmsPolitiqueAnnulation, UpdateReservationInput } from '../../src/shared/types/hebergement';

const optionalId=(v:unknown,label:string)=>v===undefined||v===null?undefined:assertPositiveInteger(v,label);
const optionalDate=(v:unknown,label:string)=>v===undefined||v===null?undefined:assertDateJournal(v,label);
const optionalText=(v:unknown,label:string,maxLength:number)=>v===undefined||v===null?undefined:assertText(v,label,{maxLength});

export function registerPmsExtensionsIpc():void {
  Electron.ipcMain.handle('pms:groupes:list',(e,hotelId?:number)=>wrapIpc(e,uid=>svc.listGroupes(uid,hotelId)));
  Electron.ipcMain.handle('pms:groupes:create',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.createGroupe(uid,{hotelId:assertPositiveInteger(o.hotelId,'hotelId'),nom:assertText(o.nom,'nom',{required:true,maxLength:150}),dateArrivee:assertDateJournal(o.dateArrivee,'dateArrivee'),dateDepart:assertDateJournal(o.dateDepart,'dateDepart'),allotement:assertPositiveInteger(o.allotement,'allotement'),contactNom:o.contactNom?assertText(o.contactNom,'contactNom',{maxLength:150}):undefined,contactEmail:o.contactEmail?assertText(o.contactEmail,'contactEmail',{maxLength:200}):undefined,contactTelephone:o.contactTelephone?assertText(o.contactTelephone,'contactTelephone',{maxLength:40}):undefined,notes:o.notes?assertText(o.notes,'notes',{maxLength:2000}):undefined});}));
  Electron.ipcMain.handle('pms:groupes:addReservation',(e,groupeId:unknown,reservationId:unknown)=>wrapIpc(e,uid=>svc.addReservationToGroupe(uid,assertPositiveInteger(groupeId,'groupeId'),assertPositiveInteger(reservationId,'reservationId'))));
  Electron.ipcMain.handle('pms:depots:list',(e,reservationId?:number)=>wrapIpc(e,uid=>svc.listDepots(uid,reservationId)));
  Electron.ipcMain.handle('pms:depots:create',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.createDepot(uid,{reservationId:assertPositiveInteger(o.reservationId,'reservationId'),montant:assertAmount(o.montant,'montant'),mode:assertText(o.mode,'mode',{required:true,maxLength:20}),reference:o.reference?assertText(o.reference,'reference',{maxLength:100}):undefined,dateDepot:assertDateJournal(o.dateDepot,'dateDepot')});}));
  Electron.ipcMain.handle('pms:channels:list',(e)=>wrapIpc(e,uid=>svc.listConnectors(uid)));
  Electron.ipcMain.handle('pms:channels:save',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.saveConnector(uid,{hotelId:assertPositiveInteger(o.hotelId,'hotelId'),code:assertText(o.code,'code',{required:true,maxLength:30}),label:assertText(o.label,'label',{required:true,maxLength:100}),endpointUrl:o.endpointUrl?assertText(o.endpointUrl,'endpointUrl',{maxLength:500}):undefined,actif:o.actif===true});}));
  Electron.ipcMain.handle('pms:channels:import',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.importChannelReservation(uid,{connectorId:assertPositiveInteger(o.connectorId,'connectorId'),externalReference:assertText(o.externalReference,'externalReference',{required:true,maxLength:100}),hotelId:assertPositiveInteger(o.hotelId,'hotelId'),clientNom:assertText(o.clientNom,'clientNom',{required:true,maxLength:150}),dateArrivee:assertDateJournal(o.dateArrivee,'dateArrivee'),dateDepart:assertDateJournal(o.dateDepart,'dateDepart'),montantTotal:o.montantTotal!==undefined?assertAmount(o.montantTotal,'montantTotal'):undefined,notes:o.notes?assertText(o.notes,'notes',{maxLength:2000}):undefined});}));

  Electron.ipcMain.handle('pms:reservations:update',(e,reservationId:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');const clean:UpdateReservationInput={
    chambreId:o.chambreId===null?null:optionalId(o.chambreId,'chambreId'),clientId:o.clientId===null?null:optionalId(o.clientId,'clientId'),planId:optionalId(o.planId,'planId'),formuleId:o.formuleId===null?null:optionalId(o.formuleId,'formuleId'),
    dateArrivee:optionalDate(o.dateArrivee,'dateArrivee'),dateDepart:optionalDate(o.dateDepart,'dateDepart'),nbAdultes:optionalId(o.nbAdultes,'nbAdultes'),nbEnfants:o.nbEnfants===undefined?undefined:assertPositiveInteger(o.nbEnfants,'nbEnfants',{allowZero:true}),
    clientNom:optionalText(o.clientNom,'clientNom',150),clientPrenom:o.clientPrenom===null?null:optionalText(o.clientPrenom,'clientPrenom',150),clientEmail:o.clientEmail===null?null:optionalText(o.clientEmail,'clientEmail',200),clientTelephone:o.clientTelephone===null?null:optionalText(o.clientTelephone,'clientTelephone',40),
    montantTotal:o.montantTotal===undefined?undefined:assertAmount(o.montantTotal,'montantTotal'),source:o.source===undefined?undefined:assertEnum(o.source,'source',['direct','booking','expedia','airbnb','agence','autre'] as const),notes:o.notes===null?null:optionalText(o.notes,'notes',2000),
    surbookingAutorise:o.surbookingAutorise===undefined?undefined:o.surbookingAutorise===true,surbookingMotif:o.surbookingMotif===null?null:optionalText(o.surbookingMotif,'surbookingMotif',500),politiqueAnnulationId:o.politiqueAnnulationId===null?null:optionalId(o.politiqueAnnulationId,'politiqueAnnulationId'),
  };return advanced.updateReservation(uid,assertPositiveInteger(reservationId,'reservationId'),clean);}));
  Electron.ipcMain.handle('pms:reservations:moveRoom',(e,reservationId:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.moveReservationRoom(uid,assertPositiveInteger(reservationId,'reservationId'),assertPositiveInteger(o.newRoomId,'newRoomId'),assertText(o.motif,'motif',{required:true,maxLength:500}),o.surbookingAutorise===true);}));
  Electron.ipcMain.handle('pms:reservations:roomMoves',(e,reservationId:unknown)=>wrapIpc(e,uid=>advanced.listRoomMoves(uid,assertPositiveInteger(reservationId,'reservationId'))));

  Electron.ipcMain.handle('pms:occupants:list',(e,reservationId:unknown)=>wrapIpc(e,uid=>advanced.listOccupants(uid,assertPositiveInteger(reservationId,'reservationId'))));
  Electron.ipcMain.handle('pms:occupants:save',(e,reservationId:unknown,input:unknown,occupantId?:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');const clean:Omit<PmsOccupant,'id'|'reservationId'>={nom:assertText(o.nom,'nom',{required:true,maxLength:150}),prenom:optionalText(o.prenom,'prenom',150)??null,dateNaissance:optionalDate(o.dateNaissance,'dateNaissance')??null,nationalite:optionalText(o.nationalite,'nationalite',80)??null,typeDocument:optionalText(o.typeDocument,'typeDocument',50)??null,numeroDocument:optionalText(o.numeroDocument,'numeroDocument',100)??null,principal:o.principal===true};return advanced.saveOccupant(uid,assertPositiveInteger(reservationId,'reservationId'),clean,occupantId===undefined?undefined:assertPositiveInteger(occupantId,'occupantId'));}));
  Electron.ipcMain.handle('pms:occupants:delete',(e,occupantId:unknown)=>wrapIpc(e,uid=>advanced.deleteOccupant(uid,assertPositiveInteger(occupantId,'occupantId'))));

  Electron.ipcMain.handle('pms:waitlist:list',(e,hotelId?:unknown)=>wrapIpc(e,uid=>advanced.listWaitlist(uid,hotelId===undefined?undefined:assertPositiveInteger(hotelId,'hotelId'))));
  Electron.ipcMain.handle('pms:waitlist:create',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.createWaitlist(uid,{hotelId:assertPositiveInteger(o.hotelId,'hotelId'),typeChambreId:optionalId(o.typeChambreId,'typeChambreId'),clientNom:assertText(o.clientNom,'clientNom',{required:true,maxLength:150}),clientPrenom:optionalText(o.clientPrenom,'clientPrenom',150),clientEmail:optionalText(o.clientEmail,'clientEmail',200),clientTelephone:optionalText(o.clientTelephone,'clientTelephone',40),dateArrivee:assertDateJournal(o.dateArrivee,'dateArrivee'),dateDepart:assertDateJournal(o.dateDepart,'dateDepart'),nbAdultes:o.nbAdultes===undefined?undefined:assertPositiveInteger(o.nbAdultes,'nbAdultes'),nbEnfants:o.nbEnfants===undefined?undefined:assertPositiveInteger(o.nbEnfants,'nbEnfants',{allowZero:true}),priorite:o.priorite===undefined?undefined:assertPositiveInteger(o.priorite,'priorite'),notes:optionalText(o.notes,'notes',2000)});}));
  Electron.ipcMain.handle('pms:waitlist:status',(e,id:unknown,statut:unknown)=>wrapIpc(e,uid=>advanced.updateWaitlistStatus(uid,assertPositiveInteger(id,'id'),assertEnum(statut,'statut',['attente','contacte','convertie','annulee','expiree'] as const) as PmsAttente['statut'])));
  Electron.ipcMain.handle('pms:waitlist:promote',(e,id:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.promoteWaitlist(uid,assertPositiveInteger(id,'id'),assertPositiveInteger(o.chambreId,'chambreId'),o.surbookingAutorise===true,optionalText(o.motif,'motif',500));}));

  Electron.ipcMain.handle('pms:cancellationPolicies:list',(e,hotelId?:unknown)=>wrapIpc(e,uid=>advanced.listCancellationPolicies(uid,hotelId===undefined?undefined:assertPositiveInteger(hotelId,'hotelId'))));
  Electron.ipcMain.handle('pms:cancellationPolicies:create',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');const clean:Omit<PmsPolitiqueAnnulation,'id'|'hotelName'|'actif'>={hotelId:assertPositiveInteger(o.hotelId,'hotelId'),nom:assertText(o.nom,'nom',{required:true,maxLength:150}),delaiSansFraisJours:assertPositiveInteger(o.delaiSansFraisJours,'delaiSansFraisJours',{allowZero:true}),penaliteType:assertEnum(o.penaliteType,'penaliteType',['pourcentage','montant','nuitees'] as const),penaliteValeur:assertAmount(o.penaliteValeur,'penaliteValeur'),noShowType:assertEnum(o.noShowType,'noShowType',['pourcentage','montant','nuitees'] as const),noShowValeur:assertAmount(o.noShowValeur,'noShowValeur')};return advanced.createCancellationPolicy(uid,clean);}));
  Electron.ipcMain.handle('pms:reservations:cancel',(e,reservationId:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.cancelReservation(uid,assertPositiveInteger(reservationId,'reservationId'),assertText(o.motif,'motif',{required:true,maxLength:1000}),optionalId(o.policyId,'policyId'));}));
  Electron.ipcMain.handle('pms:reservations:noShow',(e,reservationId:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.markReservationNoShow(uid,assertPositiveInteger(reservationId,'reservationId'),assertText(o.motif,'motif',{required:true,maxLength:1000}),optionalId(o.policyId,'policyId'));}));
  Electron.ipcMain.handle('pms:depots:operate',(e,depotId:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.operateDeposit(uid,assertPositiveInteger(depotId,'depotId'),assertEnum(o.type,'type',['remboursement','annulation'] as const),assertText(o.motif,'motif',{required:true,maxLength:1000}),optionalText(o.reference,'reference',100));}));
  Electron.ipcMain.handle('pms:folios:transfer',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.transferFolioLines(uid,assertPositiveInteger(o.sourceReservationId,'sourceReservationId'),assertPositiveInteger(o.destinationReservationId,'destinationReservationId'),assertArray<unknown>(o.lineIds,'lineIds',1).map((v,i)=>assertPositiveInteger(v,`lineIds[${i}]`)),assertText(o.motif,'motif',{required:true,maxLength:500}));}));
  Electron.ipcMain.handle('pms:folios:share',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.shareFolio(uid,assertPositiveInteger(o.folioReservationId,'folioReservationId'),assertPositiveInteger(o.sharedReservationId,'sharedReservationId'));}));
}
