import Electron from '../lib/electronApi';
import { wrapIpc } from './ipcHelpers';
import { assertAmount, assertArray, assertDateJournal, assertEnum, assertObject, assertPositiveInteger, assertText } from './validation';
import * as svc from '../services/pms-extensions.service';
import * as advanced from '../services/pms-advanced.service';
import * as distribution from '../services/distribution.service';
import * as mice from '../services/mice.service';
import type { PmsAttente, PmsOccupant, PmsPolitiqueAnnulation, UpdateReservationInput } from '../../src/shared/types/hebergement';

const optionalId=(v:unknown,label:string)=>v===undefined||v===null?undefined:assertPositiveInteger(v,label);
const optionalDate=(v:unknown,label:string)=>v===undefined||v===null?undefined:assertDateJournal(v,label);
const optionalText=(v:unknown,label:string,maxLength:number)=>v===undefined||v===null?undefined:assertText(v,label,{maxLength});

export function registerPmsExtensionsIpc():void {
  Electron.ipcMain.handle('pms:groupes:list',(e,hotelId?:number)=>wrapIpc(e,uid=>svc.listGroupes(uid,hotelId)));
  Electron.ipcMain.handle('pms:groupes:create',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.createGroupe(uid,{hotelId:assertPositiveInteger(o.hotelId,'hotelId'),nom:assertText(o.nom,'nom',{required:true,maxLength:150}),dateArrivee:assertDateJournal(o.dateArrivee,'dateArrivee'),dateDepart:assertDateJournal(o.dateDepart,'dateDepart'),allotement:assertPositiveInteger(o.allotement,'allotement'),contactNom:o.contactNom?assertText(o.contactNom,'contactNom',{maxLength:150}):undefined,contactEmail:o.contactEmail?assertText(o.contactEmail,'contactEmail',{maxLength:200}):undefined,contactTelephone:o.contactTelephone?assertText(o.contactTelephone,'contactTelephone',{maxLength:40}):undefined,notes:o.notes?assertText(o.notes,'notes',{maxLength:2000}):undefined});}));
  Electron.ipcMain.handle('pms:groupes:addReservation',(e,groupeId:unknown,reservationId:unknown)=>wrapIpc(e,uid=>svc.addReservationToGroupe(uid,assertPositiveInteger(groupeId,'groupeId'),assertPositiveInteger(reservationId,'reservationId'))));
  Electron.ipcMain.handle('pms:depots:list',(e,reservationId?:number)=>wrapIpc(e,uid=>svc.listDepots(uid,reservationId)));
  Electron.ipcMain.handle('pms:depots:create',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.createDepot(uid,{reservationId:assertPositiveInteger(o.reservationId,'reservationId'),montant:assertAmount(o.montant,'montant'),mode:assertText(o.mode,'mode',{required:true,maxLength:20}),reference:o.reference?assertText(o.reference,'reference',{maxLength:100}):undefined,dateDepot:assertDateJournal(o.dateDepot,'dateDepot')});}));
  Electron.ipcMain.handle('pms:channels:list',(e)=>wrapIpc(e,uid=>svc.listConnectors(uid)));
  Electron.ipcMain.handle('pms:channels:save',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.saveConnector(uid,{hotelId:assertPositiveInteger(o.hotelId,'hotelId'),code:assertText(o.code,'code',{required:true,maxLength:30}),label:assertText(o.label,'label',{required:true,maxLength:100}),endpointUrl:o.endpointUrl?assertText(o.endpointUrl,'endpointUrl',{maxLength:500}):undefined,actif:o.actif===true});}));
  Electron.ipcMain.handle('pms:channels:import',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return svc.importChannelReservation(uid,{connectorId:assertPositiveInteger(o.connectorId,'connectorId'),externalReference:assertText(o.externalReference,'externalReference',{required:true,maxLength:100}),hotelId:assertPositiveInteger(o.hotelId,'hotelId'),clientNom:assertText(o.clientNom,'clientNom',{required:true,maxLength:150}),dateArrivee:assertDateJournal(o.dateArrivee,'dateArrivee'),dateDepart:assertDateJournal(o.dateDepart,'dateDepart'),montantTotal:o.montantTotal!==undefined?assertAmount(o.montantTotal,'montantTotal'):undefined,notes:o.notes?assertText(o.notes,'notes',{maxLength:2000}):undefined});}));
  Electron.ipcMain.handle('distribution:connector:configure',(e,input)=>wrapIpc(e,uid=>distribution.configureConnector(uid,input)));
  Electron.ipcMain.handle('distribution:mapping:save',(e,input)=>wrapIpc(e,uid=>distribution.saveMapping(uid,input)));
  Electron.ipcMain.handle('distribution:availability',(e,hotelId:number,from:string,to:string)=>wrapIpc(e,uid=>distribution.availability(uid,hotelId,from,to)));
  Electron.ipcMain.handle('distribution:restriction:save',(e,input)=>wrapIpc(e,uid=>distribution.setRestriction(uid,input)));
  Electron.ipcMain.handle('distribution:sync:queue',(e,connectorId:number,from:string,to:string)=>wrapIpc(e,uid=>distribution.queueInventorySync(uid,connectorId,from,to)));
  Electron.ipcMain.handle('distribution:sync:next',(e,limit?:number)=>wrapIpc(e,uid=>distribution.nextSyncJobs(uid,limit)));
  Electron.ipcMain.handle('distribution:sync:complete',(e,id:number,result)=>wrapIpc(e,uid=>distribution.completeSyncJob(uid,id,result)));
  Electron.ipcMain.handle('distribution:sync:logs',(e,connectorId:number)=>wrapIpc(e,uid=>distribution.listSyncLogs(uid,connectorId)));
  Electron.ipcMain.handle('distribution:webhook:ingest',(e,input)=>wrapIpc(e,uid=>distribution.ingestWebhook(uid,input)));
  Electron.ipcMain.handle('distribution:booking:config',(e,input)=>wrapIpc(e,uid=>distribution.saveBookingConfig(uid,input)));
  Electron.ipcMain.handle('distribution:booking:promo',(e,input)=>wrapIpc(e,uid=>distribution.savePromo(uid,input)));
  Electron.ipcMain.handle('distribution:booking:quote',(e,input)=>wrapIpc(e,uid=>distribution.quoteBooking(uid,input)));
  Electron.ipcMain.handle('distribution:booking:create',(e,input)=>wrapIpc(e,uid=>distribution.createBookingOrder(uid,input)));
  Electron.ipcMain.handle('distribution:booking:payment',(e,input)=>wrapIpc(e,uid=>distribution.confirmBookingPayment(uid,input)));
  Electron.ipcMain.handle('distribution:dashboard',(e,hotelId:number)=>wrapIpc(e,uid=>distribution.distributionDashboard(uid,hotelId)));

  Electron.ipcMain.handle('pms:reservations:update',(e,reservationId:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');const clean:UpdateReservationInput={
    chambreId:o.chambreId===null?null:optionalId(o.chambreId,'chambreId'),clientId:o.clientId===null?null:optionalId(o.clientId,'clientId'),planId:optionalId(o.planId,'planId'),formuleId:o.formuleId===null?null:optionalId(o.formuleId,'formuleId'),
    dateArrivee:optionalDate(o.dateArrivee,'dateArrivee'),dateDepart:optionalDate(o.dateDepart,'dateDepart'),nbAdultes:optionalId(o.nbAdultes,'nbAdultes'),nbEnfants:o.nbEnfants===undefined?undefined:assertPositiveInteger(o.nbEnfants,'nbEnfants',{allowZero:true}),
    clientNom:optionalText(o.clientNom,'clientNom',150),clientPrenom:o.clientPrenom===null?null:optionalText(o.clientPrenom,'clientPrenom',150),clientEmail:o.clientEmail===null?null:optionalText(o.clientEmail,'clientEmail',200),clientTelephone:o.clientTelephone===null?null:optionalText(o.clientTelephone,'clientTelephone',40),
    montantTotal:o.montantTotal===undefined?undefined:assertAmount(o.montantTotal,'montantTotal'),source:o.source===undefined?undefined:assertEnum(o.source,'source',['direct','booking','expedia','airbnb','agence','autre'] as const),notes:o.notes===null?null:optionalText(o.notes,'notes',2000),
    surbookingAutorise:o.surbookingAutorise===undefined?undefined:o.surbookingAutorise===true,surbookingMotif:o.surbookingMotif===null?null:optionalText(o.surbookingMotif,'surbookingMotif',500),politiqueAnnulationId:o.politiqueAnnulationId===null?null:optionalId(o.politiqueAnnulationId,'politiqueAnnulationId'),
  };return advanced.updateReservation(uid,assertPositiveInteger(reservationId,'reservationId'),clean);}));
  Electron.ipcMain.handle('pms:reservations:moveRoom',(e,reservationId:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.moveReservationRoom(uid,assertPositiveInteger(reservationId,'reservationId'),assertPositiveInteger(o.newRoomId,'newRoomId'),assertText(o.motif,'motif',{required:true,maxLength:500}),o.surbookingAutorise===true);}));
  Electron.ipcMain.handle('pms:reservations:roomMoves',(e,reservationId:unknown)=>wrapIpc(e,uid=>advanced.listRoomMoves(uid,assertPositiveInteger(reservationId,'reservationId'))));

  Electron.ipcMain.handle('pms:occupants:list',(e,reservationId:unknown)=>wrapIpc(e,uid=>advanced.listOccupants(uid,assertPositiveInteger(reservationId,'reservationId'))));
  Electron.ipcMain.handle('pms:occupants:save',(e,reservationId:unknown,input:unknown,occupantId?:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');const clean:Omit<PmsOccupant,'id'|'reservationId'>={nom:assertText(o.nom,'nom',{required:true,maxLength:150}),prenom:optionalText(o.prenom,'prenom',150)??null,dateNaissance:optionalDate(o.dateNaissance,'dateNaissance')??null,nationalite:optionalText(o.nationalite,'nationalite',80)??null,typeDocument:optionalText(o.typeDocument,'typeDocument',50)??null,numeroDocument:optionalText(o.numeroDocument,'numeroDocument',100)??null,principal:o.principal===true};return advanced.saveOccupant(uid,assertPositiveInteger(reservationId,'reservationId'),clean,occupantId===undefined?undefined:assertPositiveInteger(occupantId,'occupantId'));}));
  Electron.ipcMain.handle('pms:occupants:delete',(e,occupantId:unknown)=>wrapIpc(e,uid=>advanced.deleteOccupant(uid,assertPositiveInteger(occupantId,'occupantId'))));

  Electron.ipcMain.handle('pms:waitlist:list',(e,hotelId?:unknown)=>wrapIpc(e,uid=>advanced.listWaitlist(uid,hotelId===undefined?undefined:assertPositiveInteger(hotelId,'hotelId'))));
  Electron.ipcMain.handle('pms:waitlist:create',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.createWaitlist(uid,{hotelId:assertPositiveInteger(o.hotelId,'hotelId'),typeChambreId:optionalId(o.typeChambreId,'typeChambreId'),clientNom:assertText(o.clientNom,'clientNom',{required:true,maxLength:150}),clientPrenom:optionalText(o.clientPrenom,'clientPrenom',150),clientEmail:optionalText(o.clientEmail,'clientEmail',200),clientTelephone:optionalText(o.clientTelephone,'clientTelephone',40),dateArrivee:assertDateJournal(o.dateArrivee,'dateArrivee'),dateDepart:assertDateJournal(o.dateDepart,'dateDepart'),nbAdultes:o.nbAdultes===undefined?undefined:assertPositiveInteger(o.nbAdultes,'nbAdultes'),nbEnfants:o.nbEnfants===undefined?undefined:assertPositiveInteger(o.nbEnfants,'nbEnfants',{allowZero:true}),priorite:o.priorite===undefined?undefined:assertPositiveInteger(o.priorite,'priorite'),notes:optionalText(o.notes,'notes',2000)});}));
  Electron.ipcMain.handle('pms:waitlist:status',(e,id:unknown,statut:unknown)=>wrapIpc(e,uid=>advanced.updateWaitlistStatus(uid,assertPositiveInteger(id,'id'),assertEnum(statut,'statut',['attente','contacte','convertie','annulee','expiree'] as const) as PmsAttente['statut'])));
  Electron.ipcMain.handle('pms:waitlist:promote',(e,id:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.promoteWaitlist(uid,assertPositiveInteger(id,'id'),assertPositiveInteger(o.chambreId,'chambreId'),o.surbookingAutorise===true,optionalText(o.motif,'motif',500));}));

  Electron.ipcMain.handle('pms:cancellationPolicies:list',(e,hotelId?:unknown)=>wrapIpc(e,uid=>advanced.listCancellationPolicies(uid,hotelId===undefined?undefined:assertPositiveInteger(hotelId,'hotelId'))));
  Electron.ipcMain.handle('pms:cancellationPolicies:create',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');const clean:Omit<PmsPolitiqueAnnulation,'id'|'hotelName'|'actif'>={hotelId:assertPositiveInteger(o.hotelId,'hotelId'),nom:assertText(o.nom,'nom',{required:true,maxLength:150}),delaiSansFraisJours:assertPositiveInteger(o.delaiSansFraisJours,'delaiSansFraisJours',{allowZero:true}),penaliteType:assertEnum(o.penaliteType,'penaliteType',['pourcentage','montant','nuitees'] as const),penaliteValeur:assertAmount(o.penaliteValeur,'penaliteValeur'),noShowType:assertEnum(o.noShowType,'noShowType',['pourcentage','montant','nuitees'] as const),noShowValeur:assertAmount(o.noShowValeur,'noShowValeur')};return advanced.createCancellationPolicy(uid,clean);}));
  Electron.ipcMain.handle('pms:reservations:cancel',(e,reservationId:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.cancelReservation(uid,assertPositiveInteger(reservationId,'reservationId'),assertText(o.motif,'motif',{required:true,maxLength:1000}),optionalId(o.policyId,'policyId'));}));
  Electron.ipcMain.handle('pms:reservations:noShow',(e,reservationId:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.markReservationNoShow(uid,assertPositiveInteger(reservationId,'reservationId'),assertText(o.motif,'motif',{required:true,maxLength:1000}),optionalId(o.policyId,'policyId'));}));
  Electron.ipcMain.handle('pms:depots:operate',(e,depotId:unknown,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.operateDeposit(uid,assertPositiveInteger(depotId,'depotId'),assertEnum(o.type,'type',['remboursement','annulation'] as const),assertText(o.motif,'motif',{required:true,maxLength:1000}),optionalText(o.reference,'reference',100));}));
  Electron.ipcMain.handle('pms:folios:transfer',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.transferFolioLines(uid,assertPositiveInteger(o.sourceReservationId,'sourceReservationId'),assertPositiveInteger(o.destinationReservationId,'destinationReservationId'),assertArray<unknown>(o.lineIds,'lineIds',1).map((v,i)=>assertPositiveInteger(v,`lineIds[${i}]`)),assertText(o.motif,'motif',{required:true,maxLength:500}));}));
  Electron.ipcMain.handle('pms:folios:share',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return advanced.shareFolio(uid,assertPositiveInteger(o.folioReservationId,'folioReservationId'),assertPositiveInteger(o.sharedReservationId,'sharedReservationId'));}));

  Electron.ipcMain.handle('mice:dashboard',(e,hotelId:unknown)=>wrapIpc(e,uid=>mice.miceDashboard(uid,assertPositiveInteger(hotelId,'hotelId'))));
  Electron.ipcMain.handle('mice:groups:detail',(e,id:unknown)=>wrapIpc(e,uid=>mice.groupDetail(uid,assertPositiveInteger(id,'groupeId'))));
  Electron.ipcMain.handle('mice:allotments:save',(e,input:unknown)=>wrapIpc(e,uid=>{const o=assertObject<Record<string,unknown>>(input,'input');return mice.saveAllotment(uid,{groupeId:assertPositiveInteger(o.groupeId,'groupeId'),typeChambreId:assertPositiveInteger(o.typeChambreId,'typeChambreId'),quantite:assertPositiveInteger(o.quantite,'quantite'),tarifNegocie:o.tarifNegocie===undefined?undefined:assertAmount(o.tarifNegocie,'tarifNegocie'),dateRelease:assertDateJournal(o.dateRelease,'dateRelease')});}));
  Electron.ipcMain.handle('mice:allotments:release',(e,groupeId:unknown,date?:unknown)=>wrapIpc(e,uid=>mice.releaseAllotments(uid,assertPositiveInteger(groupeId,'groupeId'),date===undefined?undefined:assertDateJournal(date,'date'))));
  Electron.ipcMain.handle('mice:rooming:import',(e,groupeId:unknown,rows:unknown)=>wrapIpc(e,uid=>{
    const clean=assertArray<Record<string,unknown>>(rows,'rows',1).map((o,i)=>({
      nom:assertText(o.nom,`rows[${i}].nom`,{required:true,maxLength:150}),prenom:optionalText(o.prenom,`rows[${i}].prenom`,150),email:optionalText(o.email,`rows[${i}].email`,200),telephone:optionalText(o.telephone,`rows[${i}].telephone`,40),typeChambreId:optionalId(o.typeChambreId,`rows[${i}].typeChambreId`),chambreId:optionalId(o.chambreId,`rows[${i}].chambreId`),dateArrivee:optionalDate(o.dateArrivee,`rows[${i}].dateArrivee`),dateDepart:optionalDate(o.dateDepart,`rows[${i}].dateDepart`),nbAdultes:o.nbAdultes===undefined?undefined:assertPositiveInteger(o.nbAdultes,`rows[${i}].nbAdultes`),nbEnfants:o.nbEnfants===undefined?undefined:assertPositiveInteger(o.nbEnfants,`rows[${i}].nbEnfants`,{allowZero:true}),notes:optionalText(o.notes,`rows[${i}].notes`,1000)
    }));
    return mice.importRoomingList(uid,assertPositiveInteger(groupeId,'groupeId'),clean);
  }));
  Electron.ipcMain.handle('mice:rooming:reserve',(e,id:unknown)=>wrapIpc(e,uid=>mice.reserveRoomingLine(uid,assertPositiveInteger(id,'lineId'))));
  Electron.ipcMain.handle('mice:spaces:list',(e,hotelId:unknown)=>wrapIpc(e,uid=>mice.listSpaces(uid,assertPositiveInteger(hotelId,'hotelId'))));
  Electron.ipcMain.handle('mice:spaces:save',(e,input)=>wrapIpc(e,uid=>mice.saveSpace(uid,input)));
  Electron.ipcMain.handle('mice:events:list',(e,hotelId:unknown)=>wrapIpc(e,uid=>mice.listEvents(uid,assertPositiveInteger(hotelId,'hotelId'))));
  Electron.ipcMain.handle('mice:events:create',(e,input)=>wrapIpc(e,uid=>mice.createEvent(uid,input)));
  Electron.ipcMain.handle('mice:spaces:book',(e,input)=>wrapIpc(e,uid=>mice.bookSpace(uid,input)));
  Electron.ipcMain.handle('mice:quotes:create',(e,input)=>wrapIpc(e,uid=>mice.createQuote(uid,input)));
  Electron.ipcMain.handle('mice:quotes:addLine',(e,input)=>wrapIpc(e,uid=>mice.addQuoteLine(uid,input)));
  Electron.ipcMain.handle('mice:quotes:status',(e,id:number,status:'envoye'|'accepte'|'refuse'|'expire')=>wrapIpc(e,uid=>mice.setQuoteStatus(uid,id,status)));
  Electron.ipcMain.handle('mice:documents:list',(e,eventId:unknown)=>wrapIpc(e,uid=>mice.listEventDocuments(uid,assertPositiveInteger(eventId,'eventId'))));
  Electron.ipcMain.handle('mice:beo:save',(e,input)=>wrapIpc(e,uid=>mice.saveBeo(uid,input)));
  Electron.ipcMain.handle('mice:charges:add',(e,input)=>wrapIpc(e,uid=>mice.addEventCharge(uid,input)));
  Electron.ipcMain.handle('mice:events:invoice',(e,eventId:unknown)=>wrapIpc(e,uid=>mice.invoiceEvent(uid,assertPositiveInteger(eventId,'eventId'))));
}
