import { createHash, randomUUID } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readFileSync, statSync } from 'node:fs';
import Electron from '../lib/electronApi';
import path from '../lib/nodePath';
import { getDatabase } from '../database/sqlite';
import { getActorContext } from './actorContext';
import { writeAuditLog } from './audit.service';
import { assertDocumentLegallyProtected } from './ged-archivage.service';

function hashFile(file:string):string{return createHash('sha256').update(readFileSync(file)).digest('hex');}
function getRoot():string{const dir=path.join(Electron.app.getPath('userData'),'ged');if(!existsSync(dir))mkdirSync(dir,{recursive:true});return dir;}
export function listVersions(documentId:number){const db=getDatabase();const d=db.prepare('SELECT id,COALESCE(parent_document_id,id) root FROM ged_documents WHERE id=?').get(documentId) as {id:number;root:number}|undefined;if(!d)throw new Error('Document introuvable.');return db.prepare(`SELECT id,titre,nom_fichier,version,version_number,content_hash,is_current,created_at FROM ged_documents WHERE id=? OR parent_document_id=? ORDER BY version_number DESC`).all(d.root,d.root);}
export async function addVersion(actorId:number,documentId:number,note?:string){const db=getDatabase();const selected=db.prepare(`SELECT id,COALESCE(parent_document_id,id) AS root FROM ged_documents WHERE id=?`).get(documentId) as {id:number;root:number}|undefined;if(!selected)throw new Error('Document introuvable.');assertDocumentLegallyProtected(selected.root);const current=db.prepare(`SELECT * FROM ged_documents WHERE (id=? OR parent_document_id=?) AND is_current=1 ORDER BY version_number DESC LIMIT 1`).get(selected.root,selected.root) as Record<string,unknown>|undefined;if(!current)throw new Error('Document introuvable.');assertDocumentLegallyProtected(Number(current.id));const picked=await Electron.dialog.showOpenDialog({properties:['openFile'],title:'Sélectionner la nouvelle version'});if(picked.canceled||!picked.filePaths[0])throw new Error('Aucun fichier sélectionné.');const src=picked.filePaths[0];const ext=path.extname(src);const dest=path.join(getRoot(),`${randomUUID().replace(/-/g,'')}${ext}`);copyFileSync(src,dest);const root=Number(current.parent_document_id??current.id);const version=Number(current.version_number??1)+1;const digest=hashFile(dest);return db.transaction(()=>{db.prepare(`UPDATE ged_documents SET is_current=0,statut='archive',updated_at=datetime('now') WHERE id=?`).run(current.id);const r=db.prepare(`INSERT INTO ged_documents(uuid,hotel_id,categorie_id,titre,description,nom_fichier,chemin,taille_octets,mime_type,tags,version,confidentiel,uploaded_by,date_document,date_expiration,parent_document_id,version_number,content_hash,is_current) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1)`).run(randomUUID().replace(/-/g,''),current.hotel_id,current.categorie_id,current.titre,note?.trim()||current.description,path.basename(src),dest,statSync(dest).size,current.mime_type,current.tags,`${version}.0`,current.confidentiel,actorId,current.date_document,current.date_expiration,root,version,digest);writeAuditLog({userId:actorId,action:'CREATE',module:'ged',description:`Nouvelle version v${version} document #${root}`});return {id:Number(r.lastInsertRowid),versionNumber:version,contentHash:digest};})();}
export function requestOcr(actorId:number,documentId:number,langue='fra'){const db=getDatabase();const doc=db.prepare(`SELECT chemin,mime_type FROM ged_documents WHERE id=? AND statut!='supprime'`).get(documentId) as {chemin:string;mime_type:string|null}|undefined;if(!doc)throw new Error('Document introuvable.');let text:string|null=null;let status='en_attente';if(/\.(txt|csv|md|json)$/i.test(doc.chemin)){text=readFileSync(doc.chemin,'utf8').slice(0,1_000_000);status='termine';}db.prepare(`INSERT INTO ged_ocr_jobs(document_id,statut,langue,texte_extrait,confidence,requested_by,processed_at) VALUES(?,?,?,?,?,?,CASE WHEN ?='termine' THEN datetime('now') END) ON CONFLICT(document_id) DO UPDATE SET statut=excluded.statut,langue=excluded.langue,texte_extrait=excluded.texte_extrait,requested_by=excluded.requested_by,updated_at=datetime('now')`).run(documentId,status,langue,text,text?1:null,actorId,status);if(text)indexOcr(documentId,text);return getOcr(documentId);}
function indexOcr(documentId:number,text:string){const db=getDatabase();db.prepare('DELETE FROM ged_ocr_fts WHERE document_id=?').run(String(documentId));db.prepare('INSERT INTO ged_ocr_fts(document_id,texte_extrait) VALUES(?,?)').run(String(documentId),text);}
export function completeOcr(actorId:number,documentId:number,text:string,confidence?:number){if(!text.trim())throw new Error('Texte OCR vide.');getDatabase().prepare(`INSERT INTO ged_ocr_jobs(document_id,statut,texte_extrait,confidence,requested_by,processed_at) VALUES(?,'termine',?,?,?,datetime('now')) ON CONFLICT(document_id) DO UPDATE SET statut='termine',texte_extrait=excluded.texte_extrait,confidence=excluded.confidence,processed_at=datetime('now'),updated_at=datetime('now')`).run(documentId,text.slice(0,1_000_000),confidence??null,actorId);indexOcr(documentId,text);writeAuditLog({userId:actorId,action:'UPDATE',module:'ged',description:`OCR validé document #${documentId}`});return getOcr(documentId);}
export function getOcr(documentId:number){return getDatabase().prepare('SELECT * FROM ged_ocr_jobs WHERE document_id=?').get(documentId)??null;}
export function searchOcr(query:string){if(!query.trim())return [];return getDatabase().prepare(`SELECT d.id,d.titre,snippet(ged_ocr_fts,1,'<mark>','</mark>','…',24) extrait FROM ged_ocr_fts JOIN ged_documents d ON d.id=CAST(ged_ocr_fts.document_id AS INTEGER) WHERE ged_ocr_fts MATCH ? LIMIT 50`).all(query.replace(/["']/g,' '));}
export function signDocument(actorId:number,documentId:number,motif?:string){const db=getDatabase();const actor=getActorContext(actorId);const doc=db.prepare(`SELECT chemin FROM ged_documents WHERE id=? AND statut!='supprime'`).get(documentId) as {chemin:string}|undefined;if(!doc)throw new Error('Document introuvable.');const documentHash=hashFile(doc.chemin);const signedAt=new Date().toISOString();const signatureHash=createHash('sha256').update(`${documentHash}|${actor.userId}|${actor.roleCode}|${signedAt}`).digest('hex');db.prepare(`INSERT INTO ged_signatures(document_id,signataire_id,signataire_nom,role_code,document_hash,signature_hash,motif,signed_at) VALUES(?,?,?,?,?,?,?,?)`).run(documentId,actor.userId,actor.email,actor.roleCode,documentHash,signatureHash,motif?.trim()||null,signedAt);writeAuditLog({userId:actorId,action:'CREATE',module:'ged',description:`Signature interne document #${documentId}`});return listSignatures(documentId);}
export function listSignatures(documentId:number){return getDatabase().prepare(`SELECT id,signataire_nom,role_code,type_signature,document_hash,signature_hash,motif,statut,signed_at FROM ged_signatures WHERE document_id=? ORDER BY signed_at DESC`).all(documentId);}
