import { randomUUID } from 'node:crypto';
import { getDatabase } from '../database/sqlite';
import { actorCanAccessHotel, getActorContext } from './actorContext';
import { writeAuditLog } from './audit.service';
import { createReservation } from './hebergement.service';
import { createFacture } from './facturation.service';
import { capacityFor, quoteLine } from './mice.rules';

type Row=Record<string,unknown>;
const db=()=>getDatabase();
function access(actorId:number,hotelId:number){if(!actorCanAccessHotel(getActorContext(actorId),hotelId))throw new Error('Accès hôtel refusé.');}
function text(v:string|undefined,label:string){const x=v?.trim();if(!x)throw new Error(`${label} requis.`);return x;}
function eventRow(id:number){const row=db().prepare(`SELECT * FROM mice_evenements WHERE id=?`).get(id)as Row|undefined;if(!row)throw new Error('Événement introuvable.');return row;}
function groupRow(id:number){const row=db().prepare(`SELECT * FROM pms_groupes WHERE id=?`).get(id)as Row|undefined;if(!row)throw new Error('Groupe introuvable.');return row;}
function audit(actorId:number,action:string,description:string){writeAuditLog({userId:actorId,action,module:'mice',page:'/mice',description});}

export function miceDashboard(actorId:number,hotelId:number){access(actorId,hotelId);const groups=db().prepare(`SELECT COUNT(*)total,SUM(statut IN('confirme','en_cours')) actifs,SUM((SELECT COUNT(*)FROM reservations r WHERE r.groupe_id=g.id)) pickup,SUM(allotement) allotement FROM pms_groupes g WHERE hotel_id=?`).get(hotelId);const events=db().prepare(`SELECT COUNT(*)total,SUM(statut IN('confirme','en_cours')) confirmes,SUM(participants) participants FROM mice_evenements WHERE hotel_id=? AND statut!='annule'`).get(hotelId);const spaces=db().prepare(`SELECT COUNT(*) total FROM mice_espaces WHERE hotel_id=? AND actif=1`).get(hotelId);const billing=db().prepare(`SELECT COALESCE(SUM(montant_ttc),0)total,SUM(facture_id IS NULL) non_facturees FROM mice_charges c JOIN mice_evenements e ON e.id=c.evenement_id WHERE e.hotel_id=?`).get(hotelId);return{groups,events,spaces,billing};}

export function groupDetail(actorId:number,groupeId:number){const group=groupRow(groupeId);access(actorId,Number(group.hotel_id));const allotments=db().prepare(`SELECT a.*,t.code type_code,t.label type_label,(SELECT COUNT(*)FROM reservations r LEFT JOIN chambres c ON c.id=r.chambre_id WHERE r.groupe_id=a.groupe_id AND c.type_chambre_id=a.type_chambre_id AND r.statut NOT IN('annulee','no_show')) pickup FROM pms_groupe_allotements a JOIN types_chambres t ON t.id=a.type_chambre_id WHERE a.groupe_id=? ORDER BY t.code`).all(groupeId);const rooming=db().prepare(`SELECT rl.*,t.code type_code,c.numero chambre_numero FROM pms_rooming_list rl LEFT JOIN types_chambres t ON t.id=rl.type_chambre_id LEFT JOIN chambres c ON c.id=rl.chambre_id WHERE rl.groupe_id=? ORDER BY ligne_no`).all(groupeId);const reservations=db().prepare(`SELECT id,client_nom,client_prenom,date_arrivee,date_depart,statut,montant_total FROM reservations WHERE groupe_id=? AND deleted_at IS NULL ORDER BY client_nom`).all(groupeId);return{group,allotments,rooming,reservations};}
export function saveAllotment(actorId:number,input:{groupeId:number;typeChambreId:number;quantite:number;tarifNegocie?:number;dateRelease:string}){const group=groupRow(input.groupeId);access(actorId,Number(group.hotel_id));if(input.quantite<1)throw new Error('Quantité d’allotement invalide.');if(input.dateRelease>String(group.date_arrivee))throw new Error('La date de release doit précéder l’arrivée.');const type=db().prepare(`SELECT id FROM types_chambres WHERE id=? AND hotel_id=?`).get(input.typeChambreId,group.hotel_id);if(!type)throw new Error('Type de chambre incompatible.');const others=db().prepare(`SELECT COALESCE(SUM(quantite),0)n FROM pms_groupe_allotements WHERE groupe_id=? AND type_chambre_id<>?`).get(input.groupeId,input.typeChambreId)as Row;if(Number(others.n)+input.quantite>Number(group.allotement))throw new Error('La ventilation dépasse l’allotement global du groupe.');db().prepare(`INSERT INTO pms_groupe_allotements(groupe_id,type_chambre_id,quantite,tarif_negocie,date_release)VALUES(?,?,?,?,?) ON CONFLICT(groupe_id,type_chambre_id)DO UPDATE SET quantite=excluded.quantite,tarif_negocie=excluded.tarif_negocie,date_release=excluded.date_release,statut='actif'`).run(input.groupeId,input.typeChambreId,input.quantite,input.tarifNegocie??0,input.dateRelease);audit(actorId,'UPDATE',`Allotement groupe #${input.groupeId}`);return true;}
export function releaseAllotments(actorId:number,groupeId:number,date=new Date().toISOString().slice(0,10)){const group=groupRow(groupeId);access(actorId,Number(group.hotel_id));const result=db().prepare(`UPDATE pms_groupe_allotements SET statut='libere' WHERE groupe_id=? AND statut='actif' AND date_release<=?`).run(groupeId,date);return{released:result.changes};}

export interface RoomingInput{nom:string;prenom?:string;email?:string;telephone?:string;typeChambreId?:number;chambreId?:number;dateArrivee?:string;dateDepart?:string;nbAdultes?:number;nbEnfants?:number;notes?:string}
export function importRoomingList(actorId:number,groupeId:number,rows:RoomingInput[]){const group=groupRow(groupeId);access(actorId,Number(group.hotel_id));if(!rows.length)throw new Error('Rooming list vide.');const current=db().prepare(`SELECT COUNT(*)n FROM pms_rooming_list WHERE groupe_id=? AND statut!='annule'`).get(groupeId)as Row;if(Number(current.n)+rows.length>Number(group.allotement))throw new Error('La rooming list dépasse l’allotement du groupe.');const next=Number((db().prepare(`SELECT COALESCE(MAX(ligne_no),0)n FROM pms_rooming_list WHERE groupe_id=?`).get(groupeId)as Row).n)+1;const insert=db().prepare(`INSERT INTO pms_rooming_list(groupe_id,ligne_no,nom,prenom,email,telephone,type_chambre_id,chambre_id,date_arrivee,date_depart,nb_adultes,nb_enfants,notes,statut,erreur)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);let valid=0,errors=0;db().transaction(()=>rows.forEach((r,index)=>{let error:string|null=null;if(!r.nom?.trim())error='Nom requis';const arrival=r.dateArrivee??String(group.date_arrivee),departure=r.dateDepart??String(group.date_depart);if(arrival<String(group.date_arrivee)||departure>String(group.date_depart)||departure<=arrival)error='Dates hors période du groupe';if(r.typeChambreId&&!db().prepare(`SELECT id FROM types_chambres WHERE id=? AND hotel_id=?`).get(r.typeChambreId,group.hotel_id))error='Type de chambre incompatible';if(r.chambreId&&!db().prepare(`SELECT id FROM chambres WHERE id=? AND hotel_id=?`).get(r.chambreId,group.hotel_id))error='Chambre incompatible';insert.run(groupeId,next+index,r.nom?.trim()||'INVALIDE',r.prenom?.trim()||null,r.email?.trim()||null,r.telephone?.trim()||null,r.typeChambreId??null,r.chambreId??null,arrival,departure,r.nbAdultes??1,r.nbEnfants??0,r.notes?.trim()||null,error?'erreur':'valide',error);error?errors++:valid++;}))();audit(actorId,'IMPORT',`Rooming list groupe #${groupeId}: ${valid} valide(s), ${errors} erreur(s)`);return{valid,errors};}
export function reserveRoomingLine(actorId:number,lineId:number){const line=db().prepare(`SELECT rl.*,g.hotel_id,g.allotement,g.code groupe_code FROM pms_rooming_list rl JOIN pms_groupes g ON g.id=rl.groupe_id WHERE rl.id=?`).get(lineId)as Row|undefined;if(!line)throw new Error('Ligne de rooming list introuvable.');access(actorId,Number(line.hotel_id));if(line.statut!=='valide')throw new Error('La ligne doit être validée.');if(line.type_chambre_id){const allot=db().prepare(`SELECT * FROM pms_groupe_allotements WHERE groupe_id=? AND type_chambre_id=? AND statut='actif'`).get(line.groupe_id,line.type_chambre_id)as Row|undefined;if(!allot)throw new Error('Aucun allotement actif pour ce type de chambre.');const pickup=db().prepare(`SELECT COUNT(*)n FROM reservations r LEFT JOIN chambres c ON c.id=r.chambre_id WHERE r.groupe_id=? AND c.type_chambre_id=? AND r.statut NOT IN('annulee','no_show')`).get(line.groupe_id,line.type_chambre_id)as Row;if(Number(pickup.n)>=Number(allot.quantite))throw new Error('Allotement de ce type atteint.');}
  const nights=Math.max(1,Math.round((new Date(String(line.date_depart)).getTime()-new Date(String(line.date_arrivee)).getTime())/86_400_000));const allot=line.type_chambre_id?db().prepare(`SELECT tarif_negocie FROM pms_groupe_allotements WHERE groupe_id=? AND type_chambre_id=?`).get(line.groupe_id,line.type_chambre_id)as Row|undefined:undefined;
  const reservation=createReservation(actorId,{hotelId:Number(line.hotel_id),chambreId:line.chambre_id?Number(line.chambre_id):undefined,dateArrivee:String(line.date_arrivee),dateDepart:String(line.date_depart),nbAdultes:Number(line.nb_adultes),nbEnfants:Number(line.nb_enfants),clientNom:String(line.nom),clientPrenom:line.prenom?String(line.prenom):undefined,clientEmail:line.email?String(line.email):undefined,clientTelephone:line.telephone?String(line.telephone):undefined,montantTotal:allot?Number(allot.tarif_negocie)*nights:0,statut:'confirmee',source:'direct',notes:`Groupe ${line.groupe_code}${line.notes?` — ${line.notes}`:''}`});db().transaction(()=>{db().prepare(`UPDATE reservations SET groupe_id=? WHERE id=?`).run(line.groupe_id,reservation.id);db().prepare(`UPDATE pms_rooming_list SET statut='reserve',reservation_id=?,erreur=NULL WHERE id=?`).run(reservation.id,lineId);})();return{...reservation,groupeId:Number(line.groupe_id)};}

export function listSpaces(actorId:number,hotelId:number){access(actorId,hotelId);return db().prepare(`SELECT * FROM mice_espaces WHERE hotel_id=? AND actif=1 ORDER BY nom`).all(hotelId);}
export function saveSpace(actorId:number,input:{hotelId:number;code:string;nom:string;type?:string;capaciteTheatre?:number;capaciteClasse?:number;capaciteBanquet?:number;tarifHeure?:number;tarifJournee?:number;equipements?:string[]}){access(actorId,input.hotelId);db().prepare(`INSERT INTO mice_espaces(hotel_id,code,nom,type,capacite_theatre,capacite_classe,capacite_banquet,tarif_heure,tarif_journee,equipements_json)VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(hotel_id,code)DO UPDATE SET nom=excluded.nom,type=excluded.type,capacite_theatre=excluded.capacite_theatre,capacite_classe=excluded.capacite_classe,capacite_banquet=excluded.capacite_banquet,tarif_heure=excluded.tarif_heure,tarif_journee=excluded.tarif_journee,equipements_json=excluded.equipements_json,actif=1`).run(input.hotelId,text(input.code,'Code').toUpperCase(),text(input.nom,'Nom'),input.type??'conference',input.capaciteTheatre??0,input.capaciteClasse??0,input.capaciteBanquet??0,input.tarifHeure??0,input.tarifJournee??0,JSON.stringify(input.equipements??[]));return true;}
export function listEvents(actorId:number,hotelId:number){access(actorId,hotelId);return db().prepare(`SELECT e.*,g.nom groupe_nom,c.nom client_nom,(SELECT COUNT(*)FROM mice_reservations_espaces b WHERE b.evenement_id=e.id AND b.statut!='annule') espaces,(SELECT COALESCE(SUM(montant_ttc),0)FROM mice_charges x WHERE x.evenement_id=e.id) total_charges FROM mice_evenements e LEFT JOIN pms_groupes g ON g.id=e.groupe_id LEFT JOIN clients_facturation c ON c.id=e.client_id WHERE e.hotel_id=? ORDER BY e.debut DESC`).all(hotelId);}
export function createEvent(actorId:number,input:{hotelId:number;groupeId?:number;clientId?:number;nom:string;type:string;debut:string;fin:string;participants:number;contactNom?:string;contactEmail?:string;notes?:string}){access(actorId,input.hotelId);if(input.fin<=input.debut)throw new Error('La fin doit suivre le début.');if(input.participants<1)throw new Error('Nombre de participants invalide.');if(input.groupeId&&Number(groupRow(input.groupeId).hotel_id)!==input.hotelId)throw new Error('Groupe incompatible.');const code=`MICE-${new Date().getFullYear()}-${randomUUID().slice(0,8).toUpperCase()}`;const result=db().prepare(`INSERT INTO mice_evenements(uuid,hotel_id,groupe_id,client_id,code,nom,type,debut,fin,participants,contact_nom,contact_email,notes,created_by)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(randomUUID(),input.hotelId,input.groupeId??null,input.clientId??null,code,text(input.nom,'Nom'),input.type,input.debut,input.fin,input.participants,input.contactNom?.trim()||null,input.contactEmail?.trim()||null,input.notes?.trim()||null,actorId);audit(actorId,'CREATE',`Événement ${code}`);return{id:Number(result.lastInsertRowid),code};}
export function bookSpace(actorId:number,input:{evenementId:number;espaceId:number;debut:string;fin:string;disposition?:string;participants:number;montageMinutes?:number;demontageMinutes?:number;tarif?:number;confirmer?:boolean}){const event=eventRow(input.evenementId);access(actorId,Number(event.hotel_id));if(input.fin<=input.debut)throw new Error('Créneau invalide.');const space=db().prepare(`SELECT * FROM mice_espaces WHERE id=? AND hotel_id=? AND actif=1`).get(input.espaceId,event.hotel_id)as Row|undefined;if(!space)throw new Error('Espace incompatible.');const layout=input.disposition??'theatre',capacity=capacityFor(layout,{theatre:Number(space.capacite_theatre),classe:Number(space.capacite_classe),banquet:Number(space.capacite_banquet)});if(input.participants>capacity)throw new Error(`Capacité dépassée (${capacity}).`);const conflict=db().prepare(`SELECT b.id,e.code,e.nom FROM mice_reservations_espaces b JOIN mice_evenements e ON e.id=b.evenement_id WHERE b.espace_id=? AND b.statut!='annule' AND b.debut<? AND b.fin>? LIMIT 1`).get(input.espaceId,input.fin,input.debut)as Row|undefined;if(conflict)throw new Error(`Conflit avec ${conflict.code} — ${conflict.nom}.`);const result=db().prepare(`INSERT INTO mice_reservations_espaces(evenement_id,espace_id,debut,fin,disposition,participants,temps_montage_minutes,temps_demontage_minutes,tarif,statut)VALUES(?,?,?,?,?,?,?,?,?,?)`).run(input.evenementId,input.espaceId,input.debut,input.fin,layout,input.participants,input.montageMinutes??0,input.demontageMinutes??0,input.tarif??space.tarif_journee,input.confirmer?'confirme':'option');return{id:Number(result.lastInsertRowid)};}

export function createQuote(actorId:number,input:{evenementId:number;valideJusquau?:string;conditions?:string}){const event=eventRow(input.evenementId);access(actorId,Number(event.hotel_id));const version=Number((db().prepare(`SELECT COALESCE(MAX(version),0)n FROM mice_devis WHERE evenement_id=?`).get(input.evenementId)as Row).n)+1;const numero=`DEV-${String(event.code)}-V${version}`;const result=db().prepare(`INSERT INTO mice_devis(evenement_id,numero,version,valide_jusquau,conditions,created_by)VALUES(?,?,?,?,?,?)`).run(input.evenementId,numero,version,input.valideJusquau??null,input.conditions?.trim()||null,actorId);return{id:Number(result.lastInsertRowid),numero};}
function recalcQuote(devisId:number){const total=db().prepare(`SELECT COALESCE(SUM(montant_ht),0)ht,COALESCE(SUM(montant_tva),0)tva,COALESCE(SUM(montant_ttc),0)ttc FROM mice_devis_lignes WHERE devis_id=?`).get(devisId)as Row;db().prepare(`UPDATE mice_devis SET montant_ht=?,montant_tva=?,montant_ttc=? WHERE id=?`).run(total.ht,total.tva,total.ttc,devisId);return total;}
export function addQuoteLine(actorId:number,input:{devisId:number;categorie:string;designation:string;quantite:number;prixUnitaire:number;tauxTva?:number}){const quote=db().prepare(`SELECT d.*,e.hotel_id FROM mice_devis d JOIN mice_evenements e ON e.id=d.evenement_id WHERE d.id=?`).get(input.devisId)as Row|undefined;if(!quote)throw new Error('Devis introuvable.');access(actorId,Number(quote.hotel_id));if(quote.statut!=='brouillon')throw new Error('Devis non modifiable.');const amount=quoteLine(input.quantite,input.prixUnitaire,input.tauxTva??19);const order=Number((db().prepare(`SELECT COALESCE(MAX(ordre),0)n FROM mice_devis_lignes WHERE devis_id=?`).get(input.devisId)as Row).n)+1;db().prepare(`INSERT INTO mice_devis_lignes(devis_id,categorie,designation,quantite,prix_unitaire,taux_tva,montant_ht,montant_tva,montant_ttc,ordre)VALUES(?,?,?,?,?,?,?,?,?,?)`).run(input.devisId,input.categorie,text(input.designation,'Désignation'),input.quantite,input.prixUnitaire,input.tauxTva??19,amount.ht,amount.tax,amount.ttc,order);return recalcQuote(input.devisId);}
export function setQuoteStatus(actorId:number,devisId:number,status:'envoye'|'accepte'|'refuse'|'expire'){const quote=db().prepare(`SELECT d.*,e.hotel_id,e.id evenement_id FROM mice_devis d JOIN mice_evenements e ON e.id=d.evenement_id WHERE d.id=?`).get(devisId)as Row|undefined;if(!quote)throw new Error('Devis introuvable.');access(actorId,Number(quote.hotel_id));if(status==='accepte'&&Number(quote.montant_ttc)<=0)throw new Error('Un devis vide ne peut pas être accepté.');db().transaction(()=>{db().prepare(`UPDATE mice_devis SET statut=? WHERE id=?`).run(status,devisId);if(status==='accepte')db().prepare(`UPDATE mice_evenements SET statut='confirme',updated_at=datetime('now')WHERE id=?`).run(quote.evenement_id);})();audit(actorId,'UPDATE',`Devis #${devisId}: ${status}`);return true;}
export function listEventDocuments(actorId:number,eventId:number){const event=eventRow(eventId);access(actorId,Number(event.hotel_id));return{quotes:db().prepare(`SELECT * FROM mice_devis WHERE evenement_id=? ORDER BY version DESC`).all(eventId),beos:db().prepare(`SELECT * FROM mice_beo WHERE evenement_id=? ORDER BY version DESC`).all(eventId),bookings:db().prepare(`SELECT b.*,s.nom espace_nom FROM mice_reservations_espaces b JOIN mice_espaces s ON s.id=b.espace_id WHERE b.evenement_id=? ORDER BY b.debut`).all(eventId),charges:db().prepare(`SELECT * FROM mice_charges WHERE evenement_id=? ORDER BY id`).all(eventId)};}
export function saveBeo(actorId:number,input:{evenementId:number;programme?:unknown[];menu?:unknown[];miseEnPlace?:unknown;audiovisuel?:unknown[];consignes?:string;contacts?:unknown[];diffuser?:boolean}){const event=eventRow(input.evenementId);access(actorId,Number(event.hotel_id));const version=Number((db().prepare(`SELECT COALESCE(MAX(version),0)n FROM mice_beo WHERE evenement_id=?`).get(input.evenementId)as Row).n)+1,numero=`BEO-${String(event.code)}-V${version}`;const result=db().prepare(`INSERT INTO mice_beo(evenement_id,numero,version,statut,programme_json,menu_json,mise_en_place_json,audiovisuel_json,consignes,contacts_json,diffuse_at,created_by)VALUES(?,?,?,?,?,?,?,?,?,?,CASE WHEN ?=1 THEN datetime('now')END,?)`).run(input.evenementId,numero,version,input.diffuser?'diffuse':'brouillon',JSON.stringify(input.programme??[]),JSON.stringify(input.menu??[]),JSON.stringify(input.miseEnPlace??{}),JSON.stringify(input.audiovisuel??[]),input.consignes?.trim()||null,JSON.stringify(input.contacts??[]),input.diffuser?1:0,actorId);audit(actorId,input.diffuser?'BEO_DISTRIBUTED':'CREATE',`${numero}`);return{id:Number(result.lastInsertRowid),numero};}
export function addEventCharge(actorId:number,input:{evenementId:number;categorie:string;designation:string;quantite:number;prixUnitaire:number;tauxTva?:number}){const event=eventRow(input.evenementId);access(actorId,Number(event.hotel_id));const amount=quoteLine(input.quantite,input.prixUnitaire,input.tauxTva??19);const result=db().prepare(`INSERT INTO mice_charges(evenement_id,categorie,designation,quantite,prix_unitaire,taux_tva,montant_ht,montant_tva,montant_ttc,created_by)VALUES(?,?,?,?,?,?,?,?,?,?)`).run(input.evenementId,text(input.categorie,'Catégorie'),text(input.designation,'Désignation'),input.quantite,input.prixUnitaire,input.tauxTva??19,amount.ht,amount.tax,amount.ttc,actorId);return{id:Number(result.lastInsertRowid),...amount};}
export function invoiceEvent(actorId:number,eventId:number){const event=eventRow(eventId);access(actorId,Number(event.hotel_id));const charges=db().prepare(`SELECT * FROM mice_charges WHERE evenement_id=? AND facture_id IS NULL ORDER BY id`).all(eventId)as Row[];if(!charges.length)throw new Error('Aucune charge à facturer.');const invoice=createFacture(actorId,{hotelId:Number(event.hotel_id),clientId:event.client_id?Number(event.client_id):undefined,clientNom:String(event.contact_nom||event.nom),notes:`Facturation événement ${event.code}`,lignes:charges.map(c=>({designation:String(c.designation),quantite:Number(c.quantite),prixUnitaire:Number(c.prix_unitaire),tauxTva:Number(c.taux_tva)}))});db().prepare(`UPDATE mice_charges SET facture_id=? WHERE evenement_id=? AND facture_id IS NULL`).run(invoice.id,eventId);audit(actorId,'INVOICE',`Événement ${event.code} → facture ${invoice.numero}`);return invoice;}

