import { getDatabase } from '../database/sqlite';
import { writeAuditLog } from './audit.service';
import { actorCanAccessHotel, getActorContext } from './actorContext';
import { assertPermission } from './permissions.service';
import { createTicket, getTicketById, recalcTicketTotals } from './pos.service';
import { genererEcritureRemboursementRestauration } from './comptabilite.service';
import { refundableBalance } from './pos-restaurant.rules';
import type { CreateSalleInput, PosEtapeService, PosSalle, PosTable, PosTableStatut, SaveTableInput } from '../../src/shared/types/pos';

function assertHotel(actorId:number,hotelId:number):void{if(!actorCanAccessHotel(getActorContext(actorId),hotelId))throw new Error('Accès hôtel refusé.');}
function pointHotel(pointVenteId:number):number{const r=getDatabase().prepare(`SELECT hotel_id FROM pos_points_vente WHERE id=? AND actif=1`).get(pointVenteId) as {hotel_id:number}|undefined;if(!r)throw new Error('Point de vente introuvable.');return r.hotel_id;}
function ticketHotel(ticketId:number):number{return getTicketById(ticketId).hotelId;}
function event(ticketId:number,type:string,details:unknown,actorId:number):void{getDatabase().prepare(`INSERT INTO pos_ticket_evenements(ticket_id,type_evenement,details_json,effectue_par) VALUES(?,?,?,?)`).run(ticketId,type,JSON.stringify(details??{}),actorId);}

export function listSalles(actorId:number,pointVenteId:number):PosSalle[]{assertHotel(actorId,pointHotel(pointVenteId));return(getDatabase().prepare(`SELECT * FROM pos_salles WHERE point_vente_id=? AND actif=1 ORDER BY nom`).all(pointVenteId) as Record<string,unknown>[]).map(r=>({id:Number(r.id),pointVenteId:Number(r.point_vente_id),nom:String(r.nom),largeur:Number(r.largeur),hauteur:Number(r.hauteur),actif:Number(r.actif)===1}));}
export function createSalle(actorId:number,input:CreateSalleInput):PosSalle{assertHotel(actorId,pointHotel(input.pointVenteId));if(!input.nom.trim())throw new Error('Nom de salle obligatoire.');const r=getDatabase().prepare(`INSERT INTO pos_salles(point_vente_id,nom,largeur,hauteur) VALUES(?,?,?,?)`).run(input.pointVenteId,input.nom.trim(),input.largeur??1000,input.hauteur??700);writeAuditLog({userId:actorId,action:'CREATE',module:'pos',description:`Salle POS ${input.nom}`});return listSalles(actorId,input.pointVenteId).find(s=>s.id===Number(r.lastInsertRowid))!;}

export function listTables(actorId:number,salleId:number):PosTable[]{const db=getDatabase();const salle=db.prepare(`SELECT point_vente_id FROM pos_salles WHERE id=?`).get(salleId) as {point_vente_id:number}|undefined;if(!salle)throw new Error('Salle introuvable.');assertHotel(actorId,pointHotel(salle.point_vente_id));return(db.prepare(`SELECT t.*,(SELECT id FROM pos_tickets x WHERE x.table_id=t.id AND x.statut='brouillon' ORDER BY x.id DESC LIMIT 1) ticket_actif_id FROM pos_tables t WHERE t.salle_id=? AND t.actif=1 ORDER BY t.numero`).all(salleId) as Record<string,unknown>[]).map(mapTable);}
function mapTable(r:Record<string,unknown>):PosTable{return{id:Number(r.id),salleId:Number(r.salle_id),numero:String(r.numero),capacite:Number(r.capacite),forme:r.forme as PosTable['forme'],positionX:Number(r.position_x),positionY:Number(r.position_y),largeur:Number(r.largeur),hauteur:Number(r.hauteur),statut:r.statut as PosTableStatut,actif:Number(r.actif)===1,ticketActifId:r.ticket_actif_id?Number(r.ticket_actif_id):null};}
export function saveTable(actorId:number,input:SaveTableInput,tableId?:number):PosTable{const db=getDatabase();const salle=db.prepare(`SELECT point_vente_id FROM pos_salles WHERE id=?`).get(input.salleId) as {point_vente_id:number}|undefined;if(!salle)throw new Error('Salle introuvable.');assertHotel(actorId,pointHotel(salle.point_vente_id));if(!input.numero.trim())throw new Error('Numéro de table obligatoire.');let id=tableId;if(id){const n=db.prepare(`UPDATE pos_tables SET numero=?,capacite=?,forme=?,position_x=?,position_y=?,largeur=?,hauteur=?,statut=?,updated_at=datetime('now') WHERE id=? AND salle_id=?`).run(input.numero.trim(),input.capacite??2,input.forme??'carree',input.positionX??0,input.positionY??0,input.largeur??90,input.hauteur??90,input.statut??'libre',id,input.salleId).changes;if(!n)throw new Error('Table introuvable.');}else{id=Number(db.prepare(`INSERT INTO pos_tables(salle_id,numero,capacite,forme,position_x,position_y,largeur,hauteur,statut) VALUES(?,?,?,?,?,?,?,?,?)`).run(input.salleId,input.numero.trim(),input.capacite??2,input.forme??'carree',input.positionX??0,input.positionY??0,input.largeur??90,input.hauteur??90,input.statut??'libre').lastInsertRowid);}return listTables(actorId,input.salleId).find(t=>t.id===id)!;}
export function updateTableStatus(actorId:number,tableId:number,statut:PosTableStatut):PosTable{const db=getDatabase();const r=db.prepare(`SELECT salle_id FROM pos_tables WHERE id=?`).get(tableId) as {salle_id:number}|undefined;if(!r)throw new Error('Table introuvable.');const current=listTables(actorId,r.salle_id).find(t=>t.id===tableId)!;if(current.ticketActifId&&['libre','hors_service'].includes(statut))throw new Error('Un ticket est encore ouvert sur cette table.');db.prepare(`UPDATE pos_tables SET statut=?,updated_at=datetime('now') WHERE id=?`).run(statut,tableId);return listTables(actorId,r.salle_id).find(t=>t.id===tableId)!;}

export function assignTicketTable(actorId:number,ticketId:number,tableId:number,nbCouverts:number):void{const db=getDatabase();const ticket=getTicketById(ticketId);assertHotel(actorId,ticket.hotelId);if(ticket.statut!=='brouillon')throw new Error('Ticket non modifiable.');const table=db.prepare(`SELECT t.id,t.capacite,s.point_vente_id,EXISTS(SELECT 1 FROM pos_tickets x WHERE x.table_id=t.id AND x.statut='brouillon' AND x.id<>?) ticket_ouvert FROM pos_tables t JOIN pos_salles s ON s.id=t.salle_id WHERE t.id=? AND t.actif=1`).get(ticketId,tableId) as {id:number;capacite:number;point_vente_id:number;ticket_ouvert:number}|undefined;if(!table||table.point_vente_id!==ticket.pointVenteId)throw new Error('Table incompatible.');if(table.ticket_ouvert)throw new Error('Un ticket est déjà ouvert sur cette table.');if(nbCouverts<1||nbCouverts>table.capacite)throw new Error(`Nombre de couverts supérieur à la capacité (${table.capacite}).`);db.transaction(()=>{if(ticket.tableId&&ticket.tableId!==tableId)db.prepare(`UPDATE pos_tables SET statut='libre',updated_at=datetime('now') WHERE id=?`).run(ticket.tableId);db.prepare(`UPDATE pos_tickets SET table_id=?,nb_couverts=? WHERE id=?`).run(tableId,nbCouverts,ticketId);db.prepare(`UPDATE pos_tables SET statut='occupee',updated_at=datetime('now') WHERE id=?`).run(tableId);event(ticketId,'affectation_table',{tableId,nbCouverts},actorId);})();}
export function updateServiceStage(actorId:number,ticketId:number,etape:PosEtapeService):void{assertHotel(actorId,ticketHotel(ticketId));const ticket=getTicketById(ticketId);if(ticket.statut!=='brouillon')throw new Error('Service déjà terminé.');getDatabase().prepare(`UPDATE pos_tickets SET etape_service=? WHERE id=?`).run(etape,ticketId);event(ticketId,'etape_service',{etape},actorId);}

export function splitTicket(actorId:number,ticketId:number,lineIds:number[]):number{const db=getDatabase();const source=getTicketById(ticketId);assertHotel(actorId,source.hotelId);if(source.statut!=='brouillon'||!lineIds.length)throw new Error('Ticket source invalide.');if(lineIds.length>=source.lignes.length)throw new Error('Laissez au moins une ligne sur le ticket source.');const created=db.transaction(()=>{for(const id of lineIds){if(!source.lignes.some(l=>l.id===id))throw new Error(`Ligne #${id} incompatible.`);}const child=createTicket(actorId,{sessionId:source.sessionId,nbCouverts:Math.max(1,Math.floor(source.nbCouverts/2))});db.prepare(`UPDATE pos_tickets SET parent_ticket_id=?,table_id=? WHERE id=?`).run(ticketId,source.tableId,child.id);for(const id of lineIds)db.prepare(`UPDATE pos_ticket_lignes SET ticket_id=? WHERE id=?`).run(child.id,id);recalcTicketTotals(ticketId);recalcTicketTotals(child.id);event(ticketId,'partage_note',{ticketDestinationId:child.id,lineIds},actorId);return child.id;})();return created;}

export function applyDiscount(actorId:number,ticketId:number,input:{type:'pourcentage'|'montant';valeur:number;motif:string}):void{assertPermission(actorId,'pos.remise.autoriser');const ticket=getTicketById(ticketId);assertHotel(actorId,ticket.hotelId);if(ticket.statut!=='brouillon')throw new Error('Ticket non modifiable.');if(input.valeur<=0||!input.motif.trim())throw new Error('Valeur et motif de remise obligatoires.');if(input.type==='pourcentage'&&input.valeur>100)throw new Error('Pourcentage de remise invalide.');getDatabase().prepare(`UPDATE pos_tickets SET remise_montant=?,remise_pourcentage=?,remise_motif=?,remise_autorisee_par=? WHERE id=?`).run(input.type==='montant'?input.valeur:0,input.type==='pourcentage'?input.valeur:0,input.motif.trim(),actorId,ticketId);recalcTicketTotals(ticketId);event(ticketId,'remise',{...input},actorId);writeAuditLog({userId:actorId,action:'UPDATE',module:'pos',description:`Remise ticket ${ticket.numero} autorisée`});}

export function refundTicket(actorId:number,ticketId:number,input:{montant:number;mode:'especes'|'carte'|'cheque'|'virement'|'autre'|'folio';motif:string;reference?:string;remettreEnStock?:boolean}):void{assertPermission(actorId,'pos.remboursement.autoriser');const db=getDatabase();const ticket=getTicketById(ticketId);assertHotel(actorId,ticket.hotelId);if(!['valide','rembourse'].includes(ticket.statut))throw new Error('Seul un ticket encaissé peut être remboursé.');const refunded=(db.prepare(`SELECT COALESCE(SUM(montant),0) total FROM pos_ticket_remboursements WHERE ticket_id=?`).get(ticketId) as {total:number}).total;const remaining=refundableBalance(ticket.totalTtc,refunded);if(input.montant<=0||input.montant>remaining+0.01)throw new Error(`Montant remboursable maximal : ${remaining} DA.`);if(!input.motif.trim())throw new Error('Motif du remboursement obligatoire.');
  db.transaction(()=>{db.prepare(`INSERT INTO pos_ticket_remboursements(ticket_id,montant,mode,motif,reference,remettre_en_stock,autorise_par,created_by) VALUES(?,?,?,?,?,?,?,?)`).run(ticketId,input.montant,input.mode,input.motif.trim(),input.reference?.trim()||null,input.remettreEnStock?1:0,actorId,actorId);if(input.mode==='especes')db.prepare(`INSERT INTO journal_caisse(hotel_id,date_operation,libelle,entree,sortie,created_by) VALUES(?,?,?,0,?,?)`).run(ticket.hotelId,ticket.dateTicket,`Remboursement POS ${ticket.numero}`,input.montant,actorId);db.prepare(`UPDATE pos_sessions SET total_ventes=MAX(0,total_ventes-?) WHERE id=?`).run(input.montant,ticket.sessionId);const col=input.mode==='especes'?'total_especes':input.mode==='carte'?'total_carte':input.mode==='cheque'?'total_cheque':input.mode==='virement'?'total_virement':null;if(col)db.prepare(`UPDATE pos_sessions SET ${col}=MAX(0,${col}-?) WHERE id=?`).run(input.montant,ticket.sessionId);if(input.montant>=remaining-0.01)db.prepare(`UPDATE pos_tickets SET statut='rembourse' WHERE id=?`).run(ticketId);event(ticketId,'remboursement',input,actorId);})();
  genererEcritureRemboursementRestauration(actorId,{ticketId:ticket.id,hotelId:ticket.hotelId,dateTicket:ticket.dateTicket,numero:ticket.numero,totalTtc:ticket.totalTtc,totalHt:ticket.totalHt,tvaMontant:ticket.tvaMontant,modePaiement:input.mode},input.mode,input.montant);writeAuditLog({userId:actorId,action:'UPDATE',module:'pos',description:`Remboursement ${input.montant} DA ticket ${ticket.numero}`});}
