import { getDatabase } from '../database/sqlite';
import { actorCanAccessHotel, getActorContext } from './actorContext';
import { assertPermission } from './permissions.service';
import { writeAuditLog } from './audit.service';
import { payFacture } from './achats-advanced.service';
import { creerEcriture } from './comptabilite.service';
import { parseBankCsv, reconciliationScore } from './tresorerie-advanced.rules';

const db=()=>getDatabase();
const round2=(n:number)=>Math.round(n*100)/100;
function assertHotel(actorId:number,hotelId:number){if(!actorCanAccessHotel(getActorContext(actorId),hotelId))throw new Error('Accès hôtel refusé.');}
function nextOrder(){const year=new Date().getFullYear();const n=(db().prepare(`SELECT COUNT(*) n FROM ordres_paiement WHERE numero LIKE ?`).get(`OP-${year}-%`) as {n:number}).n+1;return `OP-${year}-${String(n).padStart(5,'0')}`;}

export function listPaymentOrders(actorId:number,hotelId?:number){const actor=getActorContext(actorId);if(hotelId)assertHotel(actorId,hotelId);let where='';const p:unknown[]=[];if(hotelId){where='WHERE op.hotel_id=?';p.push(hotelId);}else if(!actor.allHotelsAccess){if(!actor.hotelIds.length)return[];where=`WHERE op.hotel_id IN (${actor.hotelIds.map(()=>'?').join(',')})`;p.push(...actor.hotelIds);}return db().prepare(`SELECT op.*,cb.intitule compte_bancaire,ff.numero facture_numero FROM ordres_paiement op LEFT JOIN comptes_bancaires cb ON cb.id=op.compte_bancaire_id LEFT JOIN factures_fournisseurs ff ON ff.id=op.facture_fournisseur_id ${where} ORDER BY op.id DESC`).all(...p);}
export function createPaymentOrder(actorId:number,input:{hotelId:number;factureFournisseurId?:number;compteBancaireId?:number;beneficiaire:string;montant:number;mode:'virement'|'cheque'|'prelevement'|'autre';dateEcheance:string;reference?:string;numeroCheque?:string}){assertHotel(actorId,input.hotelId);if(input.montant<=0||!input.beneficiaire.trim())throw new Error('Ordre de paiement invalide.');if(input.mode==='cheque'&&!input.numeroCheque?.trim())throw new Error('Numéro de chèque requis.');const r=db().prepare(`INSERT INTO ordres_paiement(numero,hotel_id,facture_fournisseur_id,compte_bancaire_id,beneficiaire,montant,mode,date_echeance,reference,numero_cheque,statut,cree_par) VALUES(?,?,?,?,?,?,?,?,?,?, 'soumis',?)`).run(nextOrder(),input.hotelId,input.factureFournisseurId??null,input.compteBancaireId??null,input.beneficiaire.trim(),input.montant,input.mode,input.dateEcheance,input.reference??null,input.numeroCheque??null,actorId);writeAuditLog({userId:actorId,action:'CREATE',module:'tresorerie',description:`Ordre de paiement #${r.lastInsertRowid}`});return listPaymentOrders(actorId,input.hotelId).find((x:any)=>x.id===Number(r.lastInsertRowid));}
export function decidePaymentOrder(actorId:number,id:number,approved:boolean){assertPermission(actorId,'tresorerie.ordre.approuver');const row=db().prepare(`SELECT * FROM ordres_paiement WHERE id=?`).get(id) as Record<string,unknown>|undefined;if(!row)throw new Error('Ordre introuvable.');assertHotel(actorId,Number(row.hotel_id));if(row.statut!=='soumis')throw new Error('Ordre non soumis.');db().prepare(`UPDATE ordres_paiement SET statut=?,approuve_par=?,approuve_at=datetime('now'),updated_at=datetime('now') WHERE id=?`).run(approved?'approuve':'rejete',actorId,id);return listPaymentOrders(actorId,Number(row.hotel_id)).find((x:any)=>x.id===id);}
export function executePaymentOrder(actorId:number,id:number){assertPermission(actorId,'tresorerie.ordre.executer');const row=db().prepare(`SELECT * FROM ordres_paiement WHERE id=?`).get(id) as Record<string,unknown>|undefined;if(!row)throw new Error('Ordre introuvable.');const hotelId=Number(row.hotel_id);assertHotel(actorId,hotelId);if(row.statut!=='approuve')throw new Error('Ordre non approuvé.');if(!row.facture_fournisseur_id)throw new Error('Une facture fournisseur est requise pour exécuter cet ordre.');payFacture(actorId,Number(row.facture_fournisseur_id),{datePaiement:new Date().toISOString().slice(0,10),montant:Number(row.montant),mode:row.mode as 'virement'|'cheque'|'prelevement'|'autre',reference:String(row.reference??row.numero_cheque??row.numero),compteBancaireId:row.compte_bancaire_id?Number(row.compte_bancaire_id):undefined});const payment=db().prepare(`SELECT id FROM paiements_fournisseurs WHERE facture_id=? AND created_by=? ORDER BY id DESC LIMIT 1`).get(row.facture_fournisseur_id,actorId) as {id:number};const entry=creerEcriture(actorId,{journalCode:'BQ',dateEcriture:new Date().toISOString().slice(0,10),piece:String(row.numero),libelle:`Paiement ${row.beneficiaire}`,hotelId,lignes:[{compteNumero:'401000',debit:Number(row.montant)},{compteNumero:'512000',credit:Number(row.montant)}],sourceModule:'tresorerie',sourceRef:String(row.numero)},true);db().prepare(`UPDATE ordres_paiement SET statut='execute',execute_par=?,execute_at=datetime('now'),paiement_fournisseur_id=?,ecriture_comptable_id=?,updated_at=datetime('now') WHERE id=?`).run(actorId,payment.id,entry.id,id);writeAuditLog({userId:actorId,action:'UPDATE',module:'tresorerie',description:`Ordre ${row.numero} exécuté et comptabilisé`});return listPaymentOrders(actorId,hotelId).find((x:any)=>x.id===id);}

export function listForecast(actorId:number,hotelId:number,dateFrom:string,dateTo:string){assertHotel(actorId,hotelId);const explicit=db().prepare(`SELECT id,date_prevue date,libelle,categorie,sens,montant,probabilite,statut,'manuel' source FROM previsions_tresorerie WHERE hotel_id=? AND date_prevue BETWEEN ? AND ? AND statut!='annulee'`).all(hotelId,dateFrom,dateTo) as any[];const suppliers=db().prepare(`SELECT -e.id id,e.date_echeance date,'Échéance '||f.raison_sociale||' / '||ff.numero libelle,'fournisseur' categorie,'decaissement' sens,(e.montant-e.montant_paye) montant,100 probabilite,e.statut,'facture_fournisseur' source FROM echeances_fournisseurs e JOIN factures_fournisseurs ff ON ff.id=e.facture_id JOIN fournisseurs f ON f.id=ff.fournisseur_id WHERE ff.hotel_id=? AND e.date_echeance BETWEEN ? AND ? AND e.statut!='payee'`).all(hotelId,dateFrom,dateTo) as any[];const lines=[...explicit,...suppliers].sort((a,b)=>String(a.date).localeCompare(String(b.date)));let cumulative=0;return lines.map(x=>{const weighted=Number(x.montant)*Number(x.probabilite)/100*(x.sens==='encaissement'?1:-1);cumulative=round2(cumulative+weighted);return{...x,impactPondere:round2(weighted),soldeCumule:cumulative};});}
export function createForecast(actorId:number,input:{hotelId:number;datePrevue:string;libelle:string;categorie:string;sens:'encaissement'|'decaissement';montant:number;probabilite?:number}){assertHotel(actorId,input.hotelId);if(input.montant<=0)throw new Error('Montant invalide.');const r=db().prepare(`INSERT INTO previsions_tresorerie(hotel_id,date_prevue,libelle,categorie,sens,montant,probabilite,created_by) VALUES(?,?,?,?,?,?,?,?)`).run(input.hotelId,input.datePrevue,input.libelle,input.categorie,input.sens,input.montant,input.probabilite??100,actorId);return{id:Number(r.lastInsertRowid)};}

export function importBankStatement(actorId:number,input:{compteBancaireId:number;nomFichier:string;csv:string;soldeOuverture?:number;soldeCloture?:number}){const account=db().prepare(`SELECT hotel_id FROM comptes_bancaires WHERE id=?`).get(input.compteBancaireId) as {hotel_id:number}|undefined;if(!account)throw new Error('Compte bancaire introuvable.');assertHotel(actorId,account.hotel_id);const rows=parseBankCsv(input.csv);const dates=rows.map(x=>x.dateOperation).sort();const id=db().transaction(()=>{const r=db().prepare(`INSERT INTO releves_bancaires(compte_bancaire_id,nom_fichier,date_debut,date_fin,solde_ouverture,solde_cloture,nb_lignes,importe_par) VALUES(?,?,?,?,?,?,?,?)`).run(input.compteBancaireId,input.nomFichier,dates[0],dates.at(-1),input.soldeOuverture??null,input.soldeCloture??null,rows.length,actorId);const id=Number(r.lastInsertRowid);const stmt=db().prepare(`INSERT INTO releve_bancaire_lignes(releve_id,date_operation,date_valeur,libelle,reference,debit,credit,solde,empreinte) VALUES(?,?,?,?,?,?,?,?,?)`);for(const x of rows)stmt.run(id,x.dateOperation,x.dateValeur??null,x.libelle,x.reference??null,x.debit,x.credit,x.solde??null,x.empreinte);return id;})();writeAuditLog({userId:actorId,action:'IMPORT',module:'tresorerie',description:`Relevé ${input.nomFichier} — ${rows.length} lignes`});return{id,nbLignes:rows.length};}
export function listBankLines(actorId:number,compteBancaireId:number){const account=db().prepare(`SELECT hotel_id FROM comptes_bancaires WHERE id=?`).get(compteBancaireId) as {hotel_id:number}|undefined;if(!account)throw new Error('Compte bancaire introuvable.');assertHotel(actorId,account.hotel_id);return db().prepare(`SELECT l.*,r.nom_fichier,(SELECT json_group_array(json_object('type',s.type_source,'id',s.source_id,'score',s.score)) FROM rapprochements_bancaires s WHERE s.ligne_releve_id=l.id) rapprochements FROM releve_bancaire_lignes l JOIN releves_bancaires r ON r.id=l.releve_id WHERE r.compte_bancaire_id=? ORDER BY l.date_operation DESC,l.id DESC`).all(compteBancaireId);}
export function suggestReconciliation(actorId:number,lineId:number){const line=db().prepare(`SELECT l.*,cb.hotel_id FROM releve_bancaire_lignes l JOIN releves_bancaires r ON r.id=l.releve_id JOIN comptes_bancaires cb ON cb.id=r.compte_bancaire_id WHERE l.id=?`).get(lineId) as any;if(!line)throw new Error('Ligne bancaire introuvable.');assertHotel(actorId,line.hotel_id);const amount=Number(line.credit||line.debit);const sources:any[]=(line.credit>0?db().prepare(`SELECT id,date_encaissement date,reference,montant,'encaissement' type FROM encaissements WHERE hotel_id=? AND statut='confirme' AND deleted_at IS NULL AND ABS(montant-?)<0.01`).all(line.hotel_id,amount):db().prepare(`SELECT p.id,p.date_paiement date,p.reference,p.montant,'paiement_fournisseur' type FROM paiements_fournisseurs p JOIN factures_fournisseurs f ON f.id=p.facture_id WHERE f.hotel_id=? AND ABS(p.montant-?)<0.01`).all(line.hotel_id,amount)) as any[];return sources.map(s=>({...s,score:reconciliationScore({dateOperation:line.date_operation,reference:line.reference,amount},{date:s.date,reference:s.reference,amount:s.montant})})).filter(s=>s.score>0).sort((a,b)=>b.score-a.score).slice(0,10);}
export function confirmReconciliation(actorId:number,input:{lineId:number;typeSource:'encaissement'|'paiement_fournisseur'|'ecriture';sourceId:number;montantSource:number;score?:number}){assertPermission(actorId,'tresorerie.rapprocher');const line=db().prepare(`SELECT l.*,cb.hotel_id FROM releve_bancaire_lignes l JOIN releves_bancaires r ON r.id=l.releve_id JOIN comptes_bancaires cb ON cb.id=r.compte_bancaire_id WHERE l.id=?`).get(input.lineId) as any;if(!line)throw new Error('Ligne bancaire introuvable.');assertHotel(actorId,line.hotel_id);if(line.statut==='rapprochee')throw new Error('Ligne déjà rapprochée.');const bankAmount=Number(line.credit||line.debit),gap=round2(bankAmount-input.montantSource);const r=db().prepare(`INSERT INTO rapprochements_bancaires(ligne_releve_id,type_source,source_id,montant_banque,montant_source,ecart,score,statut,confirme_par,confirme_at) VALUES(?,?,?,?,?,?,?,'confirme',?,datetime('now'))`).run(input.lineId,input.typeSource,input.sourceId,bankAmount,input.montantSource,gap,input.score??0,actorId);db().prepare(`UPDATE releve_bancaire_lignes SET statut='rapprochee' WHERE id=?`).run(input.lineId);return{id:Number(r.lastInsertRowid),ecart:gap};}

export function listCostCenters(actorId:number,hotelId:number){assertHotel(actorId,hotelId);return db().prepare(`SELECT * FROM centres_cout WHERE hotel_id=? ORDER BY code`).all(hotelId);}
export function createCostCenter(actorId:number,input:{hotelId:number;code:string;libelle:string;responsable?:string}){assertHotel(actorId,input.hotelId);const r=db().prepare(`INSERT INTO centres_cout(hotel_id,code,libelle,responsable) VALUES(?,?,?,?)`).run(input.hotelId,input.code.trim().toUpperCase(),input.libelle.trim(),input.responsable??null);return{id:Number(r.lastInsertRowid),...input};}
export function allocateCost(actorId:number,input:{ligneEcritureId:number;centreCoutId:number;montant:number;pourcentage:number}){const row=db().prepare(`SELECT COALESCE(l.hotel_id,e.hotel_id) hotel_id,l.debit,l.credit FROM lignes_ecriture l JOIN ecritures_comptables e ON e.id=l.ecriture_id WHERE l.id=?`).get(input.ligneEcritureId) as any;if(!row)throw new Error('Ligne comptable introuvable.');assertHotel(actorId,Number(row.hotel_id));const base=Math.max(Number(row.debit),Number(row.credit));const allocated=Number((db().prepare(`SELECT COALESCE(SUM(montant),0) n FROM ventilations_analytiques WHERE ligne_ecriture_id=?`).get(input.ligneEcritureId) as {n:number}).n);if(input.montant<=0||allocated+input.montant>base+0.01)throw new Error('La ventilation dépasse le montant de la ligne.');db().prepare(`INSERT INTO ventilations_analytiques(ligne_ecriture_id,centre_cout_id,montant,pourcentage,created_by) VALUES(?,?,?,?,?)`).run(input.ligneEcritureId,input.centreCoutId,input.montant,input.pourcentage,actorId);return true;}
export function analyticalReport(actorId:number,hotelId:number,dateFrom:string,dateTo:string){assertHotel(actorId,hotelId);return db().prepare(`SELECT cc.code,cc.libelle,SUM(CASE WHEN c.classe IN (6,7) THEN va.montant ELSE 0 END) montant,COUNT(DISTINCT le.ecriture_id) ecritures FROM ventilations_analytiques va JOIN centres_cout cc ON cc.id=va.centre_cout_id JOIN lignes_ecriture le ON le.id=va.ligne_ecriture_id JOIN ecritures_comptables e ON e.id=le.ecriture_id JOIN comptes c ON c.id=le.compte_id WHERE cc.hotel_id=? AND e.date_ecriture BETWEEN ? AND ? AND e.statut='valide' GROUP BY cc.id ORDER BY cc.code`).all(hotelId,dateFrom,dateTo);}
